import * as fs from "node:fs/promises";
import * as path from "node:path";
import { scaffold } from "../../flux-core/index";
import { inlineSlideFixture, inlineSlideSvg } from "../fixtures/inline-slide";
import { createSlideRepository } from "../../src/lib/slide/embedRepository";
import { prepareSlideDocument } from "../../src/lib/slide/embedDocument";
import { ensureDom } from "../../flux-core/render";
const root = process.argv[2];
if (!root) throw new Error("Pass scratch project path");
await scaffold(root, { title: "Inline slide verification" });
const write = async (rel: string, text: string) => { const abs = path.join(root, rel); await fs.mkdir(path.dirname(abs), { recursive: true }); await fs.writeFile(abs, text); };
const manifest = JSON.parse(await fs.readFile(`${root}/project.json`, "utf8"));
manifest.slides = [{ id: "talk", path: "slides/talk/deck.json" }];
manifest.manuscript.path = "paper/main.qmd";
manifest.manuscript.config = "paper/_quarto.yml";
manifest.supplementary = [{ path: "paper/nested/report.qmd" }];
await write("project.json", JSON.stringify(manifest, null, 2));
await write("slides/talk/deck.json", JSON.stringify(inlineSlideFixture(), null, 2));
await write("slides/talk/assets/shared.svg", inlineSlideSvg());
const line = '![](../slides/talk/renders/results-step-0.svg){#slide-fixture .flux-slide deck="talk" slide="results" width=100%}';
await write("paper/main.qmd", `---\ntitle: Inline slide verification\n---\n\n# Results\n\nClick the slide to reveal each step.\n\n${line}\n`);
await write("paper/nested/detail.qmd", line.replace('#slide-fixture','#slide-include'));
await write("paper/nested/report.qmd", `---\ntitle: Evidence report\nformat:\n  html: default\n  docx: default\n  pdf:\n    pdf-engine: pdflatex\n    latex-auto-install: false\n---\n\n# Included evidence\n\n${line.replace('../slides','../../slides')}\n\n{{< include detail.qmd >}}\n`);
await write("paper/_quarto.yml", "project:\n  type: default\n");
await ensureDom();
const io = { readText: (p: string) => fs.readFile(p, "utf8"), readFile: (p: string) => fs.readFile(p), exists: (p: string) => fs.access(p).then(()=>true,()=>false), writeText: (p: string,t: string)=>fs.writeFile(p,t), mkdir: async (p:string)=>{await fs.mkdir(p,{recursive:true});} };
const repo = createSlideRepository(root, io);
const doc = await prepareSlideDocument(line, repo, { interactive: false, strict: true });
const html = `<!doctype html><html><head><meta charset="utf-8">${doc.style}<style>body{margin:60px;font:16px Georgia;color:#222;background:white}.flux-slide-embed{width:640px!important}h1{font-weight:normal}</style></head><body><h1>Inline slide verification</h1><p>Static export at step 0.</p>${doc.blocks[0].html}</body></html>`;
await write("exports/slide-static.html", html); repo.dispose();
console.log(root);
