import * as fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { harness } from './lib/harness.mjs';
import { scratchProject, installTestLauncher, rawMcp } from './lib/mcpFixture';
import { makeNote, makeReply, serializeEvent } from '../src/lib/project/annotations';
import { appendAnnotationEvent, readInbox, readPresence } from '../flux-core/annotations';
import { approve } from '../flux-core/liveClient';
import { backgroundTask } from '../flux-core/backgroundTask';
import { connect } from '../flux-core/connect';
import { detectAgentIdentity } from '../flux-core/agentIdentity';
const require = createRequire(import.meta.url);
const { createAgentRunner } = require('../electron/agentRunner.cjs');
const { startBridge } = require('../electron/bridgeServer.cjs');
const { taskCwd, backgroundConcurrency } = require('../electron/runnerDrivers/taskPolicy.cjs');
const h = harness('verify-background-run');
const temp = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'background-run-')));
const repo = path.resolve(import.meta.dirname, '..');
const runners: any[] = [], bridges: any[] = [];
const wait = async (check: () => boolean | Promise<boolean>, label: string) => {
  const deadline = Date.now() + 30000;
  while (!await check()) { if (Date.now() > deadline) throw Error('Timeout: ' + label); await new Promise(r => setTimeout(r, 20)); }
};
async function shim(file: string, args: string[]) {
  const quote = (s: string) => `'${s.replaceAll("'", "'\\''")}'`;
  const target = file + (process.platform === 'win32' ? '.cmd' : '');
  await fs.writeFile(target, process.platform === 'win32' ? `@echo off\r\n"${process.execPath}" ${args.map(s=>`"${s}"`).join(' ')} %*\r\n` : `#!/bin/sh\nexec ${quote(process.execPath)} ${args.map(quote).join(' ')} "$@"\n`, { mode: 0o755 });
  return target;
}
try {
  h.eq(taskCwd('/analysis/project','/analysis',[{name:'pyproject.toml'}]),'/analysis','Python analysis parent selected');
  h.eq(taskCwd('/work/project','/work',[{name:'README.md'}]),'/work/project','generic parent is not an analysis workspace');
  h.eq(taskCwd('/work/project','/work',[{name:'pyproject.toml'},{name:'project.json'}]),'/work/project','another Flux project is never the analysis workspace');
  h.eq(taskCwd('/work/project','/work',[{name:'analysis.ipynb'}]),'/work','top-level analysis notebooks identify a workspace');
  h.eq(taskCwd('/work/project','/work',[{name:'pyproject.toml',directory:true}]),'/work/project','marker must be a file');
  h.eq([backgroundConcurrency(undefined),backgroundConcurrency(99),backgroundConcurrency(0)],[2,3,1],'background default and limits');
  const workspace=path.join(temp,'analysis');await fs.mkdir(workspace);await fs.writeFile(path.join(workspace,'pyproject.toml'),'[project]\nname="scratch"');await fs.writeFile(path.join(workspace,'uv.lock'),'');
  const root=await scratchProject(path.join(workspace,'project'),'Background fixture');
  const launcher=await installTestLauncher(repo,path.join(temp,'bin'));
  const context=require('../electron/fluxPaths.cjs').configInfoSync().fluxContextPath;
  await fs.mkdir(context,{recursive:true});
  for(const name of ['FLUX.md','CONNECT.md'])await fs.copyFile(path.join(repo,'resources/flux-context',name),path.join(context,name));
  const ask=await connect({target:root,depth:'ask',identity:detectAgentIdentity(process.env)}), task=await connect({target:root,depth:'task',identity:detectAgentIdentity(process.env)});
  const taskText=await fs.readFile(task.taskPackPath!,'utf8');
  h.ok(taskText.includes('Claim it (claim_item)') && !taskText.includes('Be read-only') && task.taskPackPath!==ask.askPackPath,'same connect engine substitutes task rules into a separate cached pack');
  const binary: Record<string,string>={};
  for (const driver of ['claude','codex']) binary[driver]=await shim(path.join(temp,driver),['--import',pathToFileURL(require.resolve('tsx')).href,path.join(repo,'scripts/fixtures/runner/task-driver.mts'),driver]);
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aMncAAAAASUVORK5CYII=','base64');
  await fs.mkdir(path.join(root,'.meta/feedback'),{recursive:true});await fs.writeFile(path.join(root,'.meta/feedback/task.png'),png);
  const note=makeNote('resolve-task',{surface:'figure',snapshot:{image:'.meta/feedback/task.png',rect:{x:0,y:0,w:1,h:1},window:{w:1,h:1,dpr:1},marks:[]}},'human');await appendAnnotationEvent(root,note);
  const events:any[]=[], evidence=path.join(temp,'evidence.jsonl');
  const env={...process.env,SHELL:'/missing',FAKE_TASK_LAUNCHER:launcher,FAKE_TASK_ID:note.id,FAKE_TASK_EVIDENCE:evidence};
  const runner=createAgentRunner({userDataDir:path.join(temp,'config'),launcher,binaries:binary,env,approvalTimeoutMs:80,preferences:()=>({fluxchat:{backgroundConcurrency:2}}),emit:(owner:any,event:any)=>events.push({...event,owner})});runners.push(runner);
  const run=await runner.start(1,{mode:'task',driver:'claude',root,itemId:note.id});
  let duplicate=false;try{await runner.start(1,{mode:'task',driver:'codex',root,itemId:note.id})}catch{duplicate=true}h.ok(duplicate,'one background session per item');
  await wait(()=>events.some(e=>e.runId===run.runId&&e.state==='idle'),'real MCP resolve');
  const item=(await readInbox(root)).items.find(i=>i.id===note.id)!;
  const proof=JSON.parse((await fs.readFile(evidence,'utf8')).trim().split('\n')[0]);
  h.eq(item.status,'resolved','fake driver uses real MCP claim/resolve and the shared fold resolves the item');
  h.ok(proof.state.background && proof.state.display.startsWith('bg · claude · ') && item.thread.some(m=>m.author===proof.state.name),'presence and signed reply use one background session name');
  h.eq(proof.cwd,workspace,'task driver actually spawns in the analysis workspace');
  h.ok(proof.text.includes('Attached view (read these PNG files)'),'item snapshot is delivered as a readable image attachment');
  h.ok(proof.text.includes(note.id)&&proof.text.includes('targets')&&proof.approve,'task receives the shared packet and hosted-only approval tool');
  h.ok(events.some(e=>e.type==='usage'&&e.costUsd===0.01),'task usage and cost forwarded');
  await wait(async()=>!(await readPresence(root)).some(s=>s.id===run.runId),'completed task presence removed');
  runner.cancel(1,run);

  const fallback=makeNote('fallback-task',{surface:'figure'},'human');await appendAnnotationEvent(root,fallback);
  const fEvents:any[]=[];
  const fRunner=createAgentRunner({userDataDir:path.join(temp,'fallback-config'),launcher,binaries:binary,env:{...env,FAKE_TASK_ID:fallback.id},emit:(_:any,e:any)=>fEvents.push(e)});runners.push(fRunner);
  const f=await fRunner.start(2,{mode:'task',driver:'codex',root,itemId:fallback.id});
  await wait(()=>fEvents.some(e=>e.state==='idle'),'fallback saved');
  let folded=(await readInbox(root)).items.find(i=>i.id===fallback.id)!;
  h.eq(folded.thread.at(-1)?.text,'Final background answer','unposted final assistant message becomes a real agent reply');
  h.ok(folded.thread.at(-1)?.kind==='agent'&&folded.thread.at(-1)?.author!== 'Codex','fallback signs with the presence name');
  await appendAnnotationEvent(root,makeReply(fallback.id,{kind:'human',name:'You'},'follow-up','human'));
  const before=fEvents.filter(e=>e.state==='idle').length;
  await fRunner.send(2,{runId:f.runId,text:'follow-up'});
  await wait(()=>fEvents.filter(e=>e.state==='idle').length>before,'resumed task');
  folded=(await readInbox(root)).items.find(i=>i.id===fallback.id)!;
  h.eq(folded.thread.filter(m=>m.text==='Final background answer').length,2,'each resumed turn has its own fallback receipt');
  const calls=(await fs.readFile(evidence,'utf8')).trim().split('\n').map(s=>JSON.parse(s));
  h.ok(calls.at(-1).args.includes('resume')&&calls.at(-1).text.includes('follow-up'),'follow-up resumes vendor thread with latest full item packet');
  fRunner.cancel(2,f);

  const held=makeNote('hold-task',{surface:'figure'},'human');await appendAnnotationEvent(root,held);
  const heldEvents:any[]=[];
  const holder=createAgentRunner({userDataDir:path.join(temp,'held-config'),launcher,binaries:binary,env:{...env,FAKE_TASK_ID:held.id},approvalTimeoutMs:500,emit:(_:any,e:any)=>heldEvents.push(e)});runners.push(holder);
  const heldRun=await holder.start(3,{mode:'task',driver:'claude',root,itemId:held.id});
  await wait(async()=>!!(await readInbox(root)).items.find(i=>i.id===held.id)?.claimedBy,'held task claim');
  const config=JSON.parse(await fs.readFile(path.join(temp,'held-config/runs',heldRun.runId,'mcp.json'),'utf8'));
  const token=config.mcpServers.flux.env.FLUX_RUNNER_TOKEN;
  const bridge=startBridge({root,getContext:()=>({}),dispatch:async()=>{},approve:(r:any)=>holder.approve(3,root,r)});bridges.push(bridge);
  await wait(()=>bridge.isRunning(),'fake app bridge');
  const request={tool_name:'Bash',input:{command:'git status --short',description:'Actual command'}};
  const approvalClient=await rawMcp(launcher,root,[root],{...process.env,FLUX_PROJECT:root,FLUX_RUNNER_TOKEN:token});
  await approvalClient.initialize();
  // A connected session with a pending "since you last looked" delta must still answer the
  // permission protocol with exactly one JSON block (approve is in connect's QUIET set).
  await approvalClient.call('connect',{});
  await fs.appendFile(path.join(root,'paper/notes.qmd'),'\nEdited by someone else while the run waits.\n');
  let allowBlocks=0;
  const allow=approvalClient.call('approve',request).then(r=>{allowBlocks=r.content.length;return JSON.parse(r.content[0].text);});
  await wait(()=>heldEvents.some(e=>e.type==='permission'),'permission shown');
  let permission=heldEvents.filter(e=>e.type==='permission').at(-1);
  h.eq(JSON.parse(permission.detail),request.input,'permission contains actual tool input');
  let wrongOwner=false;try{holder.respond(9,{runId:heldRun.runId,permissionId:permission.permissionId,optionId:'allow'})}catch{wrongOwner=true}h.ok(wrongOwner,'another window cannot grant approval');
  holder.respond(3,{runId:heldRun.runId,permissionId:permission.permissionId,optionId:'allow'});
  h.eq(await allow,{behavior:'allow',updatedInput:request.input},'real MCP approve tool and bridge return Claude allow-once protocol');
  h.eq(allowBlocks,1,'approve answers with one JSON block even with a pending connect delta');
  await approvalClient.close();
  const deny=approve(root,token,request);const count=heldEvents.filter(e=>e.type==='permission').length;
  await wait(()=>heldEvents.filter(e=>e.type==='permission').length>count,'second permission');
  permission=heldEvents.filter(e=>e.type==='permission').at(-1);holder.respond(3,{runId:heldRun.runId,permissionId:permission.permissionId,optionId:'deny'});
  h.eq((await deny).behavior,'deny','explicit denial round trip');
  h.eq((await approve(root,'bad-token',request)).behavior,'deny','unknown run token denied');
  h.eq((await approve(root,token,request)).behavior,'deny','permission timeout denies');
  const cancelled=approve(root,token,request);const n=heldEvents.filter(e=>e.type==='permission').length;
  await wait(()=>heldEvents.filter(e=>e.type==='permission').length>n,'cancelled permission');
  holder.cancelOwner(3);
  h.eq((await cancelled).behavior,'deny','window close/cancel denies pending permission');
  await wait(async()=>!(await readPresence(root)).some(s=>s.id===heldRun.runId),'cancel cleans MCP presence');
  h.ok(heldEvents.some(e=>e.state==='cancelled'),'cancel emits status and removes presence');
  bridge.stop();
  h.eq((await approve(root,token,request)).behavior,'deny','no app reachable denies');
  const queuedEvents:any[]=[];
  let concurrency=2;
  const queuedRunner=createAgentRunner({userDataDir:path.join(temp,'queued-config'),launcher,binaries:binary,env,preferences:()=>({fluxchat:{backgroundConcurrency:concurrency}}),emit:(_:any,e:any)=>queuedEvents.push(e)});runners.push(queuedRunner);
  const queued:any[]=[];
  for(let i=0;i<3;i++) {const n=makeNote('hold-task '+i,{surface:'figure'},'human');await appendAnnotationEvent(root,n);queued.push(await queuedRunner.start(4,{mode:'task',driver:'codex',root,itemId:n.id}));}
  await wait(async()=>{const p=await readPresence(root);return p.filter(s=>queued.some(r=>r.runId===s.id)).length===2},'default two concurrent tasks');
  h.ok(!queuedEvents.some(e=>e.runId===queued[2].runId&&e.type==='session'),'third background task stays queued at default limit two');
  await queuedRunner.cancel(4,queued[0]);
  await wait(()=>queuedEvents.some(e=>e.runId===queued[2].runId&&e.type==='session'),'queued task takes freed slot');
  h.ok(!(await readInbox(root)).state.stoppedSessions.has(queued[1].runId),'stopping one task does not revoke another');
  h.ok((await readInbox(root)).state.stoppedSessions.has(queued[0].runId),'Stop durably revokes and releases the old background session');
  await Promise.all(queued.slice(1).map(r=>queuedRunner.cancel(4,r)));
  concurrency=1;
  const one:any[]=[];
  for(let i=0;i<2;i++){const n=makeNote('hold-task limited '+i,{surface:'figure'},'human');await appendAnnotationEvent(root,n);one.push(await queuedRunner.start(4,{mode:'task',driver:'codex',root,itemId:n.id}));}
  await wait(()=>queuedEvents.some(e=>e.runId===one[0].runId&&e.type==='session'),'single concurrency run');
  h.ok(!queuedEvents.some(e=>e.runId===one[1].runId&&e.type==='session'),'configured concurrency one is enforced');
  await Promise.all(one.map(r=>queuedRunner.cancel(4,r)));
  const normal=await rawMcp(launcher,root,[root],{...process.env,FLUX_RUNNER_TOKEN:''});
  try{await normal.initialize();h.ok(!(await normal.request('tools/list')).result.tools.some((t:any)=>t.name==='approve'),'ordinary MCP sessions never list approve')}finally{await normal.close()}
  const turnRequest={root,id:fallback.id,runId:'test-receipt',stateFile:path.join(temp,'receipt.json'),driver:'codex' as const};
  const humanReceipt=(await backgroundTask({...turnRequest,action:'prepare'})).receipt!;
  await appendAnnotationEvent(root,makeReply(fallback.id,{kind:'human',name:'You'},'While you are working','human'));
  const afterHuman=await backgroundTask({...turnRequest,action:'finish',receipt:humanReceipt,text:'Answer despite concurrent human reply'});
  h.ok('replied' in afterHuman&&afterHuman.replied,'a concurrent human reply does not suppress the agent final-message fallback');
  const receipt=(await backgroundTask({...turnRequest,action:'prepare'})).receipt!;
  await appendAnnotationEvent(root,makeReply(fallback.id,{kind:'agent',name:'other'},'already answered','other'));
  const skipped=await backgroundTask({...turnRequest,action:'finish',receipt,text:'duplicate'});
  h.ok('replied' in skipped&&!skipped.replied,'an existing reply suppresses final-message fallback');
} catch(e) {h.fail(e instanceof Error?e.stack:String(e));}
finally {for(const bridge of bridges)bridge.stop();await Promise.all(runners.map(r=>r.dispose()));}
await h.done();
