#!/usr/bin/env -S npx tsx
// Colour-system plan F4 (Flux half) — the axis view re-ticks and moves filled marks:
//   • the tick generator per scheme: nice 1·2·5 linear steps with ScalarFormatter labels (uniform
//     decimals, unicode minus), decades (+ 3×10ᵏ over short spans) and mantissa minors on a log
//     axis, 10ᵏ labels for a log formatter;
//   • filled marks re-project vertex by vertex through the view: heatmap cells and hexagons land
//     on the projection of their recorded data box (data-x0 / x1 / y0 / y1), bars keep their x and
//     follow the y view; restore puts the generated bytes back; a tween frame sits between;
//   • `plotViewIssues` no longer calls filled marks unchanged (only images / rasters are).
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { DOMParser, parseHTML } from 'linkedom';
import { harness } from './lib/harness.mjs';
import type { FluxPlotManifest } from '../src/lib/plot/types';
import type { PlotView } from '../src/lib/types';
import { viewFits, projectWith, plotViewIssues, filledLeaves } from '../src/lib/plot/project';
import { applyPlotView, restoreProjection } from '../src/lib/plot/projectDom';
import { preparePlot } from '../src/lib/plot/parse';
import { linearTicks, logTicks, logMinorTicks, scalarLabels, formatTick, ticksFor, niceStep } from '../src/lib/plot/ticks';

const { document } = parseHTML('<html><body></body></html>');
Object.assign(globalThis, { document, DOMParser });
const h = harness('verify-plot-view-filled');
const repo = resolve(import.meta.dirname, '..');
const load = (folder: string, name: string) => ({
  manifest: JSON.parse(readFileSync(join(repo, 'scripts/fixtures', folder, `${name}.fluxplot.json`), 'utf8')) as FluxPlotManifest,
  svg: readFileSync(join(repo, 'scripts/fixtures', folder, `${name}.svg`), 'utf8'),
});
const nums = (d: string | null | undefined) => (d ?? '').match(/[-+]?(?:\d*\.)?\d+(?:e[-+]?\d+)?/gi)!.map(Number);
const box = (root: Element, id: string) => {
  const n = root.querySelector(`[id="${id}"]`)!; const p = n.tagName.toLowerCase() === 'path' ? n : n.querySelector('path')!;
  const v = nums(p.getAttribute('d')); const xs = v.filter((_, i) => i % 2 === 0), ys = v.filter((_, i) => i % 2 === 1);
  return { x0: Math.min(...xs), x1: Math.max(...xs), y0: Math.min(...ys), y1: Math.max(...ys), n: xs.length, el: p };
};
const near = (a: number, b: number, msg: string, eps = 2e-3) => h.ok(Number.isFinite(a) && Math.abs(a - b) < eps, `${msg}: ${a} ≈ ${b}`);
try {
  h.section('tick generation per scheme');
  h.eq(niceStep(2), 0.5, 'a span of 2 steps by 0.5');
  h.eq(linearTicks(2, 4), [2, 2.5, 3, 3.5, 4], 'linear ticks of [2, 4]');
  h.eq(linearTicks(-1, 1), [-1, -0.5, 0, 0.5, 1], 'linear ticks of [-1, 1]');
  h.eq(scalarLabels([-1, -0.5, 0, 0.5, 1]), ['−1.0', '−0.5', '0.0', '0.5', '1.0'], 'ScalarFormatter labels: uniform decimals, unicode minus');
  h.eq(scalarLabels([10, 20, 30, 40]), ['10', '20', '30', '40'], 'integers need no decimals');
  h.eq(scalarLabels([0, 0.25, 0.5, 0.75]), ['0.00', '0.25', '0.50', '0.75'], 'quarters need two');
  h.eq(logTicks(1, 1000), [1, 3, 10, 30, 100, 300, 1000], 'log ticks over three decades add 3×10ᵏ');
  h.eq(logTicks(1, 1e5), [1, 10, 100, 1000, 1e4, 1e5], 'over five decades, decades only');
  h.eq(logMinorTicks(1, 100, [1, 10, 100]).length, 16, 'mantissa minors 2…9 in every decade');
  h.eq(formatTick(100, 'log'), { text: '10^2', base: '10', exponent: '2' }, 'a log formatter labels a decade as 10ᵏ');
  h.eq(ticksFor('log', 1, 1000), logTicks(1, 1000), 'ticksFor dispatches by kind');
  h.eq(ticksFor('linear', 0, 1), [0, 0.2, 0.4, 0.6, 0.8, 1], 'and linear');

  h.section('heatmap cells re-project onto their data boxes');
  const heat = load('colorscale', 'heatmap');
  const cells = heat.manifest.series.find(s => s.field?.kind === 'heatmap')!;
  const leaves = filledLeaves(cells);
  h.ok(leaves.length === 48 && leaves.every(l => /\.cell\.\d+\.\d+$/.test(l)), `filledLeaves names the ${leaves.length} cells (not the layer)`);
  const { root: hroot } = preparePlot(heat.svg, heat.manifest);
  const hRaw = viewFits(heat.manifest)!, hView: PlotView = { y: { domain: [1, 4] }, x: { domain: [0, 12] } }, hFits = viewFits(heat.manifest, hView)!;
  const cell = leaves[9], before = box(hroot!, cell);
  const dataBox = ['data-x0', 'data-x1', 'data-y0', 'data-y1'].map(a => Number(before.el.getAttribute(a)));
  h.ok(dataBox.every(Number.isFinite), `a cell carries its data box (${dataBox.join(', ')})`);
  near(before.x0, projectWith(hRaw.x, dataBox[0]), 'as generated, the cell\'s left edge is the raw projection of data-x0');
  applyPlotView(hroot!, heat.manifest, hView, '');
  const after = box(hroot!, cell);
  near(after.x0, projectWith(hFits.x, dataBox[0]), 'viewed: left edge = view projection of data-x0');
  near(after.x1, projectWith(hFits.x, dataBox[1]), 'right edge = data-x1');
  near(Math.min(after.y0, after.y1), Math.min(projectWith(hFits.y, dataBox[2]), projectWith(hFits.y, dataBox[3])), 'top = the higher of data-y0 / y1 projected');
  near(Math.max(after.y0, after.y1), Math.max(projectWith(hFits.y, dataBox[2]), projectWith(hFits.y, dataBox[3])), 'bottom likewise');
  h.eq(after.n, before.n, 'the polygon keeps its vertex count');
  h.ok(!plotViewIssues(heat.manifest, hView).some(i => i.includes('unchanged')), 'cells are not called unchanged');
  restoreProjection(hroot!);
  const restored = box(hroot!, cell);
  near(restored.x0, before.x0, 'restore: left edge back'); near(restored.y1, before.y1, 'restore: bottom back');
  // a tween frame sits between the generated and the viewed geometry
  applyPlotView(hroot!, heat.manifest, hView, '', { t: 0.5 });
  const mid = box(hroot!, cell);
  h.ok(mid.x0 > Math.min(before.x0, after.x0) - 1e-6 && mid.x0 < Math.max(before.x0, after.x0) + 1e-6 && Math.abs(mid.x0 - before.x0) > 1e-6, 'a half-way frame lies between the two');
  restoreProjection(hroot!);

  h.section('hexagons and bars from real generator output');
  const feat = load('fluxplot03', 'features');
  const { root } = preparePlot(feat.svg, feat.manifest);
  const hexSeries = feat.manifest.series.find(s => s.id === 'panel.hex.mean')!;
  const hexLeaf = filledLeaves(hexSeries).find(l => root!.querySelector(`[id="${l}"]`))!;
  const hexEl = box(root!, hexLeaf).el;
  const hexBox = ['data-x0', 'data-x1', 'data-y0', 'data-y1'].map(a => Number(hexEl.getAttribute(a)));
  const hexRaw = viewFits(feat.manifest, undefined, 'panel.hex')!;
  const hexView: PlotView = { x: { domain: [hexBox[0] - 1, hexBox[1] + 3] } };
  const hexFits = viewFits(feat.manifest, hexView, 'panel.hex')!;
  applyPlotView(root!, feat.manifest, hexView, '');
  const hb = box(root!, hexLeaf);
  near(hb.x0, projectWith(hexFits.x, hexBox[0]), 'a hexagon\'s left vertex lands on the view projection of data-x0');
  near(hb.x1, projectWith(hexFits.x, hexBox[1]), 'its right vertex on data-x1');
  near(hb.y0, Math.min(projectWith(hexRaw.y, hexBox[2]), projectWith(hexRaw.y, hexBox[3])), 'an x view leaves its y extent');
  h.eq(hb.n, 6, 'six vertices, still a hexagon');
  // bars keep x, follow y
  const barSeries = feat.manifest.series.find(s => s.id === 'panel.cells.means')!;
  const barIds = barSeries.svg.bars!;
  const barPayload = barSeries.bar as { center: number[]; width: number[]; baseline: number[]; length: number[] };
  restoreProjection(root!); // a view applies to every panel: measure the generated bars unviewed
  const barBefore = box(root!, barIds[1]);
  const cellsRaw = viewFits(feat.manifest, undefined, 'panel.cells')!;
  near(barBefore.x0, projectWith(cellsRaw.x, barPayload.center[1] - barPayload.width[1] / 2), 'a bar\'s generated left edge is center − width/2 projected');
  const barView: PlotView = { y: { domain: [0, 5] } };
  const cellsFits = viewFits(feat.manifest, barView, 'panel.cells')!;
  applyPlotView(root!, feat.manifest, barView, '');
  const barAfter = box(root!, barIds[1]);
  near(barAfter.x0, barBefore.x0, 'a y view keeps the bar\'s x');
  near(Math.min(barAfter.y0, barAfter.y1), projectWith(cellsFits.y, barPayload.baseline[1] + barPayload.length[1]), 'the bar\'s top is the projected data height');
  near(Math.max(barAfter.y0, barAfter.y1), projectWith(cellsFits.y, barPayload.baseline[1]), 'its base the projected baseline');
  h.ok(!plotViewIssues(feat.manifest, barView).some(i => i.includes('unchanged') && !i.includes('image')) || plotViewIssues(feat.manifest, barView).some(i => i.includes('images')), 'the limitation, if any, names images / rasters only');
  h.ok(!filledLeaves(feat.manifest.series.find(s => s.id === 'panel.image.cells')!).length, 'an image series has no filled leaves to re-project');
  restoreProjection(root!);
} catch (e) { h.fail(e instanceof Error ? e.stack ?? e.message : String(e)); }
await h.done();
