import assert from "node:assert/strict";
import { harness } from "./lib/harness.mjs";
import { createDeck, addSlide, addBeat, setTransform, duplicateTrack, moveTrackToBeat } from "../src/lib/slide/ops";
import { deckToProject, projectIntoDeck } from "../src/lib/slide/deckProject";
import { applyState, diffState, numericTextTween } from "../src/lib/slide/tween";
import { planElementMorph, sampleElementMorph } from "../src/lib/slide/outline";
import { portablePayload } from "../src/lib/slide/payload";
import { compileSlide } from "../src/lib/slide/compile";
import { safeMathRender } from "../src/shell/modes/paper/science/safeMath";
import katex from "katex";
import { normalizeEmbedAlts, transformQmdForExport, readQmdTree } from "../src/lib/exportQmd";
import { markCitations } from "../src/lib/references/zoteroFields";
import { scanRefNumbers } from "../src/shell/modes/paper/science/refNumbers";
import { familyById } from "../src/lib/figfamily";
import { publishExportRecovery, planExportRecovery, recoverExportSources, exportJournalPath } from "../src/lib/project/exportRecovery";
const h = harness("verify-v020-paper-slide");
const deck = createDeck({ id: "fortification" });
const a = deck.slides[0], b = addSlide(deck);
const rect = { id: "title", type: "rect" as const, x: 10, y: 20, width: 100, height: 80, fill: "#ff0000", stroke: "none", strokeWidth: 0 };
a.elements = [rect]; b.elements = [{ ...rect, x: 300, fill: "#0000ff" }];
const projection = deckToProject(deck, deck.assets); projection.figures[0].elements[0].x = 900;
const composed = projectIntoDeck(projection, deck, { baselines: new Map([[a.id, new Map([[rect.id, rect]])]]) });
h.eq(composed.slides[0].elements[0].x, 10, "checkout restores the owning slide's canonical source");
h.eq(composed.slides[1].elements[0].x, 300, "same element ID on sibling slide remains independent");
const beat = addBeat(deck, a.id)!;
const track = setTransform(deck, a.id, beat.id, rect.id, { state: { x: 200 } })!;
const before = JSON.stringify(deck);
h.eq(duplicateTrack(deck, a.id, track.id!), null, "duplicate Change is refused without ambiguity");
h.eq(moveTrackToBeat(deck, a.id, track.id!, a.beats[0].id), false, "playback move into Design is refused");
h.eq(JSON.stringify(deck), before, "refused animation operations preserve exact model bytes");
const copyStep=addBeat(deck,a.id)!;
const copiedChange=duplicateTrack(deck,a.id,track.id!,copyStep.id);
h.ok(!!copiedChange&&copiedChange!==track.id&&copyStep.tracks.length===1&&beat.tracks.length===1,"Change copies directly to another step with a fresh identity and untouched source");
const copiedBytes=JSON.stringify(deck);
h.eq(duplicateTrack(deck,a.id,track.id!,copyStep.id),null,"copy refuses a conflicting Change already present in its destination");
h.eq(JSON.stringify(deck),copiedBytes,"conflicting destination copy preserves exact model bytes");
const end = { ...rect, type: "ellipse" as const };
const rebuilt = applyState({ ...rect, opacity: .4, flipX: true }, diffState({ ...rect, opacity: .4, flipX: true }, end)!);
h.ok(rebuilt.opacity === undefined && rebuilt.flipX === undefined, "Become deletes retained optional base properties absent in destination");
h.eq(numericTextTween("Total 5.", "Total 9.")?.(.5), "Total 7.", "numeric tween preserves sentence punctuation");
const gradient = { map: "fixture", axis: "x" as const, stops: ["#ff0000", "#0000ff"] };
const morph = planElementMorph({ ...rect, fill: "none", fillMap: gradient }, { ...end, fill: "none", fillMap: gradient })!;
h.eq(sampleElementMorph(morph, .5).fillMap, gradient, "outline sampling preserves gradient-only fill");
const birth = { id: "birth", target: "ghost", ghostFrom: rect.id, preset: "transform" as const, duration: 400, disabled: true, to: { state: { x: 99 } } };
a.elements.push({ ...rect, id: "ghost" }); beat.tracks.push(birth); a.notes = "Presenter note";
(a.elements[0] as any).source = { svgPath: "/private/secret.svg", recipePath: "/private/secret.py" };
const portable = portablePayload({ deck, plots: {}, assets: {} });
h.ok(!JSON.stringify(portable).includes("/private"), "portable payload strips private source and recipe paths");
h.eq(portable.deck.slides[0].notes, "Presenter note", "presenter payload retains intended speaker notes");
h.ok(!portablePayload({ deck, plots: {}, assets: {} }, { notes: false }).deck.slides[0].notes, "Paper projection omits speaker notes");
h.ok(compileSlide(portable.deck.slides[0], deck.stage).resolvedSlide.beats[1].tracks.some(t => t.disabled && t.ghostFrom), "disabled ghost ownership survives portable projection");
h.ok(safeMathRender(katex, "\\begin{subarray}\\cr", true).includes("katex-error"), "internal KaTeX exception becomes visible source fallback");
h.ok(safeMathRender(katex, "x".repeat(17000), true).includes("source characters"), "oversized equation reports bound without truncating source");
const examples = "````qmd\n![example](fig.svg){#fig-test}\n{{< include private.qmd >}}\n```\n````\n\n`@fig-test`\n";
h.eq(normalizeEmbedAlts(examples, () => true).text, examples, "fenced figure examples preserve canonical alt bytes");
h.eq(transformQmdForExport(examples, { captions: new Map([["fig-test", "caption"]]), figures: new Map([["fig-test", { family: familyById("main"), number: 1 }]]) }), examples, "export leaves long fences and inline figure-reference examples unchanged");
const reads: string[] = [];
await readQmdTree("/project/paper/a.qmd", { readText: async p => { reads.push(p); return examples; } });
h.eq(reads.length, 1, "fenced include examples are never traversed");
h.ok(markCitations("Intro\n\n---\n[@real2020]\n---\n").includes("ZC"), "body thematic rules do not masquerade as YAML and hide real citations");
const tables = "|a|b|\n|-|-|\n|1|2|\n: First {#tbl-x}\n\n|a|b|\n|-|-|\n|1|2|\n: Duplicate {#tbl-x}\n\n|a|b|\n|-|\n|1|2|\n: Bad {#tbl-bad}\n";
h.eq([...scanRefNumbers(tables).tbl], [["tbl-x", 1]], "only valid tables number and duplicate labels preserve first ordinal");
const files = new Map([["/project/paper/a.qmd", "original A"], ["/project/paper/b.qmd", "original B"]]);
const io = { readText: async (p: string) => files.get(p) ?? null, writeText: async (p: string, s: string) => { files.set(p, s); }, removeFile: async (p: string) => { files.delete(p); } };
const journal = planExportRecovery("/project", "owned", [["/project/paper/a.qmd", "original A", "temporary A"], ["/project/paper/b.qmd", "original B", "temporary B"]]);
await publishExportRecovery(io, "/project", journal); files.set("/project/paper/a.qmd", "temporary A");
await recoverExportSources(io, "/project"); await recoverExportSources(io, "/project");
h.eq(files.get("/project/paper/a.qmd"), "original A", "interrupted partial rewrite restores original source idempotently");
h.ok(!files.has(exportJournalPath("/project")), "fully recovered journal is removed");
await publishExportRecovery(io, "/project", journal); files.set("/project/paper/a.qmd", "newer user edit");
await assert.rejects(recoverExportSources(io, "/project"), /newer content retained/);
h.eq(files.get("/project/paper/a.qmd"), "newer user edit", "external edits win during restoration");
h.ok(files.get(exportJournalPath("/project"))!.includes("original A"), "conflicting recovery retains durable original bytes");
await h.done();
