import assert from "node:assert/strict";
import { createFigureReferenceResolver, figureReferenceConflicts, parsePanelSpec } from "../src/lib/figureReferences";
import { transformQmdForExport } from "../src/lib/exportQmd";
import { BUILTIN_FAMILIES } from "../src/lib/figfamily";
import { createFigure, setFigureIdentity, deleteCanvas, duplicateFigure, deleteFigure } from "../src/lib/ops";
import { ensureFigureReferenceKeys, mintFigureReferenceKey } from "../src/lib/project/figureIdentity";
import { presentationViewport, basePresentationViewport } from "../src/lib/editorPresentation";
import type { Project } from "../src/lib/types";
let checks = 0;
const eq = (a: unknown, b: unknown, label: string) => { assert.deepEqual(a, b, label); checks++; };
const refs = [{ label: "fig-long-title", panels: ["a", "b", "c", "a1"] }, { label: "fig-long-title-a", panels: ["b"] }, { label: "fig-empty", panels: [] }];
const resolve = createFigureReferenceResolver(refs);
eq(resolve("fig-long-title-a")?.ref, refs[1], "exact key wins over panel suffix");
eq(resolve("fig-long-title-a-b")?.ref, refs[1], "longest exact prefix owns panels");
eq(resolve("fig-long-title-a-c"), null, "invalid panel cannot fall through to another figure");
eq(resolve("fig-long-title-b,c")?.panelSpec, "b,c", "comma panel lists resolve");
eq(resolve("fig-long-title-b-c")?.panelSpec, "b-c", "panel ranges resolve");
eq(resolve("fig-long-title-a1")?.panelSpec, "a1", "suffixed panel labels resolve");
eq(resolve("fig-empty-a"), null, "known figure without panels cannot invent panel a");
eq(parsePanelSpec("q", ["a"]), null, "unknown panel stays unresolved");
eq(figureReferenceConflicts(refs).map((c) => c.kind), ["panel-shadow"], "key versus panel collision is diagnosed");
eq(figureReferenceConflicts([refs[0], refs[0]]).map((c) => c.kind), ["duplicate"], "duplicate identity is diagnosed");
const p: Project = { version: 2, name: "Identity", canvases: [{ id: "one", name: "One" }, { id: "two", name: "Two" }], figures: [], assets: [], palette: [] };
const a = createFigure(p, { id: "growth", canvasId: "one", nickname: "Growth curve" });
const b = createFigure(p, { id: "dose", canvasId: "two", nickname: "Dose response" });
const oldKey = a.referenceKey;
setFigureIdentity(p, a.id, { nickname: "New title", number: 2 });
eq(a.referenceKey, oldKey, "title and number edits preserve identity");
const copy = duplicateFigure(p, a.id);
assert(copy); checks++;
const copied = p.figures.find((f) => f.id === copy)!;
eq(!!copied.referenceKey && copied.referenceKey !== oldKey, true, "a duplicate has a real, different permanent reference identity");
const ledger = p.figures.map((f) => [f.id, f.referenceKey]);
ensureFigureReferenceKeys(p);
eq(p.figures.map((f) => [f.id, f.referenceKey]), ledger, "reopen migration is idempotent");
const context = { captions: new Map<string, string>(), figures: new Map(p.figures.map((f) => [f.referenceKey!, { family: BUILTIN_FAMILIES[0], number: f.number!, panels: [] }])) };
const first = `See @${a.referenceKey}, then @${b.referenceKey}.`;
const second = `See @${b.referenceKey}, then @${a.referenceKey}.`;
const before = JSON.stringify(p);
const expectedA = `Fig. ${a.number}`, expectedB = `Fig. ${b.number}`;
eq(transformQmdForExport(first, context), `See ${expectedA}, then ${expectedB}.`, "export uses Figure numbers");
eq(transformQmdForExport(second, context), `See ${expectedB}, then ${expectedA}.`, "changing Paper order preserves Figure numbers");
eq(JSON.stringify(p), before, "manuscript transforms never mutate Figure");
deleteCanvas(p, "one");
eq(p.figures.map((f) => [f.id, f.number, f.referenceKey]), [[b.id, 1, b.referenceKey]], "canvas deletion compacts immediately without rekeying survivors");
const base = { panX: 81, panY: -23, zoom: 1.25 };
const display = { camera: { x: 120, y: 90, zoom: 2 }, stage: { width: 640, height: 360 } };
eq(basePresentationViewport(presentationViewport(base, display), display), base, "camera viewport mapping inverts exactly");
eq(presentationViewport(base), base, "plain Figure viewport remains unchanged");
const regenerated: Project = { version: 2, name: "Delete/recreate", canvases: [{ id: "c", name: "Canvas" }], figures: [], assets: [], palette: [] };
const original = createFigure(regenerated, { canvasId: "c" });
original.referenceKey = "fig-figure-1"; // exact legacy label after migration
const deletedKey = original.referenceKey;
deleteFigure(regenerated, original.id); // deleting last frame creates a new blank
eq(regenerated.figures.length, 1, "last-frame deletion retains its replacement canvas frame");
eq(regenerated.figures[0].referenceKey === deletedKey, false, "replacement blank cannot retarget deleted legacy references");
eq(createFigureReferenceResolver(regenerated.figures.map((f) => ({ label: f.referenceKey! })))(deletedKey), null, "old manuscript key remains unresolved after deleting/recreating a figure");
const created = createFigure(regenerated, { canvasId: "c", nickname: "Same title" });
const createdKey = created.referenceKey;
deleteFigure(regenerated, created.id, { allowEmpty: true });
const recreated = createFigure(regenerated, { canvasId: "c", nickname: "Same title" });
eq(recreated.referenceKey === createdKey, false, "reusing a human title never reuses its deleted identity");
eq(mintFigureReferenceKey("growth", [{ id: "another", referenceKey: "fig-growth" }]), "fig-growth-2", "new explicit slug key avoids a live collision");
const legacy = structuredClone(regenerated);
legacy.figures[0].referenceKey = undefined;
ensureFigureReferenceKeys(legacy, { figures: [{ id: legacy.figures[0].id, label: deletedKey }] });
eq(legacy.figures[0].referenceKey, deletedKey, "legacy index backfill preserves the original key exactly");
console.log(`FIGURE REFERENCE IDENTITY: PASS (${checks} assertions)`);
