import { createRequire } from 'node:module';
import { harness } from './lib/harness.mjs';
const { analyze } = createRequire(import.meta.url)('./perf/frame-oracle.cjs');
const h = harness('verify-frame-oracle');
const frame = (i: number, props = {}) => ({ t: i * 16, dark: .02, bw: 400 + i * 2, bh: 300 + i * 2, x: 50 + i, y: 40, ...props });
const clean = Array.from({ length: 7 }, (_, i) => frame(i));
h.eq(analyze(clean).blanks, [], 'smooth motion has no dropouts');
h.eq(analyze(clean).glitches, [], 'smooth motion has no geometry spikes');
const blank = (i: number) => frame(i, { dark: 0, bw: 0, bh: 0, x: null, y: null });
h.eq(analyze([clean[0], blank(1), clean[2]]).blanks.map((f: { i: number }) => f.i), [1], 'a planted fully blank frame is detected, not filtered out');
h.eq(analyze([clean[0], blank(1), blank(2), clean[3]]).blanks.length, 2, 'consecutive blank frames remain detectable');
h.eq(analyze([blank(0), clean[1], blank(2)]).blanks.length, 2, 'capture-boundary blank frames remain detectable');
h.eq(analyze([clean[0], frame(1, { dark: .002 }), clean[2]]).blanks.length, 1, 'partial content collapse remains detectable');
h.ok(analyze([clean[0], frame(1, { bw: 500 }), clean[2]]).glitches.length > 0, 'planted size spike is detected');
h.ok(analyze([clean[0], frame(1, { x: 80 }), clean[2]]).glitches.length > 0, 'planted position spike is detected');
h.eq(analyze([clean[0], blank(1), clean[2]]).gapP50, 16, 'capture cadence uses every sample, including dropouts');
h.eq(analyze([blank(0), blank(1)]).blanks.length, 2, 'an entirely blank capture is a failure too');
h.eq(analyze([frame(0),frame(1,{bw:416}),frame(10,{bw:560})]).glitches, [], 'nonuniform capture intervals do not invent a size spike');
h.eq(analyze([]).frames, 0, 'empty capture has no invented evidence');
await h.done();
