#!/usr/bin/env -S npx tsx
// Colour-system plan A7.3 / A7.4 / A7.7 — live recolouring in the DOM, against fluxplot itself:
//   • applying a colour-scale view to the generated SVG paints EVERY data-value element hex-for-hex
//     as fluxplot paints it when the same controls regenerate the plot (the *-edited twins written
//     by scripts/fixtures/colorscale/make_fixtures.py), for a log hexmatrix (fill+stroke) and a
//     cells=True heatmap with a missing cell (fill, bad colour), with a named colormap and a table;
//   • the colour key follows: the solids gradient's stops match the twin's, ticks re-place through
//     the key's anchors onto the twin's positions;
//   • an absent or identity view restores the generated bytes exactly; a second apply of the same
//     view rewrites nothing; issues (log minimum ≤ 0, unknown scale, raster scale, unknown map)
//     are reported and the generated paint is kept;
//   • a limit scrub over thousands of elements stays inside the 100 ms budget even in linkedom;
//   • the slide tween of colour scales: log limits in log space, linear limits linearly, colormap
//     tables blend per entry, kinds / named maps step at raw 0.5; a tweened view applies cleanly.
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseHTML } from 'linkedom';
import { harness } from './lib/harness.mjs';
import { applyPlotColorScale, restoreColorScales, plotColorScaleIssues } from '../src/lib/plot/colorScaleDom';
import { colorScalePatch } from '../src/lib/plot/colorScaleControls';
import { effectiveScale, colorFor, alphaFor, shortFloat } from '../src/lib/plot/colorscale';
import { colormapLut, ensureColormapLuts } from '../src/lib/color/colormapLuts';
import { lerpColorScales } from '../src/lib/slide/tween';
import type { FluxPlotManifest } from '../src/lib/plot/types';
import type { ColorScaleView } from '../src/lib/types';

const h = harness('verify-colorscale-dom');
const repo = resolve(import.meta.dirname, '..'), fixtures = join(repo, 'scripts/fixtures/colorscale');
const EDITS = JSON.parse(readFileSync(join(fixtures, 'EDITS.json'), 'utf8')) as Record<string, Record<string, { cmap?: string; vmin?: number; vmax?: number; norm?: { kind: string } }>>;
const { document } = parseHTML('<html><body></body></html>');
const load = (name: string) => ({ svg: readFileSync(join(fixtures, `${name}.svg`), 'utf8'), manifest: JSON.parse(readFileSync(join(fixtures, `${name}.fluxplot.json`), 'utf8')) as FluxPlotManifest });
const mount = (svg: string): Element => { const wrap = document.createElement('div'); wrap.innerHTML = svg.replace(/\bid="([^"]+)"/g, 'id="plot__$1"'); return wrap as unknown as Element; };
const DRAWABLE = 'path,use,rect,circle,ellipse,polygon,polyline,line,image';
const drawable = (n: Element): Element => (/^(path|use|rect|circle|ellipse|polygon|polyline|line|image)$/i.test(n.tagName) ? n : n.querySelector(DRAWABLE) ?? n);
const style = (n: Element) => (n as unknown as { style: { getPropertyValue(p: string): string } }).style;
const color = (v: string) => (v || '#000000').trim().toLowerCase();
const paint = (n: Element) => { const d = drawable(n), s = style(d); return { fill: color(s.getPropertyValue('fill') || d.getAttribute('fill') || ''), stroke: color(s.getPropertyValue('stroke') || d.getAttribute('stroke') || 'none'), fo: Number(s.getPropertyValue('fill-opacity') || 1), so: Number(s.getPropertyValue('stroke-opacity') || 1) }; };
const valueNodes = (root: Element, scaleId: string) => Array.from(root.querySelectorAll(`[data-color-scale="${scaleId}"] [data-value], [data-color-scale="${scaleId}"] [data-missing]`));
const gradientId = (m: FluxPlotManifest, scaleId: string) => { const cb = m.colorScales!.find(s => s.id === scaleId)!.colorbars[0]; const solids = m.guides!.find(g => g.id === cb)!.parts!.find(p => p.role === 'colorbar-solids')!.svgId; return `plot__${solids}.gradient`; };
const stops = (root: Element, gid: string) => Array.from(root.querySelectorAll(`[id="${gid}"] stop`)).map(s => `${s.getAttribute('stop-color')}${s.getAttribute('stop-opacity') ? '/' + s.getAttribute('stop-opacity') : ''}`);
const TR = /translate\(\s*([-\d.eE+]+)[ ,]+([-\d.eE+]+)/;
/** Visible tick positions of a key as fractions of ITS OWN anchor span (the twin's layout may shift). */
const tickFractions = (root: Element, m: FluxPlotManifest, cb: string, minor: boolean) => {
  const g = m.guides!.find(x => x.id === cb)!, a0 = g.anchors![0], a1 = g.anchors![g.anchors!.length - 1], horizontal = g.orientation === 'horizontal';
  return Array.from(root.querySelectorAll(`[id^="plot__${cb}.${minor ? 'minor.tick' : 'tick'}."]`)).filter(n => style(n).getPropertyValue('display') !== 'none')
    .map(n => { const mm = TR.exec((n.querySelector('path') ?? n).getAttribute('transform') ?? ''); return mm ? (a0.svg - Number(horizontal ? mm[1] : mm[2])) / (a0.svg - a1.svg) : NaN; })
    .filter(Number.isFinite).sort((a, b) => a - b);
};
const tickLabels = (root: Element, cb: string) => Array.from(root.querySelectorAll(`[id^="plot__${cb}.tick-label."]`)).filter(n => style(n).getPropertyValue('display') !== 'none')
  .map(n => ({ y: Number((n.querySelector('text') ?? n).getAttribute('y')), text: (n.textContent ?? '').replace(/\s+/g, '') })).sort((a, b) => b.y - a.y).map(l => l.text);
const close = (a: number[], b: number[], tol = 2e-3) => a.length === b.length && a.every((x, i) => Math.abs(x - b[i]) < tol);
const fmt = (xs: number[]) => xs.map(x => x.toFixed(3)).join(' ');
const snapshot = (root: Element) => Array.from(root.querySelectorAll('*')).map(n => { const p = paint(n); return [n.tagName, n.getAttribute('id'), p.fill, p.stroke, p.fo, p.so, n.getAttribute('transform'), n.getAttribute('x'), n.getAttribute('y'), style(n).getPropertyValue('display'), n.children.length ? '' : n.textContent].join('|'); });
const viewOf = (edit: { cmap?: string; vmin?: number; vmax?: number; norm?: { kind: string } }): ColorScaleView => ({ ...(edit.cmap ? { cmap: edit.cmap } : {}), norm: { ...(edit.norm ? { kind: edit.norm.kind as 'linear' } : {}), ...(edit.vmin != null ? { vmin: edit.vmin } : {}), ...(edit.vmax != null ? { vmax: edit.vmax } : {}) } });

try {
  await ensureColormapLuts();
  for (const name of ['hexmatrix', 'heatmap', 'hexmatrix-alpha']) {
    const base = load(name), twin = load(`${name}-edited`);
    const [scaleId, edit] = Object.entries(EDITS[name])[0];
    const scale = base.manifest.colorScales!.find(s => s.id === scaleId)!;
    const pristine = snapshot(mount(base.svg));
    const twinDom = mount(twin.svg);
    for (const [form, view] of [['a named colormap', viewOf(edit)], ['the table the editor writes', { ...colorScalePatch(scale, undefined, { cmap: edit.cmap ?? null, vmin: edit.vmin ?? undefined, vmax: edit.vmax ?? undefined, norm: (edit.norm?.kind as 'linear') ?? undefined }, colormapLut) }]] as const) {
      const wrap = mount(base.svg);
      const res = applyPlotColorScale(wrap, base.manifest, { [scaleId]: view as ColorScaleView }, 'plot');
      h.eq(res.issues, [], `${name} (${form}): applies without issues`);
      h.eq(res.unresolved, [], `${name} (${form}): every colormap resolved`);
      const ours = valueNodes(wrap, scaleId), theirs = valueNodes(twinDom, scaleId);
      h.eq(ours.length, theirs.length, `${name} (${form}): ${ours.length} data-value elements, as in the regenerated twin`);
      let mismatches = 0;
      ours.forEach((n, i) => { const a = paint(n), b = paint(theirs[i]); if (JSON.stringify(a) !== JSON.stringify(b)) { if (mismatches < 3) console.log(`   mismatch #${i} value=${n.getAttribute('data-value')} missing=${n.getAttribute('data-missing')}`, a, b); mismatches++; } });
      h.eq(mismatches, 0, `${name} (${form}): every data-value element paints hex-for-hex as fluxplot regenerated it`);
      h.eq(ours.filter(n => paint(n).fill !== paint(valueNodes(mount(base.svg), scaleId)[0]).fill).length > 0, true, `${name} (${form}): the paint really changed`);
      const gid = gradientId(base.manifest, scaleId);
      h.eq(stops(wrap, gid).length, 2 * scale.colormap.N, `${name} (${form}): the key gradient has two stops per table entry`);
      h.eq(stops(wrap, gid), stops(twinDom, gid), `${name} (${form}): the key gradient's stops match the regenerated twin`);
      const cb = scale.colorbars[0];
      for (const minor of [false, true]) {
        const ours = tickFractions(wrap, base.manifest, cb, minor), twins = tickFractions(twinDom, twin.manifest, cb, minor);
        if (!close(ours, twins)) console.log(`   ${name} ${minor ? 'minor' : 'major'} ticks: ours ${fmt(ours)} | twin ${fmt(twins)}`);
        h.ok(close(ours, twins), `${name} (${form}): ${minor ? 'minor' : 'major'} ticks re-place onto the regenerated twin's positions (${ours.length})`);
      }
      h.eq(tickLabels(wrap, cb), tickLabels(twinDom, cb), `${name} (${form}): tick labels read as the regenerated twin's`);
      // pristine restore, idempotency, identity
      const once = (wrap as unknown as { innerHTML: string }).innerHTML;
      applyPlotColorScale(wrap, base.manifest, { [scaleId]: view as ColorScaleView }, 'plot');
      h.eq((wrap as unknown as { innerHTML: string }).innerHTML, once, `${name} (${form}): a second apply of the same view rewrites nothing`);
      applyPlotColorScale(wrap, base.manifest, undefined, 'plot');
      h.eq(snapshot(wrap), pristine, `${name} (${form}): an absent view restores the generated bytes (paint, gradient, ticks)`);
      applyPlotColorScale(wrap, base.manifest, { [scaleId]: view as ColorScaleView }, 'plot');
      restoreColorScales(wrap);
      h.eq(snapshot(wrap), pristine, `${name} (${form}): restoreColorScales puts everything back`);
      applyPlotColorScale(wrap, base.manifest, { [scaleId]: view as ColorScaleView }, 'plot');
      applyPlotColorScale(wrap, base.manifest, { [scaleId]: { norm: { vmax: scale.norm.vmax! } } }, 'plot');
      h.eq(snapshot(wrap), pristine, `${name} (${form}): a view equal to the generated scale restores`);
    }
    // the effective law agrees with what was painted (reversed direction)
    const rev = mount(base.svg);
    applyPlotColorScale(rev, base.manifest, { [scaleId]: { reversed: true } }, 'plot');
    const eff = effectiveScale(scale, { reversed: true }, colormapLut);
    const wrong = valueNodes(rev, scaleId).filter(n => n.getAttribute('data-missing') !== '1' && paint(n).fill !== colorFor(eff, Number(n.getAttribute('data-value'))).slice(0, 7).toLowerCase());
    h.eq(wrong.length, 0, `${name}: reversed paints through the same law as colorFor`);
  }

  // B6 — the opacity channel: fill-opacity (and stroke-opacity for fill+stroke paints) follows
  // each element's data-alpha-value through fluxplot's law, before and after a recolour
  {
    const base = load('hexmatrix-alpha');
    const scale = base.manifest.colorScales!.find(s => s.id === 'mean')!;
    h.ok(!!scale.alpha && scale.alpha.source === 'count' && scale.alpha.range[0] === 0.25, 'the fixture scale records its alpha channel (count → 0.25…1)');
    const wrap = mount(base.svg);
    const nodes = valueNodes(wrap, 'mean').filter(n => n.getAttribute('data-alpha-value'));
    h.ok(nodes.length >= 20, `${nodes.length} hexagons carry data-alpha-value`);
    const expect = (n: Element) => shortFloat(alphaFor(scale.alpha!, Number(n.getAttribute('data-alpha-value'))));
    h.eq(nodes.filter(n => shortFloat(paint(n).fo) !== expect(n) || shortFloat(paint(n).so) !== expect(n)).length, 0, 'as generated, every hexagon\'s fill- and stroke-opacity equal the channel law of its value');
    applyPlotColorScale(wrap, base.manifest, { mean: { cmap: 'magma', norm: { vmax: 0.5 } } }, 'plot');
    h.eq(nodes.filter(n => shortFloat(paint(n).fo) !== expect(n) || shortFloat(paint(n).so) !== expect(n)).length, 0, 'after a live recolour every hexagon keeps its channel opacity');
    h.ok(nodes.some(n => paint(n).fill !== '#000000' && paint(n).fo < 1), 'and is both recoloured and translucent');
    const lo = alphaFor(scale.alpha!, NaN), hiV = alphaFor(scale.alpha!, scale.alpha!.norm.vmax as number);
    h.eq([lo, hiV], [0.25, 1], 'a missing value takes the low alpha; the maximum the high');
    h.ok(Number.isFinite(alphaFor({ source: 'p', range: [0, 1], norm: { kind: 'log', vmin: 0.001, vmax: 1 } }, 0.0316227766)), 'a log channel is finite');
    h.ok(Math.abs(alphaFor({ source: 'p', range: [0, 1], norm: { kind: 'log', vmin: 0.001, vmax: 1 } }, Math.sqrt(0.001)) - 0.5) < 1e-9, 'a log channel maps the geometric midpoint to the middle alpha');
    h.eq(alphaFor({ source: 'p', range: [0.2, 0.9], norm: { kind: 'linear', vmin: 3, vmax: 3 } }, 3), 0.9, 'equal limits give the high alpha');
    // a plain element (no data-alpha-value) under a scale with a channel keeps its own opacity
    const plain = mount(base.svg);
    const bare = valueNodes(plain, 'mean')[0];
    bare.removeAttribute('data-alpha-value');
    style(drawable(bare)).setProperty('fill-opacity', '0.7');
    applyPlotColorScale(plain, base.manifest, { mean: { cmap: 'magma' } }, 'plot');
    h.eq(paint(bare).fo, 0.7, 'an element without a channel value keeps its own opacity through a recolour');
    restoreColorScales(wrap);
    h.eq(nodes.filter(n => shortFloat(paint(n).fo) !== expect(n)).length, 0, 'restore leaves the generated opacities');
  }

  // issues keep the generated paint
  const base = load('hexmatrix'), scale = base.manifest.colorScales![0], pristine = snapshot(mount(base.svg));
  h.ok(plotColorScaleIssues(base.manifest, { rates: { norm: { vmin: 0 } } }, colormapLut)[0]?.includes('above 0'), 'a log minimum at 0 is reported');
  h.ok(plotColorScaleIssues(base.manifest, { nope: { norm: { vmax: 3 } } }, colormapLut)[0]?.includes('not in this plot'), 'an unknown scale id is reported');
  h.eq(plotColorScaleIssues(base.manifest, { rates: { norm: { vmax: 143 } } }, colormapLut), [], 'an identity view has no issues');
  const bad = mount(base.svg);
  h.eq(applyPlotColorScale(bad, base.manifest, { rates: { norm: { vmin: 0 } } }, 'plot').issues.length, 1, 'apply reports an impossible norm');
  h.eq(snapshot(bad), pristine, 'and keeps the generated paint');
  const unresolved = applyPlotColorScale(bad, base.manifest, { rates: { cmap: 'magma' } }, 'plot', { resolve: () => null });
  h.eq(unresolved.unresolved, ['magma'], 'a colormap the resolver does not know yet is reported for a later re-apply');
  h.eq(snapshot(bad), pristine, 'and the generated paint stays until it loads');
  const raster = structuredClone(base.manifest); raster.colorScales![0].recolor = 'raster';
  h.ok(applyPlotColorScale(bad, raster, { rates: { norm: { vmax: 20 } } }, 'plot').issues[0]?.includes('raster'), 'a raster scale is reported');
  h.eq(snapshot(bad), pristine, 'and left as generated');

  // budget: a limit scrub over thousands of elements
  const big = mount(base.svg), group = big.querySelector('[data-color-scale="rates"]')!, proto = group.querySelector('[data-value]')!;
  const EXTRA = 6000;
  for (let i = 0; i < EXTRA; i++) { const c = proto.cloneNode(true) as Element; c.setAttribute('data-value', String(1 + (i % 140))); c.removeAttribute('id'); group.appendChild(c); }
  applyPlotColorScale(big, base.manifest, { rates: { norm: { vmax: 20 } } }, 'plot');
  const t0 = performance.now(); const FRAMES = 20;
  for (let k = 1; k <= FRAMES; k++) applyPlotColorScale(big, base.manifest, { rates: { norm: { vmax: 20 + k * 3 } } }, 'plot');
  const perFrame = (performance.now() - t0) / FRAMES;
  console.log(`   ${EXTRA + 33} data-value elements: ${perFrame.toFixed(1)} ms per limit change (linkedom)`);
  h.ok(perFrame < 100, `a limit scrub over ${EXTRA + 33} elements stays inside the 100 ms budget (${perFrame.toFixed(1)} ms in linkedom)`);
  const t1 = performance.now();
  applyPlotColorScale(big, base.manifest, { rates: { norm: { vmax: 20 + FRAMES * 3 } } }, 'plot');
  h.ok(performance.now() - t1 < perFrame, 'an unchanged view costs less than a changed one (slots are cached)');

  // the slide tween
  const logA = { rates: { norm: { kind: 'log' as const, vmin: 1, vmax: 10 } } }, logB = { rates: { norm: { kind: 'log' as const, vmin: 1, vmax: 1000 } } };
  h.ok(Math.abs((lerpColorScales(logA, logB, .5)?.rates.norm?.vmax ?? 0) - 100) < 1e-9, 'log limits tween in log space');
  h.eq(lerpColorScales({ rates: { norm: { vmax: 10 } } }, { rates: { norm: { vmax: 30 } } }, .25)?.rates.norm?.vmax, 15, 'linear limits interpolate');
  h.eq(lerpColorScales(undefined, logB, .3), undefined, 'an absent start stays generated before raw 0.5');
  h.eq(lerpColorScales(undefined, logB, .7), logB, 'and steps to the end after it');
  h.eq(lerpColorScales({ rates: { cmap: 'viridis' } }, { rates: { cmap: 'magma' } }, .3)?.rates.cmap, 'viridis', 'named colormaps step (before)');
  h.eq(lerpColorScales({ rates: { cmap: 'viridis' } }, { rates: { cmap: 'magma' } }, .7)?.rates.cmap, 'magma', 'named colormaps step (after)');
  const tab = lerpColorScales({ rates: { cmap: { lut: ['#000000ff', '#ffffffff'] } } }, { rates: { cmap: { lut: ['#ffffffff', '#000000ff'] } } }, .5)?.rates.cmap;
  h.ok(typeof tab === 'object' && tab.lut.length === 256 && tab.lut[0] === tab.lut[255] && tab.lut[0] !== '#000000' && tab.lut[0] !== '#ffffff', 'colormap tables blend per entry (resampled to 256)');
  h.eq(lerpColorScales({ rates: { norm: { kind: 'log' } } }, { rates: { norm: { kind: 'linear' } } }, .6)?.rates.norm?.kind, 'linear', 'norm kinds step at raw 0.5');
  const mid = lerpColorScales({ rates: { norm: { vmax: 143 } } }, { rates: { cmap: colormapLut('magma')!, norm: { vmax: 20 } } }, .5)!;
  const midDom = mount(base.svg);
  h.eq(applyPlotColorScale(midDom, base.manifest, mid, 'plot').issues, [], 'a mid-tween view applies cleanly');
  h.ok(valueNodes(midDom, 'rates').some((n, i) => paint(n).fill !== paint(valueNodes(mount(base.svg), 'rates')[i]).fill), 'and paints between the ends');
} catch (e) { h.fail(e instanceof Error ? e.stack ?? e.message : String(e)); }
await h.done();
