import { restoreBibRemoval } from "../src/lib/references/bibUndo";
import assert from "node:assert/strict";
import { scanBib, assertBibValid } from "../src/lib/references/bibScanner";
import { splitBibEntries, lightEntry, lightBibEntries, decodeBibDisplay, stampDateAdded } from "../src/lib/references/bibtex";
import { planAdds } from "../src/lib/references/addPlan";
import { extractBibField } from "../src/lib/references/zoteroFiles";
import { harness } from "./lib/harness.mjs";
const h = harness("verify-bib-scanner");
const corpus = `% contact user@example.org\r\n@string{journal = "A" # { B}}\r\n@comment{ignore @misc{notPaper}}\r\n@preamble{"prefix"}\r\n@custom{KeepKey,\r\n title={A {Nested} title}, abstract={text doi={10.1/wrong}, file={wrong}}, doi={10.1000/right(1)}, file={real.pdf}, dateadded={1999-01-01}, journaltitle="Journal"}\r\n@misc{Second,title="A \\"quoted\\" title", year=2020}`;
const scan = assertBibValid(corpus);
h.eq(scan.records.filter(r => r.kind === "entry").length, 2, "structural entries and comment emails do not become papers");
const raws = splitBibEntries(corpus);
h.eq(lightEntry(raws[0]).doi, "10.1000/right(1)", "nested field-like text cannot shadow authoritative DOI");
h.eq(extractBibField(raws[0], "file"), "real.pdf", "Zotero field extraction uses same structural parser");
h.eq(lightEntry(raws[0]).container, "Journal", "BibLaTeX journaltitle projects for display");
const stamped = stampDateAdded(raws[0], "2026-09-21");
h.ok(stamped.includes("dateadded={2026-09-21}") && stamped.replace("2026-09-21", "1999-01-01") === raws[0], "date edit changes only intended value span");
const slices = scan.records.map(r => corpus.slice(r.start,r.end));
h.eq(slices, [corpus.slice(scan.records[0].start,scan.records[0].end), ...scan.records.slice(1).map(r => corpus.slice(r.start,r.end))], "scanner raw spans retain byte content including CRLF");
assert.throws(() => planAdds("", "@article{bad,title={unfinished\n@misc{good,title={safe}}"), /Malformed BibTeX/);
h.ok(true, "malformed incoming record refuses before absorbing or publishing later papers");
const sameTitle = (key: string, doi: string) => `@article{${key},title={A scientific title},author={Smith},year={2020},doi={${doi}}}`;
h.eq(planAdds(sameTitle("first","10.1/preprint"), sameTitle("second","10.1/published")).added.length,1,"distinct authoritative DOIs cannot merge by matching signature");
h.ok(planAdds("@misc{Alpha,title={first}}", "@misc{alpha,title={second}}").keys[0].toLowerCase() !== "alpha", "preserved incoming keys use filesystem case identity");
h.ok(planAdds("", "@misc{CON,title={reserved}}").keys[0] !== "CON", "new reserved filename key receives safe generated identity");
h.ok(planAdds("",corpus).appendText.includes('@string{journal = "A" # { B}}'),"structural macro source survives import");
h.eq(lightBibEntries('@string{j="Neuro" # {science}} @article{a,journaltitle=j,title={Test},date={2026-09}}')[0].container, "Neuroscience", "macro concatenation projects without rewriting raw source");
h.eq(decodeBibDisplay(String.raw`{Garc\'ia} and M{\"u}ller`), "García and Müller", "common TeX accents normalize for display and search");
h.ok(planAdds("", corpus).appendText.startsWith("% contact user@example.org\r\n"), "import preserves uninterpreted comments and structural record order");
assert.throws(() => planAdds(sameTitle("other", "10.1234/same"), sameTitle("other", "10.1234/same"), "bibtex", undefined, {restore: true}), /Cannot restore/);
h.ok(true, "undo restoration refuses intervening identity conflicts instead of dedup success");
const undoBefore = "% preface\n@article{first,title={First},dateadded={old}}\n\n@article{middle,title={Middle}}\n\n@article{last,title={Last}}\n";
const undoAfter = undoBefore.replace("@article{middle,title={Middle}}\n\n", "");
h.eq(restoreBibRemoval(undoAfter,{before:undoBefore,after:undoAfter,keys:["middle"]}),undoBefore,"delete undo restores exact bytes and original order when unchanged");
const intervening = undoAfter.replace("title={First}","title={Edited First}") + "@article{new,title={New}}\n";
const restored = restoreBibRemoval(intervening,{before:undoBefore,after:undoAfter,keys:["middle"]});
h.ok(restored.includes("Edited First") && restored.indexOf("{middle,") < restored.indexOf("{last,") && restored.includes("{new,"),"undo preserves intervening edits and additions while restoring original relative order");
assert.throws(()=>restoreBibRemoval(undoAfter+"@article{middle,title={Conflict}}",{before:undoBefore,after:undoAfter,keys:["middle"]}),/conflict/);
h.ok(true,"undo refuses an intervening same-key identity instead of rekeying the original");
h.done();
