import './lib/cssStub.mjs';
import assert from 'node:assert/strict';
import { get } from 'svelte/store';
import * as store from '../src/lib/store';
import { editSession } from '../src/lib/interact/editSession';
import { computeResizeBox } from '../src/lib/interact/gestureMath';
import { selectionTargets } from '../src/lib/interact/selectionTargets';
import { uniqueFieldKeys } from '../src/lib/interact/propertyFields';
import { resizeFrame } from '../src/lib/interact/frameResize';
import { setBoxDim } from '../src/lib/ops';
import type { Figure, Project, RectElement } from '../src/lib/types';
const near = (a: number, b: number) => assert.ok(Math.abs(a-b) < 1e-9, `${a} ≈ ${b}`);
const rect: RectElement = { type: 'rect', id: 'a', x: 40, y: 40, width: 120, height: 100, rotation: 45, fill: '#ffffff', stroke: '#000000', strokeWidth: 1, cornerRadius: 0, lockAspect: true };
for (let w = 121; w <= 200; w++) setBoxDim(rect, 'w', w);
near(rect.height, 200 / 1.2);
const ob = {x:40,y:40,w:120,h:100};
for (const [handle,point] of [['e',{x:120,y:90}],['w',{x:80,y:90}]] as const) {
  const box=computeResizeBox(ob,handle,point,true); near(box.w,80);near(box.h,80/1.2);
  near(handle==='w' ? box.x+box.w : box.x,handle==='w'?160:40);
}
const crossed=computeResizeBox(ob,'nw',{x:500,y:400},false);
assert.deepEqual(crossed,{x:159,y:139,w:1,h:1});
const fig: Figure={id:'f',canvasId:'c',name:'Frame',x:-50,y:20,width:600,height:400,elements:[rect],guides:{x:[10],y:[20]},captions:{__figure__:'Caption'},referenceKey:'legacy'};
const before=structuredClone(fig);
resizeFrame(fig,{x:-90,y:-20,w:700,h:500});
near(fig.x+rect.x,before.x+before.elements[0].x);near(fig.y+rect.y,before.y+before.elements[0].y);
assert.deepEqual(fig.guides,{x:[50],y:[60]});assert.equal(rect.width,200);assert.equal(rect.rotation,45);assert.equal(fig.referenceKey,'legacy');assert.deepEqual(fig.captions,before.captions);
assert.throws(()=>resizeFrame(fig,{x:0,y:0,w:Infinity,h:100}));
const p: Project={version:2,name:'Editing',canvases:[{id:'c',name:'Canvas'}],figures:[fig],assets:[],palette:[]};
fig.groups={parent:{id:'parent',name:'Locked',locked:true},child:{id:'child',name:'Child',parentId:'parent'}};
rect.groupId='child';
assert.equal(selectionTargets(fig,new Set(['a']),{editable:true}).length,0);
assert.equal(selectionTargets(fig,new Set(['a'])).length,1);
fig.groups.parent.locked=false;fig.groups.parent.hidden=true;
assert.equal(selectionTargets(fig,new Set(['a']),{visible:true}).length,0);
const keys=uniqueFieldKeys(['e','l','p','e','l','p'].map(key=>({key}))).map(f=>f.key);
assert.equal(new Set(keys).size,keys.length);assert.ok(!keys.includes('f')&&!keys.includes('s'));
store.loadProject(p,null);
store.commit(p=>p.name='First');store.commit(p=>p.name='Second');store.undo();store.dirty.set(false);
const original=store.historyStats();const session=editSession();
session.run(()=>store.mutate(p=>p.name='Preview'));session.cancel();
assert.equal(get(store.project).name,'First');assert.equal(get(store.dirty),false);
assert.deepEqual(store.historyStats(),original,'cancel preserves prior undo, redo and byte accounting');
store.redo();assert.equal(get(store.project).name,'Second');
session.run(()=>store.mutate(p=>p.name='Third'));session.run(()=>store.mutate(p=>p.name='Fourth'));session.finish();store.undo();assert.equal(get(store.project).name,'Second','one undo restores whole property edit');
const noOp=store.historyStats();store.dirty.set(false);
session.run(()=>store.mutate(()=>{}));session.finish();assert.deepEqual(store.historyStats(),noOp);assert.equal(get(store.dirty),false);
const foreign=store.beginGesture();store.mutate(p=>p.name='Live');store.commit(p=>p.name='Other edit');assert.equal(store.rollbackGesture(foreign),false);assert.equal(get(store.project).name,'Other edit');
const saved=editSession();store.dirty.set(false);saved.run(()=>store.mutate(p=>p.name='Saved preview'));store.dirty.set(false);saved.cancel();assert.equal(get(store.project).name,'Other edit');assert.equal(get(store.dirty),true,'cancelling an already-saved preview must save its restored baseline');
console.log('FIGURE EDITING: PASS');
