import {readFile}from'node:fs/promises';
import assert from'node:assert/strict';
import{harness}from'./lib/harness.mjs';
import{furnitureGoldens}from'./gen-model3d-furniture-goldens.mjs';
import{furnitureLayout}from'../src/lib/model3d/furnitureLayout';
import{furnitureSvg}from'../src/lib/model3d/furniture';
import{niceTicks}from'../src/lib/model3d/ticks';
import{orbitPose,axisView,pixelsPerUnit}from'../src/lib/model3d/orbit';
import{makeModel3dElement}from'../src/lib/model3d/make';
import{inspectGlb}from'../src/lib/model3d/glbCore.mjs';
import type{Scene3dManifest,Model3dAsset}from'../src/lib/model3d/types';
const h=harness('verify-model3d-furniture'),root=new URL('./fixtures/model3d/fluxplot/',import.meta.url);
const golden=JSON.parse(await readFile(new URL('./fixtures/model3d/furniture-golden.json',import.meta.url),'utf8'));assert.deepEqual(await furnitureGoldens(),golden);h.eq(Object.keys(golden).length,33,'11 fixtures ×3 views match exact layout/SVG goldens');
const m:Scene3dManifest=JSON.parse(await readFile(new URL('box-axes.fluxplot.json',root),'utf8')),info=inspectGlb(await readFile(new URL('box-axes.glb',root))),asset:Model3dAsset={id:'a',name:'box.glb',kind:'glb',path:'assets/a.glb',naturalWidth:336,naturalHeight:288,sha256:'0'.repeat(64),bytes:4000,model:info},el=makeModel3dElement(asset,{manifest:m,id:'test'});
const layout=furnitureLayout(m,el),pose=orbitPose(el,info.bounds,layout.viewport),front=furnitureSvg(m,el,pose,layout),back=furnitureSvg(m,{...el,...axisView('back')},orbitPose({...el,...axisView('back')},info.bounds,layout.viewport),layout);
h.ok(front.under.includes('<text')&&front.under.includes('x (µm)'),'axes use vector text');h.ok(front.under!==back.under,'panes and projected ticks follow view');h.ok(!/NaN|Infinity/.test(front.under),'all projected coordinates finite');h.ok(front.under.includes('test__axes.x.ticks'),'semantic part ids namespaced');
const cardinal={...el,...axisView('front')},cardinalSvg=furnitureSvg(m,cardinal,orbitPose(cardinal,info.bounds,layout.viewport),layout);h.ok(!cardinalSvg.underNodes.some(n=>n.partId==='axes.z.ticks'||n.partId==='axes.z.label'),'collapsed depth axis hides coincident ticks and labels');
const rotated:Scene3dManifest={...m,toWorld:[1,0,0,0,0,0,-1,0,0,1,0,0,0,0,0,1],bounds:{min:[1,3,-7],max:[2,5,-4]},axes:{kind:'box'}},explicit:Scene3dManifest={...rotated,axes:{kind:'box',x:{lim:[1,2]},y:{lim:[4,7]},z:{lim:[3,5]}}};h.eq(furnitureSvg(rotated,el,pose,layout).under,furnitureSvg(explicit,el,pose,layout).under,'absent data limits inverse-rotate world bounds once');
const constant:Scene3dManifest={spec:'fluxplot/scene3d',schemaVersion:'0.1.0',glb:'constant.glb',parts:[{id:'field',role:'surface-field',node:'field',field:{cmap:{name:'constant',stops:[[0,'#000000'],[1,'#FFFFFF']]},range:[2,2],ticks:[2],label:'Constant'}},{id:'bar',role:'colorbar',field:'field'}]};const cl=furnitureLayout(constant,el),cs=furnitureSvg(constant,el,pose,cl);h.ok(cs.over.includes('>2</text>')&&!/NaN|Infinity/.test(cs.over),'constant colorbar has finite centered tick');h.ok(Number(cs.overNodes.find(n=>n.partId==='bar')!.children!.find(n=>n.key==='cbar-title')!.attrs.y)>=cl.fontSize,'colorbar title baseline leaves a full font size above it');
const larger=furnitureLayout(m,{width:el.width*2,height:el.height*2});h.eq(larger.fontSize,layout.fontSize,'resize keeps physical font size');h.ok(larger.viewport.width>layout.viewport.width,'resize expands3D viewport');
const continuous:Scene3dManifest=JSON.parse(await readFile(new URL('continuous.fluxplot.json',root),'utf8'));
for(const size of [9.333333333333332,21])for(const scale of [.5,1,3]){
 const partId=continuous.parts!.find(p=>p.role==='colorbar')!.id;
 const element={...el,width:el.width*scale,height:el.height*scale,overrides:{[partId]:{fontSize:size}}};
 const l=furnitureLayout(continuous,element,element.overrides),s=furnitureSvg(continuous,element,pose,l);
 const nodes=s.overNodes.find(n=>n.partId===partId)!.children!,title=nodes.find(n=>n.key==='cbar-title')!,labels=nodes.filter(n=>n.key.startsWith('cbar-label-'));
 const top=Math.min(...labels.map(n=>Number(n.attrs.y)));
 h.ok(top-Number(title.attrs.y)>=size*1.3,`colorbar title separates from top tick at ${scale}× box / ${size}px font`);
 h.ok(Number(title.attrs.y)>=size,`colorbar title stays within top margin at ${scale}× box / ${size}px font`);
 h.ok([title,...labels].every(n=>n.attrs['font-size']===size),`colorbar physical font unchanged at ${scale}× box / ${size}px font`);
}
h.ok(front.under.includes('font-family="Inter, sans-serif"'),'standalone house font has intentional sans fallback');h.ok(furnitureSvg(m,{...el,overrides:{'axes.x.label':{fontFamily:'Georgia'}}},pose,layout).under.includes('font-family="Georgia"'),'explicit font override remains verbatim');
const sm:Scene3dManifest=JSON.parse(await readFile(new URL('scalebar.fluxplot.json',root),'utf8')),se=makeModel3dElement(asset,{manifest:sm,id:'scale'}),sl=furnitureLayout(sm,se),sp=orbitPose(se,info.bounds,sl.viewport),ss=furnitureSvg(sm,se,sp,sl);const scaleGroup=ss.overNodes.find(n=>n.partId==='scalebar'),bar=scaleGroup?.children?.find(n=>n.tag==='line');h.ok(!!bar,'scale bar rendered');h.ok(Math.abs(Number(bar?.attrs.x2)-Number(bar?.attrs.x1)-(sm.parts!.find(p=>p.id==='scalebar')!.length!*pixelsPerUnit(sp,sl.viewport)!))<1e-9,'scale bar exact data-unit projection');h.ok(!furnitureSvg(sm,se,{...sp,projection:'perspective'},sl).over.includes('scale-line'),'perspective hides exact scale bar');
const hidden={...sm,parts:sm.parts!.map(p=>p.id==='scalebar'?{...p,hidden:true}:p)};h.eq(furnitureLayout(hidden,se,{'scalebar':{hidden:false}}).scalebars.length,1,'explicit show overrides source-hidden');
h.eq(niceTicks(-1,1),[-1,-.5,0,.5,1],'nice tick oracle');h.eq(niceTicks(1.21,3.82),[1.5,2,2.5,3,3.5],'data range tick oracle');
for(const name of ['furniture.ts','furnitureLayout.ts','ticks.ts'])h.ok(!/getBoundingClientRect|measureText|document\.|window\./.test(await readFile(new URL(`../src/lib/model3d/${name}`,import.meta.url),'utf8')),`${name} no DOM/text measurement`);
const styled={...el,overrides:{'axes.x.label':{fill:'#FF0000',fontSize:21}}},s=furnitureSvg(m,styled,pose,layout);h.ok(s.under.includes('fill="#FF0000"')&&s.under.includes('font-size="21"'),'part text styling shares plot units');await h.done();
