import assert from 'node:assert/strict';
import { harness } from './lib/harness.mjs';
import { setModelField, setModelStates, setModelFrame, modelFrame } from '../src/lib/model3d/semanticOps';
import { makeModel3dElement } from '../src/lib/model3d/make';
import { mapValues } from '../src/lib/model3d/colormap';
import { inspectGlb, writeGlb } from '../src/lib/model3d/glbCore.mjs';
import type { Project } from '../src/lib/types';
import type { Model3dAsset } from '../src/lib/model3d/types';
const h = harness('verify-model3d-semantics');
const info = inspectGlb(writeGlb({ parts: [{ name: 'mesh', positions: [0,0,0,1,0,0,0,1,0], indices: [0,1,2] }] }));
info.states = ['first', 'second', 'third'];
const asset: Model3dAsset = { id: 'asset', name: 'shape.glb', kind: 'glb', path: 'assets/shape.glb', sha256: 'a'.repeat(64), bytes: 1024, naturalWidth: 336, naturalHeight: 252, model: info };
const a = makeModel3dElement(asset, { id: 'a' }), b = makeModel3dElement(asset, { id: 'b' });
const untouched = { id: 'rect', type: 'rect', fill: '#abcdef' };
const project = { assets: [asset], figures: [{ id: 'figure', elements: [a,b,untouched] }] } as unknown as Project;
a.overrides = { mesh: { fill: '#123456' } };
setModelField(project, ['a','b','rect'], 'value', { cmap: 'viridis', range: [-1,2] });
h.eq(a.fields, b.fields, 'field batch updates both models');
h.eq(a.modelColors, 'source', 'field edits activate source colors');
h.eq(a.overrides, { mesh: { fill: '#123456' } }, 'field edits preserve explicit part fills');
h.eq(untouched, { id: 'rect', type: 'rect', fill: '#abcdef' }, 'nonmodels remain byte-identical');
setModelField(project, ['a'], 'value', { range: [2,2] });
h.eq(a.fields?.value.range, [2,2], 'constant field override accepted');
h.eq(Array.from(mapValues([2,3], { cmap: { name: 'test', stops: [[0,'#000000'],[1,'#FFFFFF']] }, range: [0,1] }, { range: [2,2] })), [0,0,0,0,0,0], 'constant override uses source/Matplotlib colormap zero');
const before = JSON.stringify(project);
assert.throws(() => setModelField(project, ['a','b'], 'value', { range: [2,1] }), /minimum/);
assert.throws(() => setModelField(project, ['a','b'], 'value', { cmap: 'no-such-map' }), /Unknown colormap/);
assert.throws(() => setModelField(project, ['a'], 'value', { range: [NaN,1] }), /finite/);
h.eq(JSON.stringify(project), before, 'invalid field batches mutate nothing');
setModelField(project, ['a'], 'value', { cmap: null });
h.eq(a.fields?.value, { range: [2,2] }, 'member reset retains the other override');
setModelField(project, ['a'], 'value', null);
h.ok(!Object.hasOwn(a, 'fields'), 'last field reset removes empty persisted map');
for (const fieldId of ['constructor', '__proto__']) {
  setModelField(project, ['a'], fieldId, { range: [0,1] });
  h.ok(Object.hasOwn(a.fields!, fieldId) && JSON.stringify(a.fields).includes(fieldId), `${fieldId} is an ordinary persisted field key`);
  setModelField(project, ['a'], fieldId, null);
}
h.ok(!Object.hasOwn(a, 'fields'), 'inherited-name field reset leaves no prototype entry');
setModelStates(project, ['a','b'], { first: .25, second: 0, third: 2 });
h.eq(a.modelStates, { first: .25, third: 1 }, 'shape weights clamp and zero uses absence');
h.eq(b.modelStates, a.modelStates, 'shape weights apply across selected models');
const stateBefore = JSON.stringify(project);
assert.throws(() => setModelStates(project, ['a','b'], { first: .5, missing: .2 }), /Unknown shape/);
assert.throws(() => setModelStates(project, ['a','b'], { first: Infinity }), /finite/);
h.eq(JSON.stringify(project), stateBefore, 'invalid state batches mutate nothing');
setModelFrame(project, ['a','b'], info.states, 1.25);
h.eq(a.modelStates, { first: .75, second: .25 }, 'sequence frame blends adjacent stored targets');
h.eq(modelFrame(a.modelStates, info.states), 1.25, 'derived frame round trips fractional weights');
h.eq(modelFrame({ first: .5 }, info.states), .5, 'base blends with first target');
h.eq(modelFrame(undefined, info.states), 0, 'absent weights are base frame');
h.eq(modelFrame({ first: .5, third: .5 }, info.states), null, 'nonadjacent weights read Custom');
h.eq(modelFrame({ second: .5 }, info.states), null, 'base plus nonfirst target reads Custom');
h.eq(modelFrame({ unknown: .1 }, info.states), null, 'unknown nonzero target reads Custom');
h.eq(modelFrame({ unknown: 0 }, info.states), 0, 'unknown zero cannot create Custom');
h.eq(modelFrame({ first: NaN }, info.states), null, 'nonfinite weights never report a frame');
assert.throws(() => setModelFrame(project, ['a'], [...info.states].reverse(), 1), /state order/);
assert.throws(() => setModelFrame(project, ['a'], info.states, Infinity), /finite/);
setModelFrame(project, ['a'], info.states, 999);
h.eq(a.modelStates, { third: 1 }, 'sequence frame clamps to final target');
setModelStates(project, ['a'], null);
h.ok(!Object.hasOwn(a, 'modelStates') && !Object.hasOwn(a, 'frame'), 'reset clears weights and frame is never persisted');
await h.done();
