import { mkdtemp, readFile, copyFile, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { promisify } from 'node:util';
import { execFile } from 'node:child_process';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { harness } from './lib/harness.mjs';
import { tsxRun } from './lib/tsxRun.mjs';
import * as core from '../flux-core/index';
import { loadFigModel } from '../flux-core/model';
import { setPlotView } from '../src/lib/ops';
import { plotViewPatch } from '../src/lib/plot/viewControls';
import { createDeck, addSlide, addBeat, addElement } from '../src/lib/slide/ops';
const h=harness('verify-plot-view-verb'), root=await mkdtemp(join(tmpdir(),'flux-view-verb-'));
const run=promisify(execFile), repo=resolve(import.meta.dirname,'..');
const cli=(...args:string[])=>run(...tsxRun(join(repo,'flux-cli.ts'),[...args,'--root',root]),{cwd:repo,timeout:30000});
let client: Client | undefined;
try {
  await core.scaffold(root,{title:'Axis view'});
  await mkdir(join(root,'plots'),{recursive:true});
  for(const ext of ['svg','fluxplot.json']) await copyFile(join(repo,`scripts/fixtures/plots/mpl_sine_waves_FLUXPLOT.${ext}`),join(root,`plots/sine.${ext}`));
  await core.createFigure(root,{id:'fig-view',name:'View'});
  await core.importPlots(root,'fig-view',[join(root,'plots/sine.svg')]);
  const read=async()=>{const m=await loadFigModel(root);return {m,el:m.project.figures.find(f=>f.id==='fig-view')!.elements.find(e=>e.type==='plot')!}};
  const original=await read();
  if(original.el.type!=='plot') throw Error('plot fixture missing');
  const id=original.el.id,manifest=JSON.parse(await readFile(join(root,'plots/sine.fluxplot.json'),'utf8'));
  const expected=structuredClone(original.m.project);
  setPlotView(expected,id,plotViewPatch(undefined,manifest,{xMax:4}),manifest.axes[0]);
  await cli('set-plot-view','fig-view',id,'--x-max','4');
  h.eq((await read()).el,expected.figures.find(f=>f.id==='fig-view')!.elements.find(e=>e.id===id),'CLI writes exactly the shared GUI op result');
  const beforeInvalid=JSON.stringify((await read()).el);
  try{await cli('set-plot-view','fig-view',id,'--x-scale','log');h.fail('nonpositive log domain rejected')}catch{h.ok(true,'nonpositive log domain rejected')}
  h.eq(JSON.stringify((await read()).el),beforeInvalid,'invalid view leaves saved bytes unchanged');
  await cli('set-plot-view','fig-view',id,'--reset');h.ok(!('view' in (await read()).el),'figure reset deletes view');
  const deck=createDeck({id:'talk',title:'View',withTitleSlide:false}),slide=addSlide(deck,{layout:'blank'});
  addElement(deck,slide.id,structuredClone(original.el));
  const first=addBeat(deck,slide.id,{label:'First'})!,second=addBeat(deck,slide.id,{label:'Zoom'})!;
  await core.saveDeck(root,deck);
  await cli('set-plot-view',`talk/${slide.id}`,id,'--x-max','6');
  await cli('set-plot-view',`talk/${slide.id}`,id,'--x-max','4','--beat',first.id);
  await cli('set-plot-view',`talk/${slide.id}`,id,'--x-min','2','--beat',second.id);
  const disk=JSON.parse(await readFile(join(root,'slides/talk/deck.json'),'utf8')),s=disk.slides[0];
  h.eq(s.elements.find((e:any)=>e.id===id).view.x.domain[1],6,'deck Design form persists view');
  h.eq(s.beats[2].tracks[0].to.state.view.x.domain,[2,4],'later beat inherits previous endpoint before patching one limit');
  await cli('set-plot-view',`talk/${slide.id}`,id,'--reset','--beat',second.id);
  const reset=JSON.parse(await readFile(join(root,'slides/talk/deck.json'),'utf8'));
  h.eq(reset.slides[0].beats[2].tracks[0].to.state.view,null,'beat reset writes sparse deletion without changing Design');
  const transport=new StdioClientTransport({command:tsxRun('flux-mcp.ts',[root,'--toolset','full'])[0],args:tsxRun('flux-mcp.ts',[root,'--toolset','full'])[1],cwd:repo,env:{...process.env,FLUX_NO_MIGRATE:'1',FLUX_MCP_TOOLSET:'full'} as Record<string,string>});
  client=new Client({name:'view-verifier',version:'1'});await client.connect(transport);
  const response=await client.callTool({name:'set_plot_view',arguments:{target:'fig-view',elementId:id,xMax:4}});
  h.ok(!response.isError,'real MCP registry twin executes');
  h.eq((await read()).el,expected.figures.find(f=>f.id==='fig-view')!.elements.find(e=>e.id===id),'MCP and CLI persist identical view');
  h.ok(core.plotViewPatch===plotViewPatch&&core.setPlotView===setPlotView,'headless exports share authoring implementation');
} catch(e) {h.fail(e instanceof Error?e.stack:String(e))}
await h.done(async()=>{await client?.close();await rm(root,{recursive:true,force:true})});
