import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { createRequire } from "node:module";
import { galleryDissectionKey, openGalleryVideo } from "../src/lib/plot/galleryExpanded";
import type { FileBridge } from "../src/lib/project/types";
import { fileLinksSupported, fileLinkSkipNote } from "./lib/symlinks.mjs";
const require = createRequire(import.meta.url);
const { createVideoMediaCore } = require("../electron/ipc/videoMedia.cjs");
const scratch = await fs.mkdtemp(path.join(os.tmpdir(), "flux-gallery-capability-"));
let checks = 0;
function check(value: unknown, label: string) { assert.ok(value, label); checks++; console.log("  ✓ " + label); }
try {
  const root = path.join(scratch, "project"), outside = path.join(scratch, "outside.mp4");
  await fs.mkdir(path.join(root, "plots/nested"), { recursive: true });
  await fs.mkdir(path.join(root, "slides/deck/assets"), { recursive: true });
  const movie = path.join(root, "plots/nested/source.mp4"), mov = path.join(root, "plots/nested/source.MOV");
  const bytes = Buffer.from("0123456789");
  await Promise.all([movie, mov, outside, path.join(root, "slides/deck/assets/saved.mp4")].map(file => fs.writeFile(file, bytes)));
  const handlers = new Map<string, Function>();
  let stream: (request: Request) => Promise<Response>;
  let liveRoot = root;
  const sender = Object.assign(new EventEmitter(), { id: 10, isDestroyed: () => false });
  const other = Object.assign(new EventEmitter(), { id: 11, isDestroyed: () => false });
  const event = { sender }, otherEvent = { sender: other };
  const guarded: string[] = [];
  const core = createVideoMediaCore({ app: { whenReady: () => Promise.resolve() }, protocol: { handle: (_scheme: string, fn: typeof stream) => stream = fn }, rootFor: () => liveRoot, fsReadGuard: (file: string) => guarded.push(file), noteWrite: () => {} });
  core.registerHandlers({ handle: (name: string, fn: Function) => handlers.set(name, fn) });
  await Promise.resolve();
  const open = (request = { root, path: movie }, owner = event) => handlers.get("gallery:videoUrl")!(owner, request);
  const release = (url: string, owner = event) => handlers.get("gallery:releaseVideoUrl")!(owner, url);
  const read = (url: string, headers?: Record<string, string>, method = "GET") => stream!(new Request(url, { headers, method }));
  const url = await open();
  check(/^flux-media:\/\/video\/[a-f0-9]{48}$/.test(url) && guarded.includes(movie), "gallery previews receive a guarded opaque capability, never a filesystem URL");
  const partial = await read(url, { Range: "bytes=2-5" });
  check(partial.status === 206 && partial.headers.get("Content-Range") === "bytes 2-5/10" && await partial.text() === "2345", "actual native protocol serves exact bounded byte ranges");
  const head = await read(url, undefined, "HEAD");
  check(head.status === 200 && head.headers.get("Content-Length") === "10" && await head.text() === "", "HEAD exposes metadata without reading a response body");
  check((await read(url, { Range: "bytes=99-" })).status === 416 && (await read(url, undefined, "POST")).status === 405, "invalid ranges and write-like methods refuse");
  await release(url, otherEvent);
  check((await read(url)).status === 200, "another window cannot release this preview");
  const second = await open(); await release(url);
  check((await read(url)).status === 403 && (await read(second)).status === 200, "closing a preview revokes only its own capability");
  const movUrl = await open({ root, path: mov });
  check((await read(movUrl)).headers.get("Content-Type") === "video/quicktime", "MOV streams retain their real media content type");
  for (const request of [{ root: scratch, path: movie }, { root, path: outside }, { root, path: path.join(root, "plots/../slides/deck/assets/saved.mp4") }, { root, path: path.join(root, "plots/nested/source.txt") }]) await assert.rejects(() => open(request));
  check(true, "wrong roots, outside files, traversal and non-video paths refuse");
  // File symlinks only — a junction takes a directory, so win32 without Developer
  // Mode cannot express this case at all.
  if (fileLinksSupported()) {
    const link = path.join(root, "plots/nested/link.mp4");
    await fs.symlink(outside, link); await assert.rejects(() => open({ root, path: link }));
    await fs.unlink(link); await fs.symlink(movie, link); const linked = await open({ root, path: link });
    await fs.unlink(link); await fs.symlink(outside, link);
    check((await read(linked)).status !== 200, "capabilities revalidate symlinks on every request");
  } else console.log(fileLinkSkipNote("capabilities revalidate symlinks on every request"));
  const saved = await handlers.get("slides:videoMediaUrl")!(event, { root, path: "slides/deck/assets/saved.mp4" });
  await release(saved);
  check((await read(saved)).status === 200, "gallery release cannot revoke an existing slide's playback");
  liveRoot = scratch;
  check((await read(second)).status === 403, "changing projects immediately invalidates gallery streams");
  liveRoot = root; sender.emit("destroyed");
  check((await read(second)).status === 403, "closing the owning window releases remaining capabilities");
  let releases = 0, fullReads = 0;
  const opened = await openGalleryVideo(root, { abs: movie, name: "source.mp4" }, { videoGalleryUrl: async () => "flux-media://video/test", releaseVideoGalleryUrl: async () => { releases++; }, readFile: async () => { fullReads++; throw new Error("must not read a full movie"); } } as unknown as FileBridge);
  opened.release(); opened.release();
  check(releases === 1 && fullReads === 0, "renderer media cleanup is idempotent and never reads full movie bytes");
  check(galleryDissectionKey({ abs: path.join(root, "plots/nested/plot.svg"), name: "plot.svg" }, root) === "nested/plot" && galleryDissectionKey({ abs: path.join(root, "plots/_dissections/nested/plot/a.svg"), name: "a.svg" }, root) === "", "gallery dissection lookup shares nested paths and companion exclusions");
  console.log(`##VERIFY## ${JSON.stringify({ script: "verify-gallery-video-capability", ok: true, checks, failed: 0 })}`);
} finally { await fs.rm(scratch, { recursive: true, force: true }); }
