import { harness } from './lib/harness.mjs';
import { setNumericProperty } from '../src/lib/interact/elementProperties';
import { setModelView } from '../src/lib/model3d/viewOps';
import { numericStep, numericFraction } from '../src/lib/interact/numericStep';
import { cascadeElements, ensurePanelLabels } from '../src/lib/ops';
import { makeModel3dElement } from '../src/lib/model3d/make';
import { inspectGlb, writeGlb } from '../src/lib/model3d/glbCore.mjs';
import type { Project } from '../src/lib/types';
import type { Model3dAsset } from '../src/lib/model3d/types';
const h = harness('verify-model3d-view-ops');
const model = inspectGlb(writeGlb({parts:[{name:'mesh',positions:[0,0,0,1,0,0,0,1,0],indices:[0,1,2]}]}));
const asset:Model3dAsset = {id:'asset',kind:'glb',name:'mesh',path:'assets/mesh.glb',bytes:200,sha256:'a'.repeat(64),model};
const a=makeModel3dElement(asset,{id:'a'}),b=makeModel3dElement(asset,{id:'b',box:{x:400}});
const rect={id:'rect',type:'rect',x:0,y:0,width:40,height:40,rotation:0,fill:'#123456',stroke:'none',strokeWidth:0};
const p={assets:[asset],figures:[{id:'fig',width:900,height:500,elements:[a,b,rect]}]} as unknown as Project;
const originalRect=JSON.stringify(rect);
setModelView(p,['a','rect'],{orbitAzimuth:750,orbitElevation:100,orbitZoom:0,orbitFov:300,modelColors:'source',modelLighting:'unlit',fill:'#abcdef'});
h.eq([a.orbitAzimuth,a.orbitElevation,a.orbitZoom,a.orbitFov],[750,90,.02,120],'camera keeps unwrapped azimuth and clamps physical ranges');
h.eq(JSON.stringify(rect),originalRect,'nonmodel selection stays byte-identical');
h.eq([a.modelColors,a.modelLighting,a.fill],['source','unlit','#abcdef'],'look properties share the mutation core');
const before=JSON.stringify(a);setModelView(p,['a'],{orbitAzimuth:NaN,orbitZoom:Infinity});h.eq(JSON.stringify(a),before,'nonfinite values do not corrupt camera');
setModelView(p,['a','b'],{orbitAzimuth:0,orbitZoom:1});
cascadeElements(p,'fig',['a','b'],{property:'orbitAzimuth',delta:30,firstFixed:true});h.eq(p.figures[0].elements.filter(e=>e.type==='model3d').map(e=>e.orbitAzimuth),[0,30],'cascade builds a strip of distinct model views');
cascadeElements(p,'fig',['a','b'],{property:'orbitZoom',mode:'mul',factor:2,firstFixed:true});h.eq(p.figures[0].elements.filter(e=>e.type==='model3d').map(e=>e.orbitZoom),[1,2],'zoom cascade multiplies through shared operations');
h.eq(ensurePanelLabels(p,'fig').created,2,'model boxes are auto-lettering anchors');
h.eq(numericStep(.9,1,1,1.1),.99,'wheel zoom has exact multiplicative step');h.eq(numericStep(.99,-1,1,1.1),.9,'opposite zoom step restores value');
h.eq(numericStep(30,2,5),40,'ordinary number fields retain additive steps');
h.ok(Math.abs(numericFraction(1,.1,10,1.1)-.5)<1e-9,'zoom track is logarithmic');
asset.model.states=['first','second'];
const target=p.figures[0].elements.find(e=>e.id==='a')!;
setNumericProperty(p,target,'modelFrame',1.5);
h.eq(target.type==='model3d'?target.modelStates:undefined,{first:.5,second:.5},'derived Frame writes named weights against the supplied project');
h.ok(!Object.hasOwn(target,'modelFrame'),'derived Frame is never persisted as a separate property');
await h.done();
