#!/usr/bin/env -S npx tsx
import assert from "node:assert/strict";
import { parseHTML, DOMParser } from "linkedom";
import { ghostFixture } from "./lib/ghostFixture";
import type { Slide } from "../src/lib/slide/types";
import type { FluxPlotManifest } from "../src/lib/plot/types";
const { document } = parseHTML("<html><body></body></html>");
Object.assign(globalThis, { document, DOMParser });
const { compileSlide, ghostTargetIds } = await import("../src/lib/slide/compile");
const { createPlayer } = await import("../src/lib/slide/player/player");
const { createDeck } = await import("../src/lib/slide/ops");
const { FLUX_DARK } = await import("../src/lib/slide/theme");
const { cachePlot } = await import("../src/lib/plot/store");
let checks = 0;
const check = (v: unknown, label: string) => { assert.ok(v, label); checks++; console.log("  ok:", label); };
const near = (a: number, b: number) => Math.abs(a - b) < .00001;
const slide = ghostFixture(), saved = JSON.stringify(slide), compiled = compileSlide(slide);
check(JSON.stringify(slide) === saved, "compilation never rewrites canonical fallback elements");
check(compiled.issues.length === 0, "valid independent and chained ghosts have no diagnostics");
check(ghostTargetIds(slide).join() === "g1,g2,child", "Design can exclude every ghost independently of ordinary hidden objects");
check(compiled.sample(1).presentation.unbornElementIds?.length === 3, "all copies are unborn before the birth step");
check(compiled.sample(2, 99).presentation.unbornElementIds?.join() === "g1,child", "each result respects its independent birth delay");
check(compiled.sample(2, 100).presentation.unbornElementIds?.join() === "child", "copy is born exactly at its delayed start");
check(compiled.preState("g1", 2)?.x === 110 && near(compiled.preState("g1", 2)?.opacity ?? 0, .18), "birth captures prior Change, appearance movement and authored opacity times dim");
check(compiled.preState("g1", 2)?.name === "First copy", "resolved copy retains its own authoring identity");
check(compiled.preState("child", 3)?.x === 310, "chained ghost starts from parent endpoint before same-step parent Change");
check(compiled.sample(2, 600).elements.find(e => e.id === "g1")?.x === 210, "inspected midpoint uses captured source, not saved fallback or simultaneous source move");
const deck = createDeck({ withTitleSlide: false }); deck.slides = [slide]; deck.defaults.transition = "none";
const host = document.createElement("div") as unknown as HTMLElement;
const player = createPlayer(host, deck, { theme: FLUX_DARK, reducedMotion: true });
const node = (id: string) => host.querySelector(`[data-el-id="${id}"]`) as HTMLElement;
const first = node("g1"), child = first.firstElementChild;
check(first.style.visibility === "hidden", "offline/runtime Design hides copied fallback geometry");
player.seek(0, 2, 600);
check(first.style.visibility === "visible" && first.style.transform.includes("translate(100px, 30px)") && near(Number(first.style.opacity), .18), "runtime midpoint matches effective captured pose and inherited style");
player.seek(0, 3, 500);
check(node("child").style.transform.includes("translate(100px, 0px)"), "direct later seek starts chained ghost at correct parent endpoint");
player.seek(0, 2, 99); check(first.style.visibility === "hidden", "reverse seek before birth removes the copy");
player.seek(0, 2, 1100); check(first.style.left === "310px", "reverse then forward seek restores exact endpoint");
check(first === node("g1") && child === first.firstElementChild, "direct and reverse seeks retain the same result and content nodes");
player.destroy();
const disabled = structuredClone(slide); disabled.beats[2].tracks[0].disabled = true;
check(compileSlide(disabled).sample(3).presentation.unbornElementIds?.includes("g1"), "disabled birth never makes its result available");
const orphan = structuredClone(slide); orphan.elements = orphan.elements.filter(e => e.id !== "source");
const orphanPlan = compileSlide(orphan);
check(orphanPlan.preState("g1", 2)?.x === 900 && orphanPlan.issues.some(i => /saved copy/.test(i.reason)), "deleted source uses saved fallback with a visible diagnostic");
const cycle = structuredClone(slide); cycle.beats[2].tracks[0].ghostFrom = "g2";
check(compileSlide(cycle).issues.some(i => /not yet born/.test(i.reason)), "same-step dependencies are diagnosed without recursive resolution");
const changed = structuredClone(slide); changed.beats[1].tracks[0].to!.state!.x = 200;
check(compileSlide(changed).preState("g1", 2)?.x === 210 && JSON.stringify(slide) === saved, "recompile follows changed source pose while preserving the existing document");
const text: Slide = { id: "text", elements: [{ id: "t", type: "text", x: 0, y: 0, width: 100, height: 30, rotation: 0, text: "Count 10", fontFamily: "Arial", fontSize: 20, fontWeight: 400, fontStyle: "normal", color: "#fff", align: "left", sizing: "fixed" }], beats: [{ id: "base", tracks: [] }, { id: "count", tracks: [{ target: "t", preset: "countUp", params: { from: 10, to: 30 } }] }, { id: "birth", tracks: [{ target: "copy", ghostFrom: "t", preset: "transform", to: { state: { text: "Count 50" } } }] }] };
text.elements.push({ ...text.elements[0], id: "copy" });
check((compileSlide(text).preState("copy", 2) as { text: string }).text === "Count 30", "text ghost captures effective prior countUp content");
const manifests: Record<string, FluxPlotManifest> = {};
for (const [id, y] of [["A", 20], ["B", 80]] as const) {
  manifests[id] = { spec: "fluxplot", schemaVersion: "0.2.0", plotType: "scatter", svg: "", size: { width: 100, height: 100, unit: "px" }, axes: [], series: [{ id: "s", points: [{ svgId: "p0", index: 0, x: .5, y }] }] } as FluxPlotManifest;
  cachePlot(id, `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><circle id="p0" cx="50" cy="${y}" r="4" opacity="0.4"/></svg>`, manifests[id]);
}
const plot: Slide = { id: "plot", elements: [{ id: "p", type: "plot", assetId: "A", x: 0, y: 0, width: 100, height: 100, rotation: 0, source: { svgPath: "plots/A.svg" } }], beats: [{ id: "base", tracks: [] }, { id: "data", tracks: [{ target: "p", preset: "transform", to: { assetId: "B", svgPath: "plots/B.svg", manifestPath: "plots/B.json", frozen: true } }, { target: "p", part: "p0", preset: "dim" }] }, { id: "birth", tracks: [{ target: "pcopy", ghostFrom: "p", preset: "transform", duration: 1000, easing: "linear", to: { state: { x: 200, width: 200 } } }] }] };
plot.elements.push({ ...plot.elements[0], id: "pcopy" });
const options = { theme: FLUX_DARK, reducedMotion: true, plotManifest: (id: string) => manifests[id] };
const plotPlan = compileSlide(plot, undefined, options), seed = plotPlan.copySourceState("p", 2);
check(seed?.type === "plot" && seed.assetId === "B" && seed.source?.svgPath === "plots/B.svg" && seed.source?.frozen, "copied plot asset and explicit frozen source paths stay coherent after data Change");
check(near(plotPlan.sample(2).partStates.pcopy.p0.opacity, .3), "inspected ghost retains inherited per-part presentation as a factor");
deck.slides = [plot];
const plotted = createPlayer(host, deck, options);
for (const time of [0, 500, 1000, 250, 1000]) {
  plotted.seek(0, 2, time);
  const part = host.querySelector('[id="pcopy__p0"]') as SVGElement;
  check(part.getAttribute("cy") === "80" && near(Number(part.style.opacity), .12), `plot ghost ${time}ms uses B geometry and authored opacity × inherited part dim without compounding`);
}
plotted.destroy();
cachePlot("B", '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><circle id="p0" cx="50" cy="60" r="4" opacity="0.4"/></svg>', manifests.B);
const refreshed = createPlayer(host, deck, options); refreshed.seek(0, 2, 0);
check(host.querySelector('[id="pcopy__p0"]')?.getAttribute("cy") === "60", "newly accepted source bytes reach the ghost origin on recompilation without editing its fallback");
refreshed.destroy();
console.log(`GHOST RUNTIME: PASS (${checks} assertions)`);
