import assert from "node:assert/strict";
import { videoFixture } from "./lib/slideVideoFixture";
import { planSlideVideo, videoFrame, videoOptions, videoSize } from "../src/lib/slide/video";
import { compileSlide } from "../src/lib/slide/compile";
import { harness } from "./lib/harness.mjs";
const h = harness("verify-slide-video");
const slide = videoFixture().slides[0];
const durations = compileSlide(slide).cues.map(c => c.duration);
const plan = planSlideVideo(slide, durations, { stepDelayMs: 500, startHoldMs: 1000, endHoldMs: 1000, fps: 60 });
assert.deepEqual(plan.cues, [{ fromBeat: 1, beat: 2, start: 1000, duration: 1000 }, { fromBeat: 3, beat: 3, start: 2500, duration: 500 }]);
assert.equal(plan.frameCount, 240);
assert.deepEqual(videoFrame(plan, 59), { fromBeat: 0, beat: 0, time: Infinity });
assert.deepEqual(videoFrame(plan, 90), { fromBeat: 1, beat: 2, time: 500 });
assert.deepEqual(videoFrame(plan, 149), { fromBeat: 1, beat: 2, time: 1000 });
assert.deepEqual(videoFrame(plan, 239), { fromBeat: 3, beat: 3, time: Infinity });
assert.throws(() => videoFrame(plan, 240));
assert.throws(() => videoOptions({ stepDelayMs: NaN })); assert.throws(() => videoOptions({ fps: 24 as 30 }));
assert.throws(() => videoOptions({ endHoldMs: -1 })); assert.throws(() => videoOptions({ startHoldMs: 60001 }));
assert.deepEqual(videoSize({ width: 640, height: 360 }, 1080), { width: 1920, height: 1080 });
assert.deepEqual(videoSize({ width: 360, height: 640 }, 720), { width: 406, height: 720 });
assert.throws(() => videoSize({ width: Infinity, height: 1 }, 720));
const auto = structuredClone(slide); auto.beats[3].advance = "auto"; auto.beats[3].autoDelayMs = 123;
assert.equal(planSlideVideo(auto, durations).cues[1].start, 2123);
const empty = { ...slide, elements: [], beats: [] };
assert.equal(planSlideVideo(empty, []).frameCount, 180);
const one = planSlideVideo(empty, [], { startHoldMs: 0, endHoldMs: 0 }); assert.equal(one.frameCount, 1); assert.equal(videoFrame(one, 0).time, Infinity);
const tiny = planSlideVideo(slide, [0, 1, 0, 0], { startHoldMs: 0, endHoldMs: 0, stepDelayMs: 0 });
assert.equal(tiny.frameCount, 1); assert.equal(videoFrame(tiny, 0).beat, 3);
assert.throws(() => planSlideVideo(slide, [0, Infinity]));
h.ok(true, "holds, grouped/automatic steps, exact endpoints, resolution and invalid settings");
await h.done();
