import './lib/cssStub.mjs';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { validatedModelBytes } from '../src/lib/model3d/portableBytes';
import { boundedModelFile } from '../flux-core/model3dFile';
import { becomeTransform } from '../src/lib/slide/ops';
import { staticModelElement, staticModelContext } from '../src/lib/slide/staticModels';
import { model3dStaticSvg } from '../src/lib/model3d/static';
import { harness } from './lib/harness.mjs';
import { gatherPayload, portablePayload } from '../src/lib/slide/payload';
import { exportDeckHtml, exportSlideVideoHtml } from '../src/lib/slide/export/exportDeck';
import { makeModel3dElement } from '../src/lib/model3d/make';
import { inspectGlb, writeGlb, GLB_LIMITS } from '../src/lib/model3d/glbCore.mjs';
import { createHash } from 'node:crypto';
import type { Model3dAsset } from '../src/lib/model3d/types';
import type { Deck } from '../src/lib/slide/types';
import { deckPdfDocument } from '../src/lib/slide/export/deckPdf';
import { deckPptxBytes } from '../src/lib/slide/export/deckPptx';
import { renderSlidePosterSvg, compileSlideFor } from '../src/lib/slide/embedRender';
import { unzipSync, strFromU8 } from 'fflate';
import { parseHTML } from 'linkedom';
import { Resvg } from '@resvg/resvg-js';
import { payloadModelContext } from '../src/lib/slide/export/model3dPayloadHost';
const h=harness('verify-model3d-slide-export');
const bytes=writeGlb({parts:[{name:'mesh',positions:[0,0,0,1,0,0,0,1,1],indices:[0,1,2]}]});
const asset:Model3dAsset={id:'mesh',name:'Mesh',kind:'glb',path:'assets/mesh.glb',naturalWidth:200,naturalHeight:200,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,model:inspectGlb(bytes)};
const element=makeModel3dElement(asset,{id:'view'});
const scene={build:{provenance:{path:'/private/source.py'}},spec:'fluxplot/scene3d',schemaVersion:'0.1.0',glb:'secret.glb',parts:[{id:'mesh',role:'mesh',node:'mesh'},{id:'title',role:'title',text:'Model title'}]};
const deck={schemaVersion:'0.6.0',id:'deck',title:'Models',stage:{width:640,height:360},assets:[asset,{...asset,id:'target',path:'assets/target.glb'}],slides:[{id:'slide',elements:[element],beats:[{id:'base',tracks:[]},{id:'change',tracks:[{id:'content',target:'view',preset:'transform',to:{assetId:'target'}}]}]}]} as unknown as Deck;
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';
let reads=0;
const io={readText:async(p:string)=>{if(p.endsWith('project.json'))return '{}';if(p.endsWith('.fluxplot.json'))return JSON.stringify(scene);throw Error('missing');},readFile:async(p:string)=>{if(!p.endsWith('.glb'))throw Error('unexpectedimage');reads++;return bytes;},modelPoster:async()=>png};
const {payload,warnings}=await gatherPayload('/scratch',deck,io);
h.eq(warnings,[],'models and design posters gather without plot warnings');
h.eq(Object.keys(payload.models??{}).sort(),['mesh','target'],'content-only model assets travel with the deck');
h.ok(!payload.assets?.mesh&&!payload.assets?.target,'GLBs never enter the image assets map');
h.eq(payload.assets?.[payload.modelPosters!.view],png,'design poster has a distinct image reference');
h.eq(reads,2,'each referenced GLB read once');
h.eq(payload.deck.assets[0].model,asset.model,'portable deck preserves model metadata');
h.eq(portablePayload(payload).modelManifests!.mesh.glb,'model.glb','portable model metadata scrubs source filename');
h.ok(!payload.modelManifests!.mesh.build && payload.modelManifests!.mesh.glb==='model.glb','public gathering itself removes private manifest build/name');
const privatePayload=structuredClone(payload);privatePayload.deck.slides[0].beats[1].tracks[0].to={assetId:'target',glbPath:'/private/source.glb',sha256:'0'.repeat(64),state:{source:{glbPath:'/private/nested.glb'}}};
const scrubbed=portablePayload(privatePayload);h.ok(!JSON.stringify(scrubbed).includes('/private/'),'portable direct and nested GLB source paths are removed');
h.eq(scrubbed.deck.assets[0].sha256,asset.sha256,'source scrub preserves the prepared asset digest');
h.eq(await validatedModelBytes(bytes,asset),bytes,'prepared byte validation preserves exact accepted bytes');
await assert.rejects(()=>validatedModelBytes(bytes,{...asset,sha256:''}),/prepared-byte/);h.ok(true,'portable bytes require a saved prepared receipt');
const changed=bytes.slice();changed[changed.length-1]^=1;
await assert.rejects(()=>gatherPayload('/scratch',deck,{...io,readFile:async()=>changed}),/prepared bytes.*SHA-256/);h.ok(true,'changed stored bytes refuse public export instead of carrying mismatched metadata');
const scratch=await fs.mkdtemp(path.join(os.tmpdir(),'flux-portable-model-'));
try {
 const root=path.join(scratch,'project'),dir=path.join(root,'slides/deck/assets');await fs.mkdir(dir,{recursive:true});
 await fs.writeFile(path.join(dir,'mesh.glb'),bytes);await fs.writeFile(path.join(dir,'target.glb'),bytes);
 let bounded=0;const boundedIO={...io,readFile:async()=>{throw Error('unbounded GLB read forbidden');},readModelFile:async(file:string,capturedRoot:string)=>{h.eq(capturedRoot,root,'bounded reader receives captured root');bounded++;return boundedModelFile(file,GLB_LIMITS.maxBytes,capturedRoot);}};
 await gatherPayload(root,deck,boundedIO);h.eq(bounded,2,'public portable gather uses bounded reader for every referenced model');
 const outside=path.join(scratch,'outside.glb');await fs.writeFile(outside,bytes);await fs.rm(path.join(dir,'mesh.glb'));await fs.symlink(outside,path.join(dir,'mesh.glb'));
 await assert.rejects(()=>gatherPayload(root,deck,boundedIO),/escapes|outside|symlink/i);h.ok(true,'portable read refuses a saved-path symlink outside the project');
 await fs.rm(path.join(dir,'mesh.glb'));await fs.writeFile(path.join(dir,'mesh.glb'),'');await fs.truncate(path.join(dir,'mesh.glb'),GLB_LIMITS.maxBytes+1);
 await assert.rejects(()=>gatherPayload(root,deck,boundedIO),/exceeds|limit/i);h.ok(true,'actual sparse oversized stored file refuses before allocation');
} finally {await fs.rm(scratch,{recursive:true,force:true});}
reads=0;await gatherPayload('/scratch',deck,{...io,modelData:'omit'});h.eq(reads,0,'static PDF/PPTX gathering never reads GLB bytes');
const exported=await exportDeckHtml(payload,{warnThreshold:1});
h.ok(exported.html.includes('var FluxModel3dRuntime='),'3D deck includes the conditional runtime');
h.ok(exported.warnings.some(w=>w.includes('max_faces=')),'large 3D deck gives model-specific size guidance');
const runtimeScripts=[...exported.html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
for(const script of runtimeScripts)h.ok(exported.html.includes(`sha256-${createHash('sha256').update(script).digest('base64')}`),'every executable script is covered by CSP');
const plain=await exportDeckHtml({deck:{...deck,assets:[],slides:[{...deck.slides[0],elements:[],beats:[]}]}});
h.ok(!plain.html.includes('var FluxModel3dRuntime='),'2D deck does not include Three/model runtime');
const capture=await exportSlideVideoHtml(payload);
h.ok(capture.includes('var FluxModel3dRuntime='),'video capture includes the model runtime');
const dom=parseHTML('<html><body></body></html>');Object.assign(globalThis,{document:dom.document,DOMParser:dom.DOMParser,XMLSerializer:dom.XMLSerializer});
const sample=payloadModelContext(payload);
h.eq(sample.modelPoster(element),png,'matching sampled view finds its exact Design poster');
h.eq(sample.modelPoster({...element,orbitAzimuth:element.orbitAzimuth+90}),undefined,'changed orbit never reuses the Design poster as a matching current frame');
const posterSvg=renderSlidePosterSvg(payload);
h.ok(posterSvg.includes('data-model3d-poster="true"')&&!posterSvg.includes('data:model/gltf-binary'),'shared static PDF/document SVG composes the model PNG');
let composed='';
const pptx=await deckPptxBytes('Model',[{payload}],async(svg)=>{composed=svg;return new Resvg(svg).render().asPng();},undefined,'final');
const archive=unzipSync(pptx.bytes);
h.ok(Object.keys(archive).some(p=>/^ppt\/media\/.*\.png$/.test(p)),'PPTX contains an actual rasterized model image');
h.ok(pptx.warnings.some(w=>w.includes('3D animation exported as a still')),'PPTX explicitly reports its 3D still policy');
h.ok(composed.includes('data-model3d-poster="true"'),'PPTX rasterization receives the shared mesh/furniture composition');
h.ok(!Object.keys(archive).some(p=>p.endsWith('.glb')),'PPTX contains no falsely editable 3D model payload');
h.ok(Object.entries(archive).filter(([p])=>/^ppt\/slides\/slide\d+\.xml$/.test(p)).some(([,v])=>strFromU8(v).includes('<p:pic>')),'PowerPoint slide references the model picture');
// Initially non-model identities have no Design model poster. Their first and
// later model endpoints require matching stills in every static writer.
const retyped=structuredClone(deck);retyped.slides[0].beats=[{id:'base',tracks:[]},{id:'become',tracks:[]}];
retyped.slides[0].elements=[{id:'R',type:'rect',x:10,y:20,width:200,height:160,rotation:0,fill:'#ccc',stroke:'none',strokeWidth:0,cornerRadius:0},{...element,id:'B',orbitAzimuth:117,overrides:{title:{text:'Endpoint title'}}}] as any;
becomeTransform(retyped,'slide','become','R','B',{mode:'consume',modelAsset:id=>retyped.assets.find(a=>a.id===id)});
const requests:any[]=[];
const typed=await gatherPayload('/scratch',retyped,{...io,modelData:'omit',modelPoster:async(request)=>{requests.push(request);return png;}});
h.ok(requests.some(r=>r.element.id==='R'&&r.element.orbitAzimuth===117),'rect-to-model Consume gathers its actual evaluated endpoint still');
const typedSvg=renderSlidePosterSvg(typed.payload,1);h.ok(typedSvg.includes('data-model3d-poster="true"')&&!typedSvg.includes('data-model3d-placeholder'),'rect-to-model SVG final state contains its matching mesh still');
let typedPptxSvg='';await deckPptxBytes('Retyped',[{payload:typed.payload}],async svg=>{typedPptxSvg=svg;return new Resvg(svg).render().asPng();},undefined,'final');
h.ok(typedPptxSvg.includes('data-model3d-poster="true"')&&!typedPptxSvg.includes('data-model3d-placeholder'),'rect-to-model PowerPoint uses the same coherent endpoint still');
const pdf=await deckPdfDocument('/scratch',retyped.id,{...io,readText:async p=>p.endsWith('project.json')?JSON.stringify({schemaVersion:'0.1.0',slides:[{id:retyped.id,path:'slides/deck/deck.json'}]}):p.endsWith('deck.json')?JSON.stringify(retyped):io.readText(p)},'final');
h.ok(pdf.warnings.includes('3D animation exported as a still')&&pdf.html.includes('data-model3d-poster="true"'),'future-only model PDF reports the static policy and includes its endpoint mesh');
const req=requests.find(r=>r.element.id==='R');const expected=model3dStaticSvg(req.element,id=>typed.payload.assets?.[id],staticModelContext(typed.payload));
h.ok(typedSvg.includes(expected)&&typedPptxSvg.includes(expected),'SVG/PPTX share exact endpoint mesh and furniture composition');
const partDeck=structuredClone(deck);partDeck.slides[0].beats=[{id:'base',tracks:[]},{id:'parts',tracks:[{id:'fade-meshes',target:'view',selector:{role:'mesh'},preset:'fadeOut',duration:500},{id:'fade-title',target:'view',part:'title',preset:'fadeOut',duration:500}]}];
const partPayload=(await gatherPayload('/scratch',partDeck,{...io,modelData:'omit'})).payload;
h.eq(compileSlideFor(partPayload).cues[1].tracks[0].parts,['mesh'],'static compilation resolves model role leaves through accepted metadata');
h.eq(renderSlidePosterSvg(partPayload,1),renderSlidePosterSvg(partPayload,0),'static Design still keeps mesh and furniture together despite sampled part fades');
const altered={...element,orbitAzimuth:99,fill:'#ff0000',width:240,height:180,modelStates:{inflated:1}};
const designStill=staticModelElement(altered,deck.slides[0]) as typeof element;
h.eq([designStill.orbitAzimuth,designStill.fill,designStill.modelStates,designStill.width],[element.orbitAzimuth,element.fill,element.modelStates,240],'original model keeps Design mesh/furniture appearance with sampled placement');
await h.done();
