#!/usr/bin/env -S npx tsx
// Colour-system plan B1 (Flux half) — a placed plot follows the deck theme:
//   • `applyPlotTheme` maps fluxplot's ink tokens (data-ink-fill / data-ink-stroke) onto the deck
//     theme: a use_light plot on flux-dark paints its tick labels, titles and spines in the deck's
//     text / muted colours, its backgrounds transparent, its gridlines a 15 % text-into-bg mix;
//   • data colours are never touched (the series line keeps its generated stroke);
//   • an explicit per-part override applied afterwards still wins;
//   • the same theme twice writes nothing; restoring (or a null theme) puts the generated bytes back;
//   • the when-rule: `followTheme` absent means on for slides, off in Paper / Figure; the op
//     `setPlotFollowTheme` writes / clears the flag and the project schema accepts it.
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseHTML } from 'linkedom';
import { harness } from './lib/harness.mjs';
import { applyPlotTheme, restorePlotTheme, plotFollowsTheme, themeInkPaints, mixHex, GRID_MIX } from '../src/lib/plot/themeDom';
import { applyOverrides } from '../src/lib/plot/parse';
import { setPlotFollowTheme } from '../src/lib/ops';
import { FLUX_DARK, FLUX_LIGHT, FLUX_SEPIA } from '../src/lib/slide/theme';
import { SCHEMAS } from '../src/lib/project/schemas';
import type { FluxPlotManifest } from '../src/lib/plot/types';
import type { Project, SemanticPlotElement } from '../src/lib/types';

const h = harness('verify-plot-theme');
const repo = resolve(import.meta.dirname, '..'), fixtures = join(repo, 'scripts/fixtures/fluxplot03');
const { document } = parseHTML('<html><body></body></html>');
const svgText = readFileSync(join(fixtures, 'panels-a.svg'), 'utf8');
const manifest = JSON.parse(readFileSync(join(fixtures, 'panels-a.fluxplot.json'), 'utf8')) as FluxPlotManifest;
const mount = (): Element => { const wrap = document.createElement('div'); wrap.innerHTML = svgText; return wrap as unknown as Element; };
const style = (n: Element) => (n as unknown as { style: { getPropertyValue(p: string): string } }).style;
const paintOf = (n: Element, prop: 'fill' | 'stroke') => (style(n).getPropertyValue(prop) || n.getAttribute(prop) || (prop === 'fill' ? '#000000' : 'none')).trim().toLowerCase();
const leaves = (root: Element, id: string) => Array.from(root.querySelectorAll(`[id="${id}"] path, [id="${id}"] text, [id="${id}"] rect, [id="${id}"] use`));
// normalised style declarations: linkedom re-serialises a touched style attribute without spaces
const decls = (n: Element) => (n.getAttribute('style') ?? '').split(';').map(d => d.replace(/\s+/g, '')).filter(Boolean).sort().join(';');
const snapshot = (root: Element) => Array.from(root.querySelectorAll('*')).map(n => [n.getAttribute('id'), decls(n)].join('|'));

try {
  h.ok(manifest.style?.tokens?.ink === '#000000', 'the fixture is a use_light plot (black ink tokens)');
  const taggedFill = mount().querySelectorAll('[data-ink-fill]').length, taggedStroke = mount().querySelectorAll('[data-ink-stroke]').length;
  h.ok(taggedFill > 10 && taggedStroke > 5, `the fixture carries ink tags (${taggedFill} fill, ${taggedStroke} stroke)`);

  // 1. the mapping
  const dark = themeInkPaints(FLUX_DARK);
  h.eq(dark.ink, FLUX_DARK.text, 'ink → the deck text colour');
  h.eq(dark.label, FLUX_DARK.text, 'label → the deck text colour');
  h.eq(dark.tick, FLUX_DARK.text, 'tick → the deck text colour');
  h.eq(dark.axis, FLUX_DARK.textMuted, 'axis → the deck muted text');
  h.eq(dark.grid, mixHex(FLUX_DARK.background, FLUX_DARK.text, GRID_MIX), 'grid → 15 % of text mixed into the background');
  h.eq(mixHex('#000000', '#ffffff', 0.5), '#808080', 'mixHex mixes in sRGB');
  h.eq(dark.plot, 'none', 'plot background → transparent');
  h.eq(dark.paper, 'none', 'paper background → transparent');

  // 2. a use_light plot on flux-dark
  const root = mount();
  const pristine = snapshot(root);
  const lineBefore = leaves(root, 'panel.small.control.line').map(n => paintOf(n, 'stroke'));
  const res = applyPlotTheme(root, manifest, FLUX_DARK);
  h.ok(res.painted > 20, `${res.painted} scaffold drawables repainted`);
  const tickLabel = leaves(root, 'panel.small.axis.x.ticklabel.1');
  h.ok(tickLabel.length > 0 && tickLabel.every(n => paintOf(n, 'fill') === FLUX_DARK.text), 'tick-label fill equals the deck text colour');
  const title = Array.from(root.querySelectorAll('[data-role="axis-title"]')).flatMap(n => Array.from(n.querySelectorAll('path, text')));
  h.ok(title.length === 0 || title.every(n => paintOf(n, 'fill') === FLUX_DARK.text), 'axis titles take the deck text colour');
  const spine = leaves(root, 'panel.small.axis.x.spine.bottom');
  h.ok(spine.length > 0 && spine.every(n => paintOf(n, 'stroke') === FLUX_DARK.textMuted), 'spines take the muted text colour');
  const ticks = leaves(root, 'panel.small.axis.x.tick.1');
  h.ok(ticks.length > 0 && ticks.every(n => paintOf(n, 'stroke') === FLUX_DARK.text), 'tick marks take the deck text colour');
  h.ok(spine.every(n => paintOf(n, 'fill') === 'none'), 'a spine painted fill:none stays unfilled (only declared paints are followed)');
  const bg = [...leaves(root, 'panel.small.axes.background'), ...leaves(root, 'panel.small.figure.background')];
  h.ok(bg.length > 0 && bg.every(n => paintOf(n, 'fill') === 'none'), 'axes and figure backgrounds become transparent');
  h.eq(leaves(root, 'panel.small.control.line').map(n => paintOf(n, 'stroke')), lineBefore, 'the data line colour is unchanged');
  h.ok(lineBefore.every(c => c !== FLUX_DARK.text), '(and it was never the ink colour to begin with)');

  // 3. idempotent, overrides win, restore
  const after = snapshot(root);
  const again = applyPlotTheme(root, manifest, FLUX_DARK);
  h.eq(snapshot(root), after, 'the same theme twice changes nothing');
  h.eq(again.painted, res.painted, 'and reports the same paint count');
  applyOverrides(root, { 'axis.x.ticklabel.1': { fill: '#ff0000' } }, 'plot', manifest);
  const overridden = Array.from(root.querySelectorAll('[id="panel.small.axis.x.ticklabel.1"]'));
  h.ok(overridden.length > 0, 'the override targeted the tick label');
  const swapped = applyPlotTheme(root, manifest, FLUX_SEPIA);
  h.ok(tickLabel.every(n => paintOf(n, 'fill') === FLUX_SEPIA.text), 'switching decks repaints in the new theme’s ink');
  h.ok(swapped.painted > 0, 'the swap repainted');
  restorePlotTheme(root);
  h.eq(snapshot(mount()), pristine, 'a fresh mount is pristine (sanity)');
  const restored = mount();
  applyPlotTheme(restored, manifest, FLUX_DARK);
  applyPlotTheme(restored, manifest, null);
  h.eq(snapshot(restored), pristine, 'a null theme restores the generated bytes exactly');
  const idOnly = mount();
  applyPlotTheme(idOnly, manifest, 'flux-dark' as unknown as typeof FLUX_DARK);
  h.eq(snapshot(idOnly), pristine, 'a theme ID string (an unresolved theme) paints nothing and restores');
  const light = mount();
  applyPlotTheme(light, manifest, FLUX_LIGHT);
  h.ok(leaves(light, 'panel.small.axis.x.ticklabel.1').every(n => paintOf(n, 'fill') === FLUX_LIGHT.text), 'a light deck paints black ink');

  // 4. when a plot follows
  const el = { followTheme: undefined } as Pick<SemanticPlotElement, 'followTheme'>;
  h.eq(plotFollowsTheme(el, 'slide'), true, 'absent followTheme: on for slides');
  h.eq(plotFollowsTheme(el, 'figure'), false, 'absent followTheme: off in Figure');
  h.eq(plotFollowsTheme(el, 'paper'), false, 'absent followTheme: off in Paper');
  h.eq(plotFollowsTheme({ followTheme: false }, 'slide'), false, 'followTheme:false opts a slide plot out');
  h.eq(plotFollowsTheme({ followTheme: true }, 'figure'), true, 'followTheme:true opts a figure plot in');
  h.eq(plotFollowsTheme(undefined, 'slide'), false, 'no element, no theme');
  const plot = { id: 'p1', type: 'plot', assetId: 'a', x: 0, y: 0, width: 10, height: 10 } as unknown as SemanticPlotElement;
  const project = { figures: [{ id: 'f', elements: [plot] }] } as unknown as Project;
  setPlotFollowTheme(project, 'p1', false);
  h.eq(plot.followTheme, false, 'setPlotFollowTheme writes the flag');
  setPlotFollowTheme(project, 'p1', null);
  h.ok(!('followTheme' in plot), 'null clears it (the host default returns; untouched files stay byte-identical)');
  const withElements = Object.entries(SCHEMAS).filter(([, sch]) => !!(sch as { definitions?: Record<string, unknown> }).definitions?.element);
  h.ok(withElements.length > 0, `schemas with an element definition: ${withElements.map(([k]) => k).join(', ')}`);
  for (const [name, sch] of withElements) {
    const branch = ((sch as { definitions: Record<string, { oneOf?: { properties: Record<string, unknown> }[] }> }).definitions.element.oneOf ?? [])
      .find(b => (b.properties.type as { const?: string })?.const === 'plot');
    h.ok(!!branch && 'followTheme' in branch.properties, `${name}: the plot element branch declares followTheme`);
  }
} catch (e) { h.fail(e instanceof Error ? e.stack ?? e.message : String(e)); }
await h.done();
