// Colour-law parity with fluxplot (colour-system plan A7.1): every vector in
// scripts/fixtures/colorscale_vectors.json — generated by fluxplot's
// tests/generate_colorscale_vectors.py from matplotlib 3.11's own ScalarMappable.to_rgba,
// copied here from fluxplot commit f5e44a41 (regenerate both when matplotlib is upgraded) —
// must colour hex for hex through src/lib/plot/colorscale.ts.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { colorFor, effectiveScale, normalize, lookup, parseHex, rgbaHex, viewIsIdentity } from "../src/lib/plot/colorscale";
import type { FluxPlotColorScale } from "../src/lib/plot/types";

const doc = JSON.parse(await readFile(new URL("./fixtures/colorscale_vectors.json", import.meta.url), "utf8")) as {
  spec: string; matplotlib: string; cases: { name: string; record: FluxPlotColorScale; values: (number | null)[]; expected: string[] }[];
};
assert.equal(doc.spec, "fluxplot/colorscale-vectors");
assert.ok(doc.cases.length >= 20, "the fixture carries the norm × colormap matrix");
let checked = 0;
const kinds = new Set<string>();
for (const c of doc.cases) {
  kinds.add(c.record.norm.kind);
  c.values.forEach((v, i) => {
    const got = colorFor(c.record, v == null ? NaN : v);
    assert.equal(got, c.expected[i], `${c.name}[${i}] value ${v}: ${got} vs ${c.expected[i]}`);
    checked++;
  });
}
for (const k of ["linear", "log", "symlog", "power", "twoslope", "centered", "boundary"]) assert.ok(kinds.has(k), `fixture covers ${k}`);

// the lookup rule's corners, independent of any fixture
const cm = doc.cases[0].record.colormap;
assert.equal(lookup(cm, 1), cm.lut[cm.N - 1], "x == 1 is the last entry");
assert.equal(lookup(cm, 1 + 1e-12), cm.over, "just above 1 is over");
assert.equal(lookup(cm, -1e-12), cm.under, "just below 0 is under");
assert.equal(lookup(cm, Infinity), cm.over, "+Infinity is over, not bad");
assert.equal(lookup(cm, -Infinity), cm.under, "−Infinity is under, not bad");
assert.equal(lookup(cm, NaN), cm.bad, "NaN is bad");
assert.equal(lookup(cm, -1, true), cm.under, "boundary index −1 is under");
assert.equal(lookup(cm, cm.N, true), cm.over, "boundary index N is over");
assert.equal(normalize({ kind: "twoslope", vmin: 0, vmax: 10, vcenter: 3, clip: false, extend: "neither" }, 11), Infinity);
assert.equal(rgbaHex(parseHex("#4c78a8")!), "#4c78a8ff");
assert.equal(rgbaHex(parseHex("#4c78a880")!), "#4c78a880");

// a view over a scale: limits, a kind switch, a reversed table, validation
const base = doc.cases.find((c) => c.name === "linear/viridis")!.record;
const limits = effectiveScale(base, { norm: { vmin: 2, vmax: 4 } });
assert.deepEqual([limits.norm.vmin, limits.norm.vmax, limits.norm.kind], [2, 4, "linear"]);
assert.equal(colorFor(limits, 3), base.colormap.lut[128], "the new midpoint is the middle of the table");
const log = effectiveScale(base, { norm: { kind: "log", vmin: 1, vmax: 100 } });
assert.equal(log.norm.kind, "log"); assert.equal(log.norm.base, 10); assert.deepEqual(log.issues, []);
assert.equal(colorFor(log, 10), base.colormap.lut[128], "a decade in is halfway on a log scale");
const bad = effectiveScale(base, { norm: { kind: "log", vmin: 0, vmax: 5 } });
assert.equal(bad.norm.kind, "linear", "an invalid switch leaves the generated norm");
assert.match(bad.issues[0], /above 0/);
const rev = effectiveScale(base, { reversed: true });
assert.equal(rev.colormap.lut[0], base.colormap.lut[base.colormap.N - 1]);
assert.equal(rev.colormap.under, base.colormap.over);
const table = effectiveScale(base, { cmap: { lut: ["#ff0000", "#00ff00"] } });
assert.deepEqual([table.colormap.N, table.colormap.lut, table.colormap.under, table.colormap.over, table.colormap.bad],
  [2, ["#ff0000ff", "#00ff00ff"], "#ff0000ff", "#00ff00ff", "#00000000"]);
const named = effectiveScale(base, { cmap: "magma" }, (name) => name === "magma" ? { lut: ["#000004", "#fcfdbf"] } : null);
assert.equal(named.colormap.name, "magma"); assert.equal(named.colormap.N, 2);
assert.equal(effectiveScale(base, { cmap: "nope" }).unresolved, "nope", "an unknown name is reported, not guessed");
assert.ok(viewIsIdentity(base, { norm: { vmin: base.norm.vmin!, kind: "linear" }, cmap: base.colormap.name }), "restating defaults is the identity");
assert.ok(!viewIsIdentity(base, { reversed: true }));
console.log(`verify-colorscale-parity: ${checked} vectors across ${doc.cases.length} cases (matplotlib ${doc.matplotlib}) PASS`);
