import assert from "node:assert/strict";
import { createDeck, addVideoToSlide, addBeat, setVideoTrack, setVideoSettings, setAnimation, setTransform, duplicateSlide, insertSlideSnapshot, addGhostTransform, cascadeTracks } from "../src/lib/slide/ops";
import { compileSlide } from "../src/lib/slide/compile";
import { deckToProject, projectIntoDeck, slideAssetIds } from "../src/lib/slide/deckProject";
import { validateDeckFile, validateModel } from "../src/lib/project/validate";
import { planFigSave } from "../src/lib/project/figfiles";
import { makeVideoElement } from "../src/lib/slide/mediaTypes";
import { applyState, diffState } from "../src/lib/slide/tween";
import { gatherPayload, gatherSlidePayload } from "../src/lib/slide/payload";
import { elementToSvg } from "../src/lib/export";
import { makeAnimPreset, parseAnimPreset } from "../src/lib/slide/animTemplates";
import { harness } from "./lib/harness.mjs";
const h = harness("verify-slide-video-model");
const deck = createDeck({ id: "videos" }), slide = deck.slides[0];
slide.elements = [];
deck.assets = [
  { id: "clip", name: "experiment.mov", kind: "mp4", path: "assets/clip.mp4", naturalWidth: 1920, naturalHeight: 1080, durationMs: 2000, hasAudio: true, sourcePath: "plots/_videos/experiment.mov" },
  { id: "poster", name: "poster", kind: "png", path: "assets/poster.png", naturalWidth: 480, naturalHeight: 270 },
];
const id = addVideoToSlide(deck, slide.id, { assetId: "clip", posterAssetId: "poster", durationMs: 2000 })!;
const video = slide.elements.find(e => e.id === id)!;
assert.equal(video.type, "video"); assert.equal(video.width / video.height, 16 / 9);
assert.equal(video.width, deck.stage.width * .8); assert.equal(video.name, "experiment");
assert.deepEqual(validateDeckFile(deck), []);
const projection = deckToProject(deck, deck.assets);
assert.deepEqual(projectIntoDeck(projection, deck), deck);
assert.ok(validateModel(projection).length > 0, "canonical Figure validator excludes slide video");
assert.throws(() => planFigSave(projection, null), /Video clips belong/);
const bad = structuredClone(deck); delete (bad.slides[0].elements[0] as any).posterAssetId;
assert.ok(validateDeckFile(bad).length); (bad.slides[0].elements[0] as any).posterAssetId = "";
assert.ok(validateDeckFile(bad).length);
assert.throws(() => makeVideoElement(deck.assets[0], "poster", deck.stage, { width: -1 }));
h.ok(true, "video schema, fit, canonical Figure boundary and lossless editor projection");
const appear = addBeat(deck, slide.id, { label: "Show" })!, play = addBeat(deck, slide.id, { label: "Play" })!;
setAnimation(deck, slide.id, appear.id, { target: id, preset: "fade", duration: 300 });
setVideoTrack(deck, slide.id, play.id, id, "start", { start: 120 });
setTransform(deck, slide.id, play.id, id, { state: { x: 100 }, duration: 700 });
setAnimation(deck, slide.id, play.id, { target: id, preset: "highlight", duration: 200 });
assert.equal(play.tracks.length, 3);
const commandId = play.tracks.find(t => t.preset === "videoStart")!.id;
assert.ok(setVideoTrack(deck, slide.id, play.id, id, "pause"));
assert.equal(play.tracks.length, 3); assert.equal(play.tracks.find(t => t.preset === "videoPause")!.id, commandId);
setVideoTrack(deck, slide.id, play.id, id, "start", { start: 120 });
const compiled = compileSlide(slide, deck.stage);
assert.equal(compiled.cues[2].tracks.find(t => t.track.preset === "videoStart")!.duration, 0);
assert.equal(compiled.sample(0).presentation.elementStates[id].visible, false);
assert.equal(compiled.sample(1).presentation.elementStates[id].visible, true);
assert.equal(compiled.sample(2).elements[0].x, 100);
assert.ok(setVideoSettings(deck, slide.id, id, { muted: true, loop: true }));
const changed = applyState(video, { x: 200, posterAssetId: "wrong", durationMs: 5, muted: false, loop: false });
assert.equal(changed.x, 200); assert.equal((changed as any).posterAssetId, "poster");
assert.equal((changed as any).durationMs, 2000); assert.equal((changed as any).muted, true);
assert.equal(diffState(video, { ...video, muted: false } as any), null);
assert.equal(setVideoTrack(deck, slide.id, play.id, "missing", "start"), false);
assert.equal(setVideoTrack(deck, slide.id, slide.beats[0].id, id, "start"), false);
assert.equal(cascadeTracks(deck, slide.id, [commandId!], { property: "duration", delta: 400 }), 0);
assert.equal(play.tracks.find(t => t.id === commandId)?.duration, 0);
assert.equal(setVideoTrack(deck, slide.id, play.id, id, "start", { start: NaN }), false);
assert.equal(setAnimation(deck, slide.id, play.id, { target: id, preset: "videoStart", part: "plot-part" }), false);
assert.throws(() => addGhostTransform(deck, slide.id, play.id, id), /Duplicate the video/);
assert.equal(parseAnimPreset(makeAnimPreset("Start", { target: id, preset: "videoStart" }))?.family, "media");
h.ok(true, "separate appearance, playback and transform channels; stable command replacement; structural settings");
const cloneId = duplicateSlide(deck, slide.id)!;
const clone = deck.slides.find(s => s.id === cloneId)!;
assert.notEqual(clone.elements[0].id, id);
assert.equal(clone.beats[2].tracks[0].target, clone.elements[0].id);
assert.deepEqual(slideAssetIds(clone), new Set(["clip", "poster"]));
const target = createDeck({ id: "target" });
const inserted = insertSlideSnapshot(target, { fluxPreset: 1, kind: "slide", name: "Movie", savedAt: "", stage: deck.stage,
  slide, assets: deck.assets.map(asset => ({ asset, data: asset.kind === "mp4" ? "data:video/mp4;base64,AA==" : "data:image/png;base64,AA==" })) });
const insertedVideo = target.slides.find(s => s.id === inserted.slideId)!.elements[0] as any;
assert.equal(insertedVideo.assetId, inserted.assetRemap.get("clip"));
assert.equal(insertedVideo.posterAssetId, inserted.assetRemap.get("poster"));
assert.deepEqual(validateDeckFile(target), []);
const svg = elementToSvg(video, aid => aid === "poster" ? "data:image/png;base64,AA==" : undefined);
assert.match(svg, /<image/); assert.doesNotMatch(svg, /video\/mp4/);
h.ok(true, "slide duplication, portable preset remapping and static poster rendering");
let movieReads = 0, streamed = 0;
const io = { readText: async (p: string) => { if (p.endsWith("project.json")) return JSON.stringify({ slides: [{ id: deck.id }] }); throw new Error("missing"); },
  readFile: async (p: string) => { if (p.endsWith(".mp4")) movieReads++; return new Uint8Array([1, 2, 3]); } };
deck.assets.push({ ...deck.assets[0], id: "unplaced-video", path: "assets/deleted.mp4" });
const portable = await gatherPayload("/root", deck, io);
assert.equal(movieReads, 1); assert.equal(portable.payload.videos?.["unplaced-video"], undefined); assert.ok(portable.payload.videos?.clip.startsWith("data:video/mp4"));
assert.ok(portable.payload.assets.poster); assert.equal(portable.payload.assets.clip, undefined);
const native = await gatherSlidePayload("/root", deck, slide.id, { ...io, videoUrl: async (p, asset) => { streamed++; assert.equal(asset.id, "clip"); assert.equal(p, "/root/slides/videos/assets/clip.mp4"); return "flux-media://video/token"; } });
assert.equal(movieReads, 1); assert.equal(streamed, 1);
assert.equal(native.payload.videos?.clip, "flux-media://video/token"); assert.ok(native.payload.assets.poster);
assert.equal(native.payload.deck.assets.find(a => a.id === "clip")?.hasAudio, true);
assert.doesNotMatch(JSON.stringify(native.payload.deck), /sourcePath|plots\/_videos/);
h.ok(true, "portable data and streamed native media share metadata without loading movie bytes into the editor");
await h.done();
