import './lib/cssStub.mjs';
import { harness } from './lib/harness.mjs';
import { resolveDeckAssets } from '../src/lib/project/slideBridge';
import { makeModel3dElement } from '../src/lib/model3d/make';
import { inspectGlb, writeGlb } from '../src/lib/model3d/glbCore.mjs';
import { createHash } from 'node:crypto';
import type { Model3dAsset } from '../src/lib/model3d/types';
import type { FileBridge } from '../src/lib/project/types';
import type { Deck } from '../src/lib/slide/types';
const h = harness('verify-model3d-deck-assets');
const bytes = writeGlb({ parts: [{ name: 'neuron.mesh', positions: [0,0,0,1,0,0,0,1,1], indices: [0,1,2] }] });
const asset: Model3dAsset = { id:'neuron', kind:'glb', name:'Neuron', path:'assets/neuron.glb', naturalWidth:320, naturalHeight:240, sha256:createHash('sha256').update(bytes).digest('hex'), bytes:bytes.length, model:inspectGlb(bytes) };
const el = makeModel3dElement(asset, {id:'neuron-view'});
const manifest = {spec:'fluxplot/scene3d',schemaVersion:'0.1.0',glb:'neuron.glb',parts:[{id:'neuron.mesh',role:'mesh',node:'neuron.mesh'}]};
const files = new Map<string,string>([['/scratch/slides/deck/assets/neuron.glb','binary'],['/scratch/slides/deck/assets/neuron.fluxplot.json',JSON.stringify(manifest)]]);
let binaryReads = 0;
const bridge = { exists:async(p:string)=>files.has(p), readText:async(p:string)=>{if(!files.has(p))throw Error('missing');return files.get(p)!;}, readFile:async()=>{binaryReads++;throw Error('GLB must not enter renderer assetData');} } as unknown as FileBridge;
const deck = {id:'deck',assets:[asset],slides:[{id:'s',elements:[el],beats:[]}]} as unknown as Deck;
const local = await resolveDeckAssets('/scratch', deck, ()=>true, true, bridge);
h.eq(local.data,{},'deck GLB never enters assetData');
h.eq(local.assets,[asset],'deck GLB metadata remains intact');
h.eq(local.diagnostics,[],'valid deck-local model resolves');
const {get}=await import('svelte/store'); const {scene3dManifests,clearScene3dSidecars}=await import('../src/lib/model3d/store');
clearScene3dSidecars();h.eq(get(scene3dManifests),{},'deferred read does not publish metadata');local.publish();h.eq(get(scene3dManifests).neuron,manifest,'owned publication primes scene metadata');
files.set('/scratch/fig/index.json',JSON.stringify({assets:[asset]}));
files.set('/scratch/fig/assets/neuron.glb','binary');files.set('/scratch/fig/assets/neuron.fluxplot.json',JSON.stringify(manifest));
const external = await resolveDeckAssets('/scratch',{...deck,assets:[]},()=>true,true,bridge);
h.eq(external.assets,[{...asset,path:'fig/assets/neuron.glb'}],'figure-derived GLB stays by-id with complete metadata');h.ok(external.external.has(asset.id),'figure-derived model is external');h.eq(external.data,{},'external GLB never becomes image bytes');
files.delete('/scratch/slides/deck/assets/neuron.glb');
const absent=await resolveDeckAssets('/scratch',deck,()=>true,true,bridge);
h.eq(absent.assets,[asset],'missing model retains metadata for a placeholder');h.ok(absent.diagnostics.some(d=>d.assetId===asset.id),'missing model emits named diagnostic');h.eq(binaryReads,0,'all model resolution is metadata-only');
h.done();
