import assert from "node:assert/strict";
import fs from "node:fs";
import {syncBuiltinESMExports} from "node:module";
import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { writePdf, readFulltext, writeFulltext, hasPdf, writeLinkedPdf, pdfBytesIdentity, fileSupplement, readSource } from "../flux-core/items";
import { searchFulltext } from "../flux-core/fulltextSearch";
import { harness } from "./lib/harness.mjs";
const h = harness("verify-item-generations");
const root = await mkdtemp(path.join(tmpdir(), "flux-item-generation-"));
const dir = path.join(root, "items", "paper");
const A = new TextEncoder().encode("%PDF-A scientific source"), B = new TextEncoder().encode("%PDF-B different source");
try {
  await writePdf("paper", A, {source: "ingest"}, root);
  const automated = await writePdf("paper", B, {source:"proxy"}, root);
  h.ok(!automated.ok && automated.reason === "already-present", "automated attach rechecks existing PDF under its item lease");
  h.eq(await readFile(path.join(dir,"paper.pdf")),Buffer.from(A),"late automated capture cannot overwrite manual attachment bytes");
  h.eq((await readSource("paper",root))?.source,"ingest","late automated capture preserves manual provenance");
  const assigned=await writePdf("paper",B,{source:"assigned"},root);
  const zotero=await writePdf("paper",B,{source:"ingest"},root,{ifAbsent:true});
  h.ok(!assigned.ok&&!zotero.ok,"Assign and additive Zotero sync use the same inside-lease absence rule");
  h.eq(await readFile(path.join(dir,"paper.pdf")),Buffer.from(A),"late Assign/Zotero preserve prior PDF bytes");
  await writePdf("paper", B, {source:"proxy"}, root, {replaceExisting:true});
  h.eq(await readFile(path.join(dir,"paper.pdf")),Buffer.from(B),"explicit refresh still authorizes replacement");
  await writePdf("paper", A, {source:"ingest"}, root);
  const originalRm=fs.promises.rm;let revoked=false;
  fs.promises.rm=(async (file: any,...args: any[])=>{
    const result=await (originalRm as any)(file,...args);
    if(file===path.join(dir,"fulltext.source.json")&&!revoked){revoked=true;await originalRm(path.join(root,".fluxlib","locks","item-paper.json"));}
    return result;
  }) as typeof fs.promises.rm;
  syncBuiltinESMExports();
  try {await assert.rejects(()=>writePdf("paper",B,{source:"ingest"},root),/Lost lease/);}
  finally {fs.promises.rm=originalRm;syncBuiltinESMExports();}
  h.ok(revoked,"fixture revokes actual item lease between invalidation and PDF publication");
  h.eq(await readFile(path.join(dir,"paper.pdf")),Buffer.from(A),"revoked PDF writer preserves exact prior scientific PDF bytes");
  h.ok(JSON.parse(await readFile(path.join(dir,"source.pending.json"),"utf8")).source.sha256,"interrupted revoked writer retains its recovery marker");
  await writePdf("paper",A,{source:"ingest"},root);
  await writeFile(path.join(dir, "annotations.json"), '{"notes":"preserve exact user bytes"}');
  h.ok(await writeFulltext("paper", "original scientific text", root, pdfBytesIdentity(A)), "matching PDF generation publishes extracted text");
  await writePdf("paper", B, {source: "ingest"}, root);
  h.eq(await readFulltext("paper", root), null, "PDF replacement cannot return preceding paper text");
  h.eq(await writeFulltext("paper", "late original extraction", root, pdfBytesIdentity(A)), false, "late extraction cannot attach original text to replacement PDF");
  h.eq(await readFile(path.join(dir, "paper.pdf")), Buffer.from(B), "replacement PDF bytes remain exact when stale extraction is refused");
  h.eq(await readFile(path.join(dir, "annotations.json"), "utf8"), '{"notes":"preserve exact user bytes"}', "PDF replacement preserves annotation bytes");
  await writeFulltext("paper", "new scientific generation", root, pdfBytesIdentity(B));
  const beforeSameSize=await fs.promises.stat(path.join(dir,"paper.pdf"));
  const sameSize=Buffer.from(B);sameSize[sameSize.length-1]^=1;
  await writeFile(path.join(dir,"paper.pdf"),sameSize);
  await fs.promises.utimes(path.join(dir,"paper.pdf"),beforeSameSize.atime,beforeSameSize.mtime);
  h.eq(await readFulltext("paper",root),null,"same-size external replacement with restored mtime invalidates derived text through ctime");
  await writeFile(path.join(dir, "paper.pdf"), A);
  h.eq(await readFulltext("paper", root), null, "external in-place PDF replacement invalidates derived text");
  h.eq((await searchFulltext("scientific", {libPath: root})).hits.length, 0, "fulltext index and exact search exclude stale source generations");
  await writePdf("textedited",A,{source:"ingest"},root);
  await writeFulltext("textedited","alpha evidence",root,pdfBytesIdentity(A));
  h.eq((await searchFulltext("alpha",{libPath:root})).hits.map(row=>row.key),["textedited"],"index initially matches original extracted text");
  const textPath=path.join(root,"items","textedited","fulltext.txt"),textStat=await fs.promises.stat(textPath);
  await writeFile(textPath,"bravo evidence");await fs.promises.utimes(textPath,textStat.atime,textStat.mtime);
  h.eq((await searchFulltext("bravo",{libPath:root})).hits.map(row=>row.key),["textedited"],"same-size extracted-text replacement with restored mtime rebuilds candidate postings");
  const target = path.join(root, "external.pdf"); await writeFile(target, A);
  await writeLinkedPdf("linked", target, root);
  await writeFulltext("linked", "linked generation", root, pdfBytesIdentity(A));
  await rm(target);
  h.eq(await hasPdf("linked", root), false, "broken pointer is missing PDF rather than pointer-present success");
  h.eq(await readFulltext("linked", root), null, "broken linked source cannot return previous text");
  const names = await Promise.all([fileSupplement("paper", "same.pdf", A, {}, root), fileSupplement("paper", "same.pdf", B, {}, root)]);
  h.eq(new Set(names).size, 2, "concurrent distinct supplements reserve separate names");
  const manifest = JSON.parse(await readFile(path.join(dir, "supplements", "manifest.json"), "utf8"));
  h.eq(manifest.items.length, 2, "serialized supplement metadata retains both publications");
  h.eq(await fileSupplement("paper", "same.pdf", A, {}, root), names[0], "byte-identical supplement deliberately deduplicates");
  await rm(path.join(dir, "source.json")); await mkdir(path.join(dir, "source.json"));
  await assert.rejects(() => writePdf("paper", B, {source: "ingest"}, root));
  h.eq(await readSource("paper", root), null, "interrupted PDF/provenance publication cannot expose preceding source metadata");
  h.ok(JSON.parse(await readFile(path.join(dir, "source.pending.json"), "utf8")).source.sha256, "interrupted publication retains recovery provenance");
  h.eq(await readFile(path.join(dir, "paper.pdf")), Buffer.from(B), "source metadata failure retains the valid newly written PDF");
} finally { await rm(root, {recursive: true, force: true}); }
await h.done();
