import { harness } from "./lib/harness.mjs";
import { DOMParser, parseHTML } from "linkedom";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { inlineSlideFixture, inlineSlideSvg } from "./fixtures/inline-slide";
import { newSlideEmbed, scanSlideEmbeds, parseSlideEmbed, serializeSlideEmbed, planSlideInsertion } from "../src/lib/slide/embed";
import { gatherSlidePayload, readEmbedDeck, underRoot } from "../src/lib/slide/payload";
import { renderSlidePosterSvg, embedPlayerOptions, namespaceEmbedDeck } from "../src/lib/slide/embedRender";
import { createSlideRepository } from "../src/lib/slide/embedRepository";
import { createPlayer } from "../src/lib/slide/player/player";
import { plotDom, plotManifests } from "../src/lib/plot/store";
import { get } from "svelte/store";
import { prepareSlideDocument } from "../src/lib/slide/embedDocument";
import { slideQuartoTransform } from "../src/lib/slide/embedQuarto";
import { prepareExport } from "../src/lib/exportPrep";
import { readProjectDependencies, slideRemovalBlocker } from "../src/lib/project/dependencies";
import { syncEmbeddedDeckSources } from "../src/lib/slide/embedSources";
import { holdDocumentExport, waitForDocumentExport } from "../src/lib/project/documentExportLease";
import { insertSlideEmbed } from "../flux-core/manuscript";
execFileSync(process.execPath, ["scripts/gen-slide-embed-assets.mjs"], { stdio: "pipe" });
const h = harness("verify-slide-embed-core");
const { document } = parseHTML("<html><body></body></html>");
let frame = 0; const frames = new Map<number, FrameRequestCallback>();
Object.assign(globalThis, { document, DOMParser, requestAnimationFrame: (cb: FrameRequestCallback) => { frames.set(++frame, cb); return frame; }, cancelAnimationFrame: (id: number) => frames.delete(id) });
const root = await fs.mkdtemp(path.join(os.tmpdir(), "flux-inline-slides-"));
const writes: string[] = [];
const io = { readText: (p: string) => fs.readFile(p, "utf8"), readFile: (p: string) => fs.readFile(p), exists: async (p: string) => fs.access(p).then(() => true, () => false),
  mkdir: async (p: string) => { await fs.mkdir(p, { recursive: true }); }, writeText: async (p: string, text: string) => { writes.push(p); await fs.mkdir(path.dirname(p), { recursive: true }); await fs.writeFile(p, text); },
  readdir: async (p: string) => (await fs.readdir(p, { withFileTypes: true })).map(e => ({ name: e.name, dir: e.isDirectory() })) };
const reject = async (fn: () => unknown, pattern: RegExp, label: string) => { try { await fn(); h.fail(label); } catch (e) { h.ok(pattern.test(String(e)), label); } };
try {
  const ref = newSlideEmbed("paper/nested/report.qmd", "talk", "results", { caption: "Evidence [a] and \\path", width: "75%", id: "slide-one" });
  const line = serializeSlideEmbed(ref);
  h.eq(parseSlideEmbed(line), ref, "caption, IDs, width round-trip");
  h.eq(ref.path, "../../slides/talk/renders/results-step-0.svg", "nested poster path");
  const reordered = parseSlideEmbed('![Caption](old.svg){width="60%" slide="results" .flux-slide .wide deck="talk" #slide-a data-label="Some words"}');
  h.ok(reordered?.width === "60%" && serializeSlideEmbed(reordered).includes('data-label="Some words"'), "attribute order, quoted values and extra attributes survive");
  const code = `---\ntitle: x\n${line}\n---\n\n\x60\x60\x60md\n${line}\n\x60\x60\x60\n<!--\n${line}\n-->\n$$\n${line}\n$$\n    ${line}\n\n${line}\n`;
  h.eq(scanSlideEmbeds(code).length, 1, "ignore YAML, fenced/indented code, comments and math");
  const edit = planSlideInsertion("Alpha\nBeta", 2, line); h.eq("Alpha\nBeta".slice(0, edit.from) + edit.insert + "Alpha\nBeta".slice(edit.to), `Alpha\n\n${line}\nBeta`, "insert one standalone block after current line");
  await reject(() => newSlideEmbed("paper/x.qmd", "../escape", "results"), /Invalid/, "unsafe source identity refused");
  await reject(() => underRoot(root, "../../escape"), /escapes/, "source paths stay within project");
  const deck = inlineSlideFixture(); const before = JSON.stringify(deck);
  await io.writeText(`${root}/project.json`, JSON.stringify({ schemaVersion: "0.1.0", id: "embed-test", figures: [], title: "Embed test", documentRoot: "paper", manuscript: { path: "paper/main.qmd", config: "paper/_quarto.yml", format: "quarto" }, supplementary: [], slides: [{ id: "talk", path: "slides/talk/deck.json" }], references: { library: "references/library.bib" } }));
  await io.writeText(`${root}/slides/talk/deck.json`, before);
  await io.writeText(`${root}/slides/talk/assets/shared.svg`, inlineSlideSvg());
  await io.writeText(`${root}/fig/index.json`, JSON.stringify({ schemaVersion: "0.1.0", assets: [], canvases: [], figures: [] }));
  const globalBefore = [...plotDom.entries()], manifestsBefore = JSON.stringify(get(plotManifests));
  const { payload, warnings } = await gatherSlidePayload(root, await readEmbedDeck(root, "talk", io), "results", io);
  h.eq(warnings, [], "scoped slide gathers without missing assets");
  h.eq(payload.deck.slides.length, 1, "only chosen slide exported");
  h.ok(!JSON.stringify(payload).includes("PRIVATE") && !JSON.stringify(payload).includes("/home/") && !JSON.stringify(payload).includes("svgPath"), "notes and source paths excluded");
  h.eq(JSON.stringify(deck), before, "payload gathering never mutates authored deck");
  const a = document.createElement("div") as unknown as HTMLElement, b = document.createElement("div") as unknown as HTMLElement;
  const p1 = createPlayer(a, namespaceEmbedDeck(payload.deck, "one"), embedPlayerOptions(payload));
  const p2 = createPlayer(b, namespaceEmbedDeck(payload.deck, "two"), embedPlayerOptions(payload));
  h.ok(p1.state().beat === 0 && !p1.state().playing && frames.size === 0, "step 0 is settled and schedules no autoplay");
  p1.next(); h.ok(p1.state().beat === 1 && p1.state().playing && p2.state().beat === 0, "one click advances one beat independently");
  p1.next(); h.ok(p1.state().beat === 1 && !p1.state().playing, "mid-animation click finishes current beat");
  p1.next(); p1.next(); p1.next(); h.ok(p1.state().beat === 2 && p1.state().slide === 0 && !p1.state().playing, "with-prev beat is manual and final step stops");
  p1.prev(); h.eq(p1.state().beat, 1, "Back moves one beat"); p1.goTo(0, 0);
  const idsA = new Set(Array.from(a.querySelectorAll("[id]")).map(n => n.id));
  h.ok(Array.from(b.querySelectorAll("[id]")).every(n => !idsA.has(n.id)), "element, part and clip IDs isolated per occurrence");
  h.eq([...plotDom.entries()], globalBefore, "player does not write global plot DOM cache");
  h.eq(JSON.stringify(get(plotManifests)), manifestsBefore, "player does not write global manifest cache");
  p1.destroy(); p2.destroy(); h.eq(frames.size, 0, "destroy cancels every animation frame");
  const zero = renderSlidePosterSvg(payload), final = renderSlidePosterSvg(payload, 2);
  h.ok(zero !== final && zero.includes('opacity:0') && final.includes('opacity:1'), "SVG poster evaluates part visibility at each endpoint");
  const repo = createSlideRepository(root, io); const snap = await repo.materialize(ref); const count = writes.length;
  await repo.materialize(ref); h.eq(writes.length, count, "identical poster materialization does not rewrite");
  h.ok(snap.poster.includes("@font-face"), "static poster embeds its font for offline PDF/Word fidelity");
  repo.invalidate(); h.ok(await repo.load(ref) === snap, "unchanged source revision reuses the immutable payload");
  const rendered = await prepareSlideDocument(`${line}\n\n${line}`, repo, { interactive: true, strict: true });
  const data = JSON.parse(/<script type="application\/json" id="flux-slide-data">(.*?)<\/script>/s.exec(rendered.tail)![1]);
  h.ok(data.occurrences.length === 2 && data.occurrences[0].id !== data.occurrences[1].id && Object.keys(data.payloads).length === 1, "HTML deduplicates payloads and separates duplicate anchors");
  const staticDoc = await prepareSlideDocument(line, repo, { interactive: false, strict: true });
  h.ok(!staticDoc.tail && staticDoc.blocks[0].html.includes("Step 0") && !staticDoc.blocks[0].html.includes("flux-slide-live"), "static export needs no JavaScript and starts at zero");
  const main = `${root}/paper/main.qmd`, include = `${root}/paper/nested/detail.qmd`;
  await io.writeText(main, `# Notes\n\n${line}\n\n{{< include nested/detail.qmd >}}\n`); await io.writeText(include, line);
  const mainBefore = await io.readText(main), includeBefore = await io.readText(include);
  const prep = await prepareExport(io, { entry: main, ctx: { captions: new Map(), figures: new Map() }, ...slideQuartoTransform(root, repo, true) });
  h.ok((await io.readText(main)).includes("flux-slide-data") && !(await io.readText(include)).includes("flux-slide-data"), "one HTML runtime and payload bundle across include tree");
  await prep.restore(); h.ok(await io.readText(main) === mainBefore && await io.readText(include) === includeBefore, "export restores every source byte");
  const prep2 = await prepareExport(io, { entry: main, ctx: { captions: new Map(), figures: new Map() }, ...slideQuartoTransform(root, repo, true) });
  await io.writeText(main, "Concurrent user edit");
  await reject(() => prep2.restore(), /newer content retained/, "concurrent export edit is preserved and reported");
  h.eq(await io.readText(main), "Concurrent user edit", "restoration cannot overwrite a newer buffer");
  const deps = await readProjectDependencies(root, io, [{ path: "paper/unsaved.qmd", text: line }]);
  h.ok(deps.complete && deps.byDeck.talk?.length === 2 && slideRemovalBlocker(deps, "talk", "results")?.includes("unsaved.qmd"), "canonical nested docs and live unsaved buffers protect slide deletion");
  await io.writeText(main, "# Anchor\n\nSome text.\n");
  const result = await insertSlideEmbed(root, "talk", "results", { doc: "paper/main.qmd", anchor: "# Anchor", width: "50%" });
  h.ok(result.path === "paper/main.qmd" && (await io.readText(main)).includes(result.markdown), "Node insertion writes canonical block after unique anchor");
  const inserted = await io.readText(main);
  await reject(() => insertSlideEmbed(root, "talk", "results", { doc: "paper/main.qmd", anchor: "absent" }), /exactly once/, "absent anchor fails without document edits");
  h.eq(await io.readText(main), inserted, "failed insertion preserves source bytes");
  const frozen = await io.readText(`${root}/slides/talk/deck.json`); await syncEmbeddedDeckSources(root, "talk", io);
  h.eq(await io.readText(`${root}/slides/talk/deck.json`), frozen, "frozen accepted sources do not churn a closed deck");
  await fs.rm(`${root}/slides/talk/renders/results-step-0.svg`);
  await repo.materialize(ref);
  h.ok(await io.exists(`${root}/slides/talk/renders/results-step-0.svg`), "deleted poster cache is rebuilt from its live source");
  const release = holdDocumentExport([main]); let resumed = false;
  const deferredSave = waitForDocumentExport(main).then(() => { resumed = true; });
  await Promise.resolve(); h.ok(!resumed, "autosave waits while Quarto reads its temporary sources");
  release(); await deferredSave; h.ok(resumed, "autosave resumes after source restoration without a false conflict");
  const cancelled = new AbortController(); cancelled.abort(); const writesBefore = writes.length;
  await reject(() => prepareExport(io, { entry: main, ctx: { captions: new Map(), figures: new Map() }, signal: cancelled.signal }), /AbortError/, "cancelled preparation aborts before document writes");
  h.eq(writes.length, writesBefore, "cancelled export preserves source files");
  const linked = JSON.parse(await io.readText(`${root}/slides/talk/deck.json`));
  linked.slides[0].elements.find((e: { id: string }) => e.id === "plot").source = { svgPath: "plots/live.svg" };
  const beatsBefore = JSON.stringify(linked.slides[0].beats);
  await io.writeText(`${root}/slides/talk/deck.json`, JSON.stringify(linked));
  await io.writeText(`${root}/plots/live.svg`, inlineSlideSvg("#d14d41").replace('width="320"', 'width="640"'));
  await syncEmbeddedDeckSources(root, "talk", io);
  const refreshed = JSON.parse(await io.readText(`${root}/slides/talk/deck.json`));
  h.ok((await io.readText(`${root}/slides/talk/assets/shared.svg`)).includes("#d14d41"), "closed deck accepts changed linked SVG bytes");
  h.ok(refreshed.slides[0].elements.find((e: { id: string }) => e.id === "plot").width === 640 && JSON.stringify(refreshed.slides[0].beats) === beatsBefore, "closed source refresh preserves authored scale and animations");
  const accepted = await io.readText(`${root}/slides/talk/deck.json`);
  await io.writeText(`${root}/plots/live.svg`, "<svg broken");
  const failedSource = await syncEmbeddedDeckSources(root, "talk", io);
  h.ok(failedSource.length > 0 && await io.readText(`${root}/slides/talk/deck.json`) === accepted, "invalid source retains the last accepted deck and reports its problem");
  const portable = inlineSlideFixture(); portable.slides[0].beats[1].tracks.push({ target: "plot", preset: "transform", disabled: true, to: { assetId: "missing-disabled" } });
  const inactive = await gatherSlidePayload(root, portable, "results", io);
  h.eq(inactive.warnings, [], "disabled animation targets do not become required export assets");
  repo.dispose(); await reject(() => repo.load(ref), /closed/, "disposed repository cannot resurrect pending players");
  const generated = JSON.parse(await fs.readFile(".generated/slide-embed-assets.json", "utf8"));
  h.eq(generated.csp, `'sha256-${createHash("sha256").update(generated.runtime).digest("base64")}'`, "runtime bytes match exact generated CSP hash");
} catch (error) { h.fail(String(error)); console.error(error); }
await h.done(() => fs.rm(root, { recursive: true, force: true }));
