import './lib/cssStub.mjs';
import { harness } from './lib/harness.mjs';
import { gatherPayload, portablePayload } from '../src/lib/slide/payload';
import { exportDeckHtml, exportSlideVideoHtml } from '../src/lib/slide/export/exportDeck';
import { makeModel3dElement } from '../src/lib/model3d/make';
import { inspectGlb, writeGlb } from '../src/lib/model3d/glbCore.mjs';
import { createHash } from 'node:crypto';
import type { Model3dAsset } from '../src/lib/model3d/types';
import type { Deck } from '../src/lib/slide/types';
const h=harness('verify-model3d-slide-export');
const bytes=writeGlb({parts:[{name:'mesh',positions:[0,0,0,1,0,0,0,1,1],indices:[0,1,2]}]});
const asset:Model3dAsset={id:'mesh',name:'Mesh',kind:'glb',path:'assets/mesh.glb',naturalWidth:200,naturalHeight:200,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,model:inspectGlb(bytes)};
const element=makeModel3dElement(asset,{id:'view'});
const scene={spec:'fluxplot/scene3d',schemaVersion:'0.1.0',glb:'secret.glb',parts:[{id:'mesh',role:'mesh',node:'mesh'}]};
const deck={schemaVersion:'0.6.0',id:'deck',title:'Models',stage:{width:640,height:360},assets:[asset,{...asset,id:'target',path:'assets/target.glb'}],slides:[{id:'slide',elements:[element],beats:[{id:'base',tracks:[]},{id:'change',tracks:[{id:'content',target:'view',preset:'transform',to:{assetId:'target'}}]}]}]} as unknown as Deck;
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';
let reads=0;
const io={readText:async(p:string)=>{if(p.endsWith('project.json'))return '{}';if(p.endsWith('.fluxplot.json'))return JSON.stringify(scene);throw Error('missing');},readFile:async(p:string)=>{if(!p.endsWith('.glb'))throw Error('unexpectedimage');reads++;return bytes;},modelPoster:async()=>png};
const {payload,warnings}=await gatherPayload('/scratch',deck,io);
h.eq(warnings,[],'models and design posters gather without plot warnings');
h.eq(Object.keys(payload.models??{}).sort(),['mesh','target'],'content-only model assets travel with the deck');
h.ok(!payload.assets?.mesh&&!payload.assets?.target,'GLBs never enter the image assets map');
h.eq(payload.assets?.[payload.modelPosters!.view],png,'design poster has a distinct image reference');
h.eq(reads,2,'each referenced GLB read once');
h.eq(payload.deck.assets[0].model,asset.model,'portable deck preserves model metadata');
h.eq(portablePayload(payload).modelManifests!.mesh.glb,'model.glb','portable model metadata scrubs source filename');
reads=0;await gatherPayload('/scratch',deck,{...io,modelData:'omit'});h.eq(reads,0,'static PDF/PPTX gathering never reads GLB bytes');
const exported=await exportDeckHtml(payload,{warnThreshold:1});
h.ok(exported.html.includes('var FluxModel3dRuntime='),'3D deck includes the conditional runtime');
h.ok(exported.warnings.some(w=>w.includes('max_faces=')),'large 3D deck gives model-specific size guidance');
const runtimeScripts=[...exported.html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
for(const script of runtimeScripts)h.ok(exported.html.includes(`sha256-${createHash('sha256').update(script).digest('base64')}`),'every executable script is covered by CSP');
const plain=await exportDeckHtml({deck:{...deck,assets:[],slides:[{...deck.slides[0],elements:[],beats:[]}]}});
h.ok(!plain.html.includes('var FluxModel3dRuntime='),'2D deck does not include Three/model runtime');
const capture=await exportSlideVideoHtml(payload);
h.ok(capture.includes('var FluxModel3dRuntime='),'video capture includes the model runtime');
h.done();
