import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { build } from 'esbuild';
import { launch, errors } from './lib/driver.mjs';
import { harness } from './lib/harness.mjs';
import { inspectGlb } from '../src/lib/model3d/glbCore.mjs';
const h = harness('verify-slide-model3d-player');
const out = path.resolve('test-results/model3d/slides-player'); await mkdir(out, { recursive: true });
const fixture = async (id: string) => {
  const bytes = await readFile(`scripts/fixtures/model3d/fluxplot/${id}.glb`);
  return { bytes: bytes.toString('base64'), manifest: JSON.parse(await readFile(`scripts/fixtures/model3d/fluxplot/${id}.fluxplot.json`, 'utf8')),
    asset: { id, kind: 'glb', name: id, path: `assets/${id}.glb`, sha256: createHash('sha256').update(bytes).digest('hex'), bytes: bytes.length, model: inspectGlb(bytes) } };
};
const fixtures = Object.fromEntries(await Promise.all(['continuous', 'states'].map(async id => [id, await fixture(id)])));
const bundle = await build({ stdin: { resolveDir: process.cwd(), loader: 'ts', contents: `
export { createPlayer, renderStaticAt } from './src/lib/slide/player/player';
export { modelBindingOf, modelFieldEndpoints } from './src/lib/slide/player/model3d';
export { createInlineHost } from './src/lib/model3d/inlineHost';
export { makeModel3dElement } from './src/lib/model3d/make';
export { furnitureLayout } from './src/lib/model3d/furnitureLayout';
export { createDeck, addSlide, addBeat, setTransform } from './src/lib/slide/ops';
export { FLUX_LIGHT } from './src/lib/slide/theme';
` }, bundle: true, format: 'iife', globalName: 'Slide3dProbe', write: false, platform: 'browser', target: 'es2022', loader: { '.css': 'empty' } });
const { browser, page } = await launch({ width: 1000, height: 760 });
try {
  await page.setContent('<!doctype html><html><body style="margin:20px;background:#fff"><div id="stage"></div><div id="still"></div></body></html>');
  await page.evaluate('window.__name = value => value'); await page.addScriptTag({ content: bundle.outputFiles[0].text });
  const result = await page.evaluate(async fixtures => {
    const api = (window as any).Slide3dProbe, checks: [boolean, string][] = [];
    const ok = (yes: unknown, text: string) => checks.push([!!yes, text]);
    const bytes = (id: string) => Uint8Array.from(atob((fixtures as any)[id].bytes), c => c.charCodeAt(0));
    const host = api.createInlineHost({ sourceKey: 'slide-player-gate', modelBytes: bytes });
    const deck = api.createDeck({ withTitleSlide: false }); deck.stage = { width: 680, height: 340 }; deck.assets = Object.values(fixtures).map((f: any) => f.asset);
    const slide = api.addSlide(deck), f = (fixtures as any).continuous;
    const element = { ...api.makeModel3dElement(f.asset, { id: 'surface', manifest: f.manifest }), x: 20, y: 20, width: 310, height: 290, orbitAzimuth: 30, modelLighting: 'unlit' };
    const shape = { ...api.makeModel3dElement((fixtures as any).states.asset, { id: 'shape' }), x: 360, y: 20, width: 270, height: 270 };
    slide.elements.push(element, shape);
    const beat = api.addBeat(deck, slide.id);
    api.setTransform(deck, slide.id, beat.id, element.id, { state: { orbitAzimuth: -330, orbitZoom: 2, fields: { 'height.field': { range: [0, 2] } } }, duration: 1000, easing: 'linear' });
    api.setTransform(deck, slide.id, beat.id, shape.id, { state: { modelStates: { bent: 1 } }, duration: 1000, easing: 'linear' });
    let scale = 1;
    const opts = { theme: api.FLUX_LIGHT, model3d: host, modelAsset: (id: string) => (fixtures as any)[id]?.asset, modelManifest: (id: string) => (fixtures as any)[id]?.manifest, pixelScale: () => scale, reducedMotion: false };
    const stage = document.getElementById('stage')!, player = api.createPlayer(stage, deck, opts); await player.readyMedia();
    const canvas = (id = 'surface') => stage.querySelector<HTMLCanvasElement>(`canvas[data-slide-model3d="${id}"]`)!;
    const pixels = (c: HTMLCanvasElement) => c.getContext('2d')!.getImageData(0, 0, c.width, c.height).data;
    const coverage = (c: HTMLCanvasElement) => { const data = pixels(c); let n = 0; for (let i = 3; i < data.length; i += 4) if (data[i]) n++; return n; };
    const before = canvas().toDataURL(), shapeBefore = canvas('shape').toDataURL();
    ok(coverage(canvas()) > 1000 && stage.textContent?.includes('Height'), 'live mesh pixels and vector colorbar are both present');
    ok(host.stats().contexts === 1 && host.stats().assets === 2, 'two assets share one inline renderer context');
    const direct = document.createElement('canvas'), directView = host.view(direct);
    const snapshots: Record<string, string> = {};
    for (const ms of [0, 500, 1000, 250, 500, 0]) {
      player.seek(0, 1, ms); await player.captureMedia([], ms);
      const sampled = api.modelBindingOf(stage.querySelector('[data-el-id="surface"]')).element;
      directView.render({ ...sampled, x: 0, y: 0 }, canvas().width, canvas().height, { manifest: f.manifest });
      ok(direct.toDataURL() === canvas().toDataURL(), `sample ${ms} ms equals independent direct inline rendering`);
      const key = String(ms); if (snapshots[key]) ok(snapshots[key] === canvas().toDataURL(), `random seek ${ms} is deterministic`); snapshots[key] = canvas().toDataURL();
      if (ms === 500) ok(sampled.orbitAzimuth === -150 && Math.abs(sampled.orbitZoom - Math.sqrt(element.orbitZoom * 2)) < 1e-10 && sampled.fields['height.field'].range[0] === -.5, 'midpoint uses unwrapped azimuth, geometric zoom and manifest-resolved field domain');
    }
    player.seek(0, 1, 1000); await player.readyMedia();
    ok(canvas().toDataURL() !== before && canvas('shape').toDataURL() !== shapeBefore, 'view/field and shape transform change actual model pixels');
    const textSize = stage.querySelector('[data-slide-model-root="surface"] text')?.getAttribute('font-size'), oldWidth = canvas().width;
    scale = 2; player.refresh(); await player.readyMedia();
    ok(canvas().width === oldWidth * 2 && stage.querySelector('[data-slide-model-root="surface"] text')?.getAttribute('font-size') === textSize, 'fit scale changes bitmap resolution while physical vector font stays unchanged');
    const count = host.stats().renders; await new Promise(r => setTimeout(r, 180));
    ok(host.stats().renders === count, 'resting player has no renderer heartbeat');
    const wrap = stage.querySelector<HTMLElement>('[data-el-id="surface"]')!, retainedCanvas = canvas(), retainedPixels = retainedCanvas.toDataURL();
    wrap.style.visibility = 'hidden'; player.refresh();
    ok(retainedCanvas.width === 0 && retainedCanvas.height === 0, 'already-born hidden model releases its canvas backing store');
    wrap.style.visibility = ''; player.refresh(); await player.readyMedia();
    ok(retainedCanvas.width > 0 && retainedCanvas.toDataURL() === retainedPixels, 'revealed model reacquires a view with exact pixels');
    const posters: Record<string, string> = { surface: canvas().toDataURL(), shape: canvas('shape').toDataURL() };
    const modelPoster = (element: any) => posters[element.id], still = document.getElementById('still')!;
    const staticCount = host.stats().renders;
    api.renderStaticAt(still, slide, deck.stage, 1, { ...opts, modelPoster });
    ok(host.stats().renders === staticCount && !still.querySelector('canvas[width]:not([width="0"])'), 'static host never allocates a live model surface or renders');
    const gradients = [...document.querySelectorAll('linearGradient')].map(node => node.id);
    ok(new Set(gradients).size === gradients.length, 'simultaneous live and static views have independent colorbar paint servers');
    ok(stage.querySelector('[id="surface__height.colorbar"]') && still.querySelector('[id="surface__height.colorbar"]'), 'semantic furniture group IDs stay addressable in each scoped view');
    ok(!!still.querySelector('image[data-model3d-poster]') && still.textContent?.includes('Height'), 'static sampled composition includes matching poster and vector furniture');
    const noHost = api.createPlayer(document.createElement('div'), deck, { ...opts, model3d: undefined, modelPoster }); await noHost.readyMedia();
    ok(noHost.state().issues.some((issue: any) => issue.reason === '3D model rendered as a still'), 'hostless runtime emits a truthful still issue'); noHost.destroy();
    player.seek(0, 1, 500); await player.readyMedia();
    (window as any).slide3d = { player, host, deck, opts, directView, checks, canvas, stage };
    return checks;
  }, fixtures);
  for (const [yes, message] of result) h.ok(yes, message);
  await page.screenshot({ path: path.join(out, 'live-and-static.png') });
  const extra = await page.evaluate(async () => {
    const { player, host, deck, opts, directView } = (window as any).slide3d, api = (window as any).Slide3dProbe;
    player.destroy(); directView.dispose(); host.dispose();
    const checks: [boolean, string][] = [], ok = (yes: unknown, text: string) => checks.push([!!yes, text]);
    let release!: () => void, rendered = 0, disposed = 0;
    const delay = new Promise<void>(resolve => release = resolve); let renderDelay = delay;
    const asyncHost = { ready: async () => {}, view: (canvas: HTMLCanvasElement) => { let released = false; return { async render(_el: unknown, w: number, h: number) { await renderDelay; if (released) return; canvas.width = w; canvas.height = h; canvas.getContext('2d')!.fillRect(0,0,w,h); rendered++; }, dispose() { released = true; canvas.width = 0; canvas.height = 0; disposed++; } }; }, dispose() {} };
    const mount = document.createElement('div'); document.body.append(mount);
    const p = api.createPlayer(mount, deck, { ...opts, model3d: asyncHost }); let settled = false;
    const ready = p.readyMedia().then(() => settled = true); await new Promise(r => setTimeout(r, 20));
    ok(!settled && rendered === 0, 'readyMedia waits for asynchronous worker publication');
    const pendingCanvas = mount.querySelector<HTMLCanvasElement>('canvas')!, pendingWrapper = mount.querySelector<HTMLElement>('[data-el-id="surface"]')!;
    pendingWrapper.style.visibility = 'hidden'; p.refresh();
    release(); await ready; ok(pendingCanvas.width === 0 && pendingCanvas.style.display === 'none', 'hidden view rejects stale asynchronous publication');
    pendingWrapper.style.visibility = ''; p.refresh(); await p.readyMedia();
    ok(settled && rendered === 2, 'all async model views settle before capture proceeds');
    let releaseFrame!: () => void; renderDelay = new Promise<void>(resolve => releaseFrame = resolve);
    const oldText = mount.textContent; p.seek(0, 1, 1000); await Promise.resolve();
    ok(mount.textContent === oldText, 'worker-delayed frame retains the previous matching vector furniture');
    releaseFrame(); await p.captureMedia([], 1000);
    ok(mount.textContent !== oldText, 'new field furniture publishes only with the matching async mesh frame');
    p.destroy(); ok(disposed === 3 && !mount.childNodes.length, 'player destroys every view and its DOM');
    let warm!: () => void; const warmWait = new Promise<void>(resolve => warm = resolve);
    const warmPlayer = api.createPlayer(mount, deck, { ...opts, model3d: { ...asyncHost, ready: () => warmWait } });
    warmPlayer.play({ slide: 0, fromBeat: 1 }); await new Promise(r => setTimeout(r, 35));
    ok(!warmPlayer.state().playing && warmPlayer.state().time === 0, 'authoring clock waits for first model upload and shader warmup');
    warm(); await warmPlayer.readyMedia(); await new Promise(r => setTimeout(r, 35));
    ok(warmPlayer.state().playing && warmPlayer.state().time < 100, 'ready completion starts authored playback from its beginning'); warmPlayer.destroy();
    const bad = api.createPlayer(mount, deck, { ...opts, model3d: { ...asyncHost, ready: async () => { throw Error('GPU unavailable'); } } });
    let rejected = false; try { await bad.readyMedia(); } catch { rejected = true; }
    ok(rejected && bad.state().issues.some((i: any) => i.reason.includes('GPU unavailable')) && !!mount.querySelector('[data-slide-model-root] svg'), 'failed GPU load keeps fallback and refuses falsely successful captures'); bad.destroy();
    return checks;
  });
  for (const [yes, message] of extra) h.ok(yes, message);
  h.eq(errors(page), [], 'browser has no uncaught player errors');
  await writeFile(path.join(out, 'receipt.json'), JSON.stringify({ checks: [...result, ...extra] }, null, 2));
} finally { await browser.close(); }
await h.done();
