import {readFile}from'node:fs/promises';
import assert from'node:assert/strict';
import{harness}from'./lib/harness.mjs';
import{furnitureGoldens}from'./gen-model3d-furniture-goldens.mjs';
import{furnitureLayout}from'../src/lib/model3d/furnitureLayout';
import{furnitureSvg}from'../src/lib/model3d/furniture';
import{niceTicks}from'../src/lib/model3d/ticks';
import{orbitPose,axisView,pixelsPerUnit}from'../src/lib/model3d/orbit';
import{makeModel3dElement}from'../src/lib/model3d/make';
import{inspectGlb}from'../src/lib/model3d/glbCore.mjs';
import type{Scene3dManifest,Model3dAsset}from'../src/lib/model3d/types';
const h=harness('verify-model3d-furniture'),root=new URL('./fixtures/model3d/fluxplot/',import.meta.url);
const golden=JSON.parse(await readFile(new URL('./fixtures/model3d/furniture-golden.json',import.meta.url),'utf8'));assert.deepEqual(await furnitureGoldens(),golden);h.eq(Object.keys(golden).length,33,'11 fixtures ×3 views match exact layout/SVG goldens');
const m:Scene3dManifest=JSON.parse(await readFile(new URL('box-axes.fluxplot.json',root),'utf8')),info=inspectGlb(await readFile(new URL('box-axes.glb',root))),asset:Model3dAsset={id:'a',name:'box.glb',kind:'glb',path:'assets/a.glb',naturalWidth:336,naturalHeight:288,sha256:'0'.repeat(64),bytes:4000,model:info},el=makeModel3dElement(asset,{manifest:m,id:'test'});
const layout=furnitureLayout(m,el),pose=orbitPose(el,info.bounds,layout.viewport),front=furnitureSvg(m,el,pose,layout),back=furnitureSvg(m,{...el,...axisView('back')},orbitPose({...el,...axisView('back')},info.bounds,layout.viewport),layout);
h.ok(front.under.includes('<text')&&front.under.includes('x (µm)'),'axes use vector text');h.ok(front.under!==back.under,'panes and projected ticks follow view');h.ok(!/NaN|Infinity/.test(front.under),'all projected coordinates finite');h.ok(front.under.includes('test__axes.x.ticks'),'semantic part ids namespaced');
const larger=furnitureLayout(m,{width:el.width*2,height:el.height*2});h.eq(larger.fontSize,layout.fontSize,'resize keeps physical font size');h.ok(larger.viewport.width>layout.viewport.width,'resize expands3D viewport');
const sm:Scene3dManifest=JSON.parse(await readFile(new URL('scalebar.fluxplot.json',root),'utf8')),se=makeModel3dElement(asset,{manifest:sm,id:'scale'}),sl=furnitureLayout(sm,se),sp=orbitPose(se,info.bounds,sl.viewport),ss=furnitureSvg(sm,se,sp,sl);const scaleGroup=ss.overNodes.find(n=>n.partId==='scalebar'),bar=scaleGroup?.children?.find(n=>n.tag==='line');h.ok(!!bar,'scale bar rendered');h.ok(Math.abs(Number(bar?.attrs.x2)-Number(bar?.attrs.x1)-(sm.parts!.find(p=>p.id==='scalebar')!.length!*pixelsPerUnit(sp,sl.viewport)!))<1e-9,'scale bar exact data-unit projection');h.ok(!furnitureSvg(sm,se,{...sp,projection:'perspective'},sl).over.includes('scale-line'),'perspective hides exact scale bar');
const hidden={...sm,parts:sm.parts!.map(p=>p.id==='scalebar'?{...p,hidden:true}:p)};h.eq(furnitureLayout(hidden,se,{'scalebar':{hidden:false}}).scalebars.length,1,'explicit show overrides source-hidden');
h.eq(niceTicks(-1,1),[-1,-.5,0,.5,1],'nice tick oracle');h.eq(niceTicks(1.21,3.82),[1.5,2,2.5,3,3.5],'data range tick oracle');
for(const name of ['furniture.ts','furnitureLayout.ts','ticks.ts'])h.ok(!/getBoundingClientRect|measureText|document\.|window\./.test(await readFile(new URL(`../src/lib/model3d/${name}`,import.meta.url),'utf8')),`${name} no DOM/text measurement`);
const styled={...el,overrides:{'axes.x.label':{fill:'#FF0000',fontSize:21}}},s=furnitureSvg(m,styled,pose,layout);h.ok(s.under.includes('fill="#FF0000"')&&s.under.includes('font-size="21"'),'part text styling shares plot units');await h.done();
