// The ONE DOM writer for live colour scales (colour-system plan A7.3 / A7.4).
//
// `applyPlotColorScale(root, manifest, colorScale, elId)` recolours every element a manifest
// colour scale paints — the descendants of `[data-color-scale=<id>]` groups carrying
// `data-value` (or `data-missing`) — through the pure colour law (plot/colorscale.ts) with the
// element's `colorScale` view applied, writing only the paint properties the group's
// `data-paint` names (fill, stroke, or both). It redraws each of the scale's colour keys too:
// the solids gradient's stops from the new table and the ticks / tick labels from the new
// limits. Every write is recorded so `restore` puts the generated bytes back exactly (the same
// pristine-record discipline as projectDom.restoreProjection); an absent or identity view
// restores. Called by every plot host BEFORE applyOverrides, so an explicit per-part override
// still wins, and idempotent at any frame of the slide pipeline.
//
// Budget: a hexmatrix or a cells=True heatmap has thousands of elements and this runs while the
// user scrubs a limit, so the per-root bindings (nodes, parsed values, last slot written) are
// built once and cached (WeakMap by root), the table is parsed once per apply, and a node is
// touched only when its colour slot changed. Nothing here reads layout.
import type { FluxPlotManifest, FluxPlotColorScale, FluxPlotGuide } from "./types";
import type { ColorScaleView } from "../types";
import { partDomId } from "./parse";
import { effectiveScale, parseColormap, slotFor, normalize, INDEX_KINDS, rgbHex, viewIsIdentity, alphaFor, shortFloat,
  type ParsedColormap, type LutResolver, type EffectiveScale } from "./colorscale";
import { colormapLut } from "../color/colormapLuts";
import { ticksFor, logMinorTicks, formatTick, scalarLabels } from "./ticks";

type Paint = "fill" | "stroke" | "both";
interface Binding {
  nodes: Element[]; values: Float64Array; missing: Uint8Array; paint: Paint; last: Int32Array; tableKey: string;
  /** Each element's `data-alpha-value` (NaN when it carries none): the scale's opacity channel. */
  alphaValues: Float64Array | null;
}
interface RootState { groups: Map<string, Binding[]>; touched: Set<Element>; keys: Map<string, KeyState[]> }
interface PristinePaint { fill: string; stroke: string; fillOpacity: string; strokeOpacity: string; hadStyle: boolean }
interface KeyState { gradient: Element | null; stops: Node[] | null; ticks: TickNode[]; labels: TickNode[]; minors: TickNode[]; clones: Element[]; guide: FluxPlotGuide; offset: number }
interface TickNode { node: Element; transform: string | null; x: string | null; y: string | null; text: string | null; display: string; shown: boolean }

const roots = new WeakMap<Element, RootState>();
const paints = new WeakMap<Element, PristinePaint>();

const DRAWABLE = "path,use,rect,circle,ellipse,polygon,polyline,line,image";
function drawable(node: Element): Element[] {
  if (/^(path|use|rect|circle|ellipse|polygon|polyline|line|image)$/i.test(node.tagName)) return [node];
  return Array.from(node.querySelectorAll(DRAWABLE));
}

function stateFor(root: Element): RootState {
  let st = roots.get(root);
  if (!st) { st = { groups: new Map(), touched: new Set(), keys: new Map() }; roots.set(root, st); }
  return st;
}

function paintOf(group: Element): Paint {
  const p = (group.getAttribute("data-paint") ?? "fill").trim();
  return p.includes("fill") && p.includes("stroke") ? "both" : p.includes("stroke") ? "stroke" : "fill";
}

function bindings(root: Element, st: RootState, scaleId: string): Binding[] {
  const cached = st.groups.get(scaleId);
  if (cached) return cached;
  const out: Binding[] = [];
  for (const group of Array.from(root.querySelectorAll(`[data-color-scale="${scaleId.replace(/["\\]/g, "\\$&")}"]`))) {
    const nodes: Element[] = [], vals: number[] = [], miss: number[] = [], alphas: number[] = [];
    let anyAlpha = false;
    const candidates = group.matches?.("[data-value],[data-missing]") ? [group] : Array.from(group.querySelectorAll("[data-value],[data-missing]"));
    for (const n of candidates) {
      const missing = n.getAttribute("data-missing") === "1";
      const v = missing ? NaN : Number(n.getAttribute("data-value"));
      if (!missing && !Number.isFinite(v)) continue;
      const a = n.getAttribute("data-alpha-value");
      const av = a == null || a === "" ? NaN : Number(a);
      if (a != null && a !== "") anyAlpha = true;
      nodes.push(n); vals.push(v); miss.push(missing ? 1 : 0); alphas.push(av);
    }
    if (nodes.length) out.push({ nodes, values: Float64Array.from(vals), missing: Uint8Array.from(miss), paint: paintOf(group), last: new Int32Array(nodes.length).fill(-1), tableKey: "",
      alphaValues: anyAlpha ? Float64Array.from(alphas) : null });
  }
  st.groups.set(scaleId, out);
  return out;
}

function capture(node: Element): PristinePaint {
  let rec = paints.get(node);
  if (!rec) {
    const st = (node as SVGElement).style;
    rec = { fill: st.getPropertyValue("fill") ?? "", stroke: st.getPropertyValue("stroke") ?? "",
      fillOpacity: st.getPropertyValue("fill-opacity") ?? "", strokeOpacity: st.getPropertyValue("stroke-opacity") ?? "",
      hadStyle: node.hasAttribute("style") };
    paints.set(node, rec);
  }
  return rec;
}

function writePaint(node: Element, st: RootState, paint: Paint, hex: string, alpha: number, channel?: number | "keep"): void {
  for (const d of drawable(node)) {
    capture(d); st.touched.add(d);
    const style = (d as SVGElement).style;
    // matplotlib's SVG writer: a fully transparent colour is `none`, a translucent one carries
    // its opacity, an opaque one nothing (so a live paint serialises as a regenerated one would).
    // An element under the scale's opacity channel (alpha_by) takes the channel's alpha in
    // place of the colour's, as matplotlib's per-element alpha does — a transparent (bad)
    // colour stays transparent.
    const value = alpha <= 0 ? "none" : hex;
    if (channel === "keep" && alpha > 0) { // the scale has an opacity channel this element is not in: its own opacity stands
      if (paint !== "stroke") style.setProperty("fill", value);
      if (paint !== "fill") style.setProperty("stroke", value);
      continue;
    }
    const eff = alpha <= 0 ? 0 : typeof channel === "number" ? channel : alpha;
    const opacity = eff > 0 && eff < 1 ? shortFloat(eff) : "";
    if (paint !== "stroke") { style.setProperty("fill", value); if (opacity) style.setProperty("fill-opacity", opacity); else style.removeProperty("fill-opacity"); }
    if (paint !== "fill") { style.setProperty("stroke", value); if (opacity) style.setProperty("stroke-opacity", opacity); else style.removeProperty("stroke-opacity"); }
  }
}

function restorePaint(node: Element): void {
  const rec = paints.get(node);
  if (!rec) return;
  const style = (node as SVGElement).style;
  for (const [prop, value] of [["fill", rec.fill], ["stroke", rec.stroke], ["fill-opacity", rec.fillOpacity], ["stroke-opacity", rec.strokeOpacity]] as const) {
    if (value) style.setProperty(prop, value); else style.removeProperty(prop);
  }
  if (!rec.hadStyle && !node.getAttribute("style")) node.removeAttribute("style");
}

/** Put back everything this module wrote under `root`. */
export function restoreColorScales(root: Element): void {
  const st = roots.get(root);
  if (!st) return;
  for (const node of st.touched) restorePaint(node);
  st.touched.clear();
  for (const list of st.groups.values()) for (const b of list) { b.last.fill(-1); b.tableKey = ""; }
  for (const list of st.keys.values()) for (const k of list) restoreKey(k);
}

export interface ColorScaleApplyResult {
  /** Why a scale was left as generated (mirrors plotViewIssues). */
  issues: string[];
  /** Named colormaps the table resolver did not know yet (load them and re-apply). */
  unresolved: string[];
}

/** Recolour `root` for the plot element's live colour-scale edits. Idempotent. */
export function applyPlotColorScale(root: Element, manifest: FluxPlotManifest | undefined, colorScale: Record<string, ColorScaleView> | undefined, elId: string,
  opts?: { resolve?: LutResolver }): ColorScaleApplyResult {
  const result: ColorScaleApplyResult = { issues: [], unresolved: [] };
  const scales = manifest?.colorScales;
  const st = roots.get(root);
  if (!scales?.length || !colorScale || !Object.keys(colorScale).length) { if (st) restoreColorScales(root); return result; }
  const state = stateFor(root);
  const resolve = opts?.resolve ?? colormapLut;
  const active = new Set<Element>();
  for (const scale of scales) {
    const view = colorScale[scale.id];
    const skip = !view || viewIsIdentity(scale, view);
    if (!skip && scale.recolor !== "live") result.issues.push(`Colour scale ‹${scale.id}› is a raster: change its colours by regenerating the plot.`);
    if (skip || scale.recolor !== "live") { restoreScale(root, state, scale); continue; }
    const eff = effectiveScale(scale, view, resolve);
    // a named colormap whose table has not loaded yet: keep the generated paint (no flicker
    // through a wrong intermediate) and tell the host, which re-applies once the table is in
    if (eff.unresolved) { result.unresolved.push(eff.unresolved); restoreScale(root, state, scale); continue; }
    if (eff.issues.length) { result.issues.push(...eff.issues.map((i) => `Colour scale ‹${scale.id}›: ${i}`)); restoreScale(root, state, scale); continue; }
    const parsed = parseColormap(eff.colormap);
    const integer = INDEX_KINDS.includes(eff.norm.kind);
    const tableKey = `${eff.colormap.name}|${eff.colormap.N}|${eff.colormap.lut[0]}|${eff.colormap.lut[eff.colormap.N - 1]}|${eff.colormap.under}|${eff.colormap.over}|${eff.colormap.bad}`;
    const alphaChannel = scale.alpha;
    for (const b of bindings(root, state, scale.id)) {
      const fresh = b.tableKey !== tableKey;
      b.tableKey = tableKey;
      const N = parsed.N;
      for (let i = 0; i < b.nodes.length; i++) {
        const slot = b.missing[i] ? N + 2 : slotFor(N, normalize(eff.norm, b.values[i]), integer);
        if (!fresh && slot === b.last[i]) { active.add(b.nodes[i]); continue; }
        b.last[i] = slot;
        const c = parsed.colors[slot];
        // the opacity channel (B6): an element carrying data-alpha-value keeps its channel alpha
        // through every recolour; one without keeps its own opacity
        const av = b.alphaValues ? b.alphaValues[i] : NaN;
        const channel = alphaChannel ? (b.alphaValues && !Number.isNaN(av) ? alphaFor(alphaChannel, av) : "keep") : undefined;
        writePaint(b.nodes[i], state, b.paint, rgbHex(c), c.a, channel);
        active.add(b.nodes[i]);
      }
    }
    redrawKeys(root, state, manifest!, scale, eff, parsed, elId);
  }
  // nodes recoloured on an earlier frame by a scale that is no longer active
  for (const node of state.touched) if (!active.has(node) && !activeAncestor(node, active)) { restorePaint(node); state.touched.delete(node); }
  return result;
}

function activeAncestor(node: Element, active: Set<Element>): boolean {
  for (let p = node.parentElement; p; p = p.parentElement) if (active.has(p)) return true;
  return false;
}

function restoreScale(root: Element, st: RootState, scale: FluxPlotColorScale): void {
  for (const b of st.groups.get(scale.id) ?? []) {
    if (!b.tableKey) continue;
    for (const n of b.nodes) for (const d of drawable(n)) { restorePaint(d); st.touched.delete(d); }
    b.last.fill(-1); b.tableKey = "";
  }
  for (const k of st.keys.get(scale.id) ?? []) restoreKey(k);
}

/** The reasons a live colour-scale view cannot be honoured in full (for the editor). */
export function plotColorScaleIssues(manifest: FluxPlotManifest | undefined, colorScale: Record<string, ColorScaleView> | undefined, resolve?: LutResolver): string[] {
  if (!colorScale || !Object.keys(colorScale).length) return [];
  if (!manifest?.colorScales?.length) return ["This plot records no colour scales; regenerate it with fluxplot ≥ 0.3.1 to recolour it live."];
  const issues: string[] = [];
  for (const [id, view] of Object.entries(colorScale)) {
    const scale = manifest.colorScales.find((s) => s.id === id);
    if (!scale) { issues.push(`Colour scale ‹${id}› is not in this plot (${manifest.colorScales.map((s) => s.id).join(", ")}).`); continue; }
    if (viewIsIdentity(scale, view)) continue;
    if (scale.recolor !== "live") issues.push(`Colour scale ‹${id}› is a raster: change its colours by regenerating the plot.`);
    const eff = effectiveScale(scale, view, resolve ?? colormapLut);
    issues.push(...eff.issues.map((i) => `Colour scale ‹${id}›: ${i}`));
    if (eff.unresolved) issues.push(`Colormap ‹${eff.unresolved}› is not one fluxplot ships; the generated colours are kept.`);
  }
  return issues;
}

// --- colour keys ------------------------------------------------------------------------------
const q = (root: Element, id: string): Element | null => root.querySelector(`[id="${id.replace(/["\\]/g, "\\$&")}"]`);

function keyStates(root: Element, st: RootState, manifest: FluxPlotManifest, scale: FluxPlotColorScale, elId: string): KeyState[] {
  const cached = st.keys.get(scale.id);
  if (cached) return cached;
  const out: KeyState[] = [];
  for (const cbId of scale.colorbars) {
    const guide = manifest.guides?.find((g) => g.id === cbId);
    if (!guide) continue;
    const solids = guide.parts?.find((p) => p.role === "colorbar-solids")?.svgId;
    const gradient = solids ? q(root, partDomId(elId, `${solids}.gradient`)) : null;
    const prefix = `${cbId}.`;
    const pick = (suffix: string) => (guide.parts ?? [])
      .map((p) => ({ p, m: new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}${suffix}\\.(\\d+)$`).exec(p.svgId) }))
      .filter((x) => x.m).sort((a, b) => Number(a.m![1]) - Number(b.m![1]))
      .map((x) => q(root, partDomId(elId, x.p.svgId))).filter((n): n is Element => !!n)
      .map((node): TickNode => ({ node, transform: null, x: null, y: null, text: null, display: "", shown: true }));
    const ticks = pick("tick"), labels = pick("tick-label");
    out.push({ gradient, stops: null, ticks, labels, minors: pick("minor\\.tick"), clones: [], guide, offset: labelOffsetOf(ticks[0], labels[0], guide.orientation !== "horizontal") });
  }
  st.keys.set(scale.id, out);
  return out;
}

function tickTarget(t: TickNode): Element {
  // the moved node: a tick's <path> (translate) or a label's <text>
  return t.node.querySelector("path,text") ?? t.node;
}

function snapshot(t: TickNode): void {
  if (t.transform !== null || t.x !== null || t.y !== null || t.text !== null) return;
  const target = tickTarget(t);
  t.transform = target.getAttribute("transform") ?? "";
  t.x = target.getAttribute("x") ?? ""; t.y = target.getAttribute("y") ?? "";
  t.text = target.tagName.toLowerCase() === "text" ? target.innerHTML : "";
  t.display = (t.node as SVGElement).style.getPropertyValue("display") ?? "";
}

function restoreTick(t: TickNode): void {
  if (t.transform === null) return;
  const target = tickTarget(t);
  if (t.transform) target.setAttribute("transform", t.transform); else target.removeAttribute("transform");
  if (t.x) target.setAttribute("x", t.x); else target.removeAttribute("x");
  if (t.y) target.setAttribute("y", t.y); else target.removeAttribute("y");
  if (target.tagName.toLowerCase() === "text") target.innerHTML = t.text ?? "";
  const style = (t.node as SVGElement).style;
  if (t.display) style.setProperty("display", t.display); else style.removeProperty("display");
  t.transform = t.x = t.y = t.text = null; t.shown = true;
}

function restoreKey(k: KeyState): void {
  if (k.gradient && k.stops) {
    while (k.gradient.firstChild) k.gradient.removeChild(k.gradient.firstChild);
    for (const s of k.stops) k.gradient.appendChild(s);
    k.stops = null;
  }
  for (const t of [...k.ticks, ...k.labels, ...k.minors]) restoreTick(t);
  for (const c of k.clones) c.parentNode?.removeChild(c);
  k.clones = [];
}

function place(target: Element, vertical: boolean, pos: number): void {
  const tr = target.getAttribute("transform");
  if (tr && /translate\(/.test(tr)) {
    target.setAttribute("transform", tr.replace(/translate\(\s*([-\d.eE+]+)[ ,]+([-\d.eE+]+)\s*\)/, (_m, x, y) =>
      vertical ? `translate(${x} ${pos.toFixed(6)})` : `translate(${pos.toFixed(6)} ${y})`));
    return;
  }
  const attr = vertical ? "y" : "x";
  const old = Number(target.getAttribute(attr));
  target.setAttribute(attr, pos.toFixed(6));
  if (tr && /rotate\(/.test(tr) && Number.isFinite(old)) {
    target.setAttribute("transform", tr.replace(/rotate\(\s*([-\d.eE+]+)[ ,]+([-\d.eE+]+)[ ,]+([-\d.eE+]+)\s*\)/, (_m, a, x, y) =>
      vertical ? `rotate(${a} ${x} ${pos.toFixed(6)})` : `rotate(${a} ${pos.toFixed(6)} ${y})`));
  }
}

function redrawKeys(root: Element, st: RootState, manifest: FluxPlotManifest, scale: FluxPlotColorScale, eff: EffectiveScale, parsed: ParsedColormap, elId: string): void {
  for (const k of keyStates(root, st, manifest, scale, elId)) {
    // 1. the solids: two hard stops per table entry, uniform in the key's axis space
    if (k.gradient) {
      if (!k.stops) k.stops = Array.from(k.gradient.childNodes);
      const doc = k.gradient.ownerDocument!;
      const N = parsed.N;
      const wanted = 2 * N;
      const existing = Array.from(k.gradient.children);
      while (existing.length < wanted) { const s = doc.createElementNS("http://www.w3.org/2000/svg", "stop"); k.gradient.appendChild(s); existing.push(s); }
      while (existing.length > wanted) { const s = existing.pop()!; k.gradient.removeChild(s); }
      for (let i = 0; i < N; i++) {
        const c = parsed.colors[i], hex = rgbHex(c);
        for (const [j, off] of [[2 * i, i / N], [2 * i + 1, (i + 1) / N]] as const) {
          const s = existing[j];
          s.setAttribute("offset", String(off)); s.setAttribute("stop-color", hex);
          if (c.a < 1) s.setAttribute("stop-opacity", String(Math.round(c.a * 1000) / 1000)); else s.removeAttribute("stop-opacity");
        }
      }
    }
    // 2. the ticks: new values from the new limits, positioned through the key's anchors
    const g = k.guide;
    const anchors = g.anchors ?? [];
    const a0 = anchors.find((a) => a.value === scale.norm.vmin) ?? anchors[0];
    const a1 = anchors.find((a) => a.value === scale.norm.vmax) ?? anchors[anchors.length - 1];
    if (!a0 || !a1 || a0 === a1 || eff.norm.vmin == null || eff.norm.vmax == null || !k.ticks.length) continue;
    const vertical = g.orientation !== "horizontal";
    const at = (v: number) => { const f = normalize(eff.norm, v); return Number.isFinite(f) && f >= -1e-9 && f <= 1 + 1e-9 ? a0.svg + (a1.svg - a0.svg) * Math.max(0, Math.min(1, f)) : NaN; };
    const majors = ticksFor(eff.norm.kind, eff.norm.vmin, eff.norm.vmax).map((v) => ({ v, pos: at(v) })).filter((p) => Number.isFinite(p.pos));
    const minors = (k.minors.length && eff.norm.kind === "log" ? logMinorTicks(eff.norm.vmin, eff.norm.vmax, majors.map((p) => p.v)) : [])
      .map((v) => ({ v, pos: at(v) })).filter((p) => Number.isFinite(p.pos));
    const formatter = (g.tickFormatter ?? "plain") as Parameters<typeof formatTick>[1];
    // a plain (ScalarFormatter) key labels every major with the same decimals and a unicode minus
    const plainLabels = formatter === "plain" && eff.norm.kind !== "log" ? scalarLabels(majors.map((p) => p.v)) : null;
    const ensure = (list: TickNode[], i: number, kind: string): TickNode => {
      if (i < list.length) return list[i];
      const last = list[list.length - 1];
      const clone = last.node.cloneNode(true) as Element;
      const id = last.node.getAttribute("id") ?? "";
      const m = /^(.*\.)(\d+)$/.exec(id);
      clone.setAttribute("id", m ? `${m[1]}${Number(m[2]) + (i - list.length + 1)}` : `${id}.${kind}.${i}`);
      last.node.parentNode?.insertBefore(clone, last.node.nextSibling);
      k.clones.push(clone);
      const t: TickNode = { node: clone, transform: null, x: null, y: null, text: null, display: "", shown: true };
      list.push(t);
      return t;
    };
    const show = (t: TickNode) => { (t.node as SVGElement).style.removeProperty("display"); t.shown = true; };
    const hideSurplus = (list: TickNode[], n: number) => {
      for (let i = n; i < list.length; i++) { const t = list[i]; snapshot(t); (t.node as SVGElement).style.setProperty("display", "none"); t.shown = false; }
    };
    majors.forEach(({ v, pos }, i) => {
      const t = ensure(k.ticks, i, "tick"); snapshot(t); place(tickTarget(t), vertical, pos); show(t);
      if (!k.labels.length) return;
      const l = ensure(k.labels, i, "tick-label"); snapshot(l);
      const target = tickTarget(l);
      place(target, vertical, pos + (vertical ? k.offset : 0));
      const label = plainLabels ? { text: plainLabels[i] } : formatTick(v, formatter);
      if (target.tagName.toLowerCase() === "text") {
        if (label.exponent !== undefined) target.innerHTML = `${label.base}<tspan baseline-shift="super" style="font-size: 70%">${label.exponent}</tspan>`;
        else target.textContent = label.text;
      }
      show(l);
    });
    hideSurplus(k.ticks, majors.length);
    hideSurplus(k.labels, majors.length);
    if (k.minors.length) {
      minors.forEach(({ pos }, i) => { const t = ensure(k.minors, i, "minor.tick"); snapshot(t); place(tickTarget(t), vertical, pos); show(t); });
      hideSurplus(k.minors, minors.length);
    }
  }
}

/** A tick label sits a little off its tick (matplotlib centres it on the tick's position, so
 *  the generated label y minus the tick's translate y is the baseline offset); measured once on
 *  the pristine first pair of a key and reused for every label it places. */
function labelOffsetOf(tick: TickNode | undefined, label: TickNode | undefined, vertical: boolean): number {
  if (!tick || !label || !vertical) return 0;
  const own = Number(tickTarget(label).getAttribute("y"));
  const m = /translate\(\s*([-\d.eE+]+)[ ,]+([-\d.eE+]+)/.exec(tickTarget(tick).getAttribute("transform") ?? "");
  const tickPos = m ? Number(m[2]) : NaN;
  return Number.isFinite(own) && Number.isFinite(tickPos) ? own - tickPos : 0;
}
