// A placed plot follows the deck's theme (colour-system plan B1, Flux half).
//
// fluxplot ≥ 0.3.1 tags every scaffold element it paints with a theme token —
// `data-ink-fill` / `data-ink-stroke` = ink | label | tick | axis | grid | plot | paper — and records
// the generated token values in `manifest.style.tokens`. `applyPlotTheme(root, manifest, theme)`
// maps the tokens onto the deck theme (ink / label / tick → the theme's text, axis → its muted
// text, grid → a 15 % mix of text into the background, plot / paper → transparent) and writes the
// paint on every tagged node, so a `use_light` plot dropped on a dark deck reads in the deck's
// ink without a regeneration. Data colours are never touched: only the tagged scaffold nodes are
// written, and every write is recorded so `restorePlotTheme` puts the generated bytes back
// exactly (the same pristine-record discipline as colorScaleDom / projectDom). Called by every
// plot host BEFORE applyOverrides, so an explicit per-part paint still wins; idempotent at any
// frame. The rule for WHEN: `plotFollowsTheme(el, host)` — an element's `followTheme`, else on
// by default on slides and off in Paper / Figure, which have no deck theme to follow.
import { writable } from "svelte/store";
import type { DeckTheme } from "../slide/types";
import type { SemanticPlotElement } from "../types";
import type { FluxPlotManifest } from "./types";

export type InkToken = "ink" | "label" | "tick" | "axis" | "grid" | "plot" | "paper";
export const INK_TOKENS: readonly InkToken[] = ["ink", "label", "tick", "axis", "grid", "plot", "paper"];
/** The share of the theme's text mixed into its background for gridlines. */
export const GRID_MIX = 0.15;

/** The deck theme the shared Canvas is editing under (Slide mode sets it, Figure leaves it
 *  null), so the plot mount can follow it. Present / export hosts pass their own `ctx.theme`. */
export const plotTheme = writable<DeckTheme | null>(null);

/** Whether a plot element follows the host's theme: its own flag, else on for slides. */
export function plotFollowsTheme(el: Pick<SemanticPlotElement, "followTheme"> | undefined, host: "slide" | "figure" | "paper"): boolean {
  if (!el) return false;
  return el.followTheme ?? host === "slide";
}

function hexToRgb(hex: string): [number, number, number] | null {
  const m = /^#([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return null;
  const v = parseInt(m[1], 16);
  return [(v >> 16) & 255, (v >> 8) & 255, v & 255];
}
const toHex = (c: [number, number, number]) => "#" + c.map((x) => Math.round(Math.min(255, Math.max(0, x))).toString(16).padStart(2, "0")).join("");

/** `t` of `b` mixed into `a` (sRGB), as lowercase hex. */
export function mixHex(a: string, b: string, t: number): string {
  const ca = hexToRgb(a), cb = hexToRgb(b);
  if (!ca || !cb) return a;
  return toHex([0, 1, 2].map((i) => ca[i] * (1 - t) + cb[i] * t) as [number, number, number]);
}

/** A theme the writer can follow: a resolved DeckTheme with concrete text and background colours
 *  (a host that hands the deck's theme ID string, or a partial theme, gets the generated ink). */
export function themeIsResolved(theme: unknown): theme is DeckTheme {
  const t = theme as Partial<DeckTheme> | null | undefined;
  return !!t && typeof t === "object" && typeof t.text === "string" && typeof t.background === "string";
}

/** Token → paint under a deck theme (`"none"` = transparent). The one mapping every host uses. */
export function themeInkPaints(theme: DeckTheme): Record<InkToken, string> {
  const text = theme.text.toLowerCase(), bg = theme.background.toLowerCase();
  return {
    ink: text, label: text, tick: text,
    axis: (theme.textMuted ?? theme.text).toLowerCase(),
    grid: mixHex(bg, text, GRID_MIX),
    plot: "none", paper: "none",
  };
}

const DRAWABLE = "path,use,rect,circle,ellipse,polygon,polyline,line,text,tspan";
function drawable(node: Element): Element[] {
  if (/^(path|use|rect|circle|ellipse|polygon|polyline|line|text|tspan)$/i.test(node.tagName)) return [node];
  return Array.from(node.querySelectorAll(DRAWABLE));
}

interface Pristine { fill: string; stroke: string; hadStyle: boolean }
interface RootState { touched: Set<Element>; key: string }
const roots = new WeakMap<Element, RootState>();
const pristine = new WeakMap<Element, Pristine>();

function capture(node: Element): void {
  if (pristine.has(node)) return;
  const st = (node as SVGElement).style;
  pristine.set(node, { fill: st.getPropertyValue("fill") ?? "", stroke: st.getPropertyValue("stroke") ?? "", hadStyle: node.hasAttribute("style") });
}

function restoreNode(node: Element): void {
  const rec = pristine.get(node);
  if (!rec) return;
  const st = (node as SVGElement).style;
  if (rec.fill) st.setProperty("fill", rec.fill); else st.removeProperty("fill");
  if (rec.stroke) st.setProperty("stroke", rec.stroke); else st.removeProperty("stroke");
  if (!rec.hadStyle && !node.getAttribute("style")) node.removeAttribute("style");
}

/** Put back everything this module wrote under `root`. */
export function restorePlotTheme(root: Element): void {
  const st = roots.get(root);
  if (!st) return;
  for (const node of st.touched) restoreNode(node);
  st.touched.clear();
  st.key = "";
}

export interface PlotThemeResult {
  /** Tagged nodes repainted (0 when the plot carries no ink tags — pre-B1 fluxplot). */
  painted: number;
  /** The paint written per token. */
  paints: Record<InkToken, string> | null;
}

/** Paint `root`'s tagged scaffold in `theme`'s ink; `theme` null (or a plot that does not
 *  follow) restores the generated paint. Idempotent: the same theme twice writes nothing. */
export function applyPlotTheme(root: Element, manifest: FluxPlotManifest | undefined, theme: DeckTheme | null | undefined): PlotThemeResult {
  void manifest; // the tags in the SVG are the source; the manifest's style block is informational
  if (!themeIsResolved(theme)) { restorePlotTheme(root); return { painted: 0, paints: null }; }
  const paints = themeInkPaints(theme);
  const key = INK_TOKENS.map((t) => paints[t]).join("|");
  let st = roots.get(root);
  if (st?.key === key) return { painted: st.touched.size, paints };
  if (st) restorePlotTheme(root); else { st = { touched: new Set(), key: "" }; roots.set(root, st); }
  for (const prop of ["fill", "stroke"] as const) {
    for (const tagged of Array.from(root.querySelectorAll(`[data-ink-${prop}]`))) {
      const token = tagged.getAttribute(`data-ink-${prop}`) as InkToken | null;
      if (!token || !(token in paints)) continue;
      const value = paints[token];
      for (const d of drawable(tagged)) {
        // a drawable painted `none` for this property stays unpainted (a tick's fill, a text's stroke)
        const style = (d as SVGElement).style;
        const current = (style.getPropertyValue(prop) || d.getAttribute(prop) || (prop === "fill" ? "#000000" : "none")).trim().toLowerCase();
        if (current === "none" && value !== "none") continue;
        capture(d); st.touched.add(d);
        style.setProperty(prop, value);
      }
    }
  }
  st.key = key;
  return { painted: st.touched.size, paints };
}
