// GENERATED by scripts/sync-fluxplot-schemas.mjs from src/lib/plot/schemas/*.schema.json
// (fluxplot's manifest and recipe contract). Do not edit; re-sync from fluxplot instead.
// Drift-gated by scripts/verify-fluxplot-schema.ts.
/* eslint-disable */

export type Axis = {
  scale: string;
  label?: string;
  base?: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  domain: [number, number];
  /**
   * @minItems 0
   */
  anchors: {
    data: number;
    svg: number;
  }[];
  supported?: boolean;
  ticks?: {
    value: number;
    label: string;
  }[];
  units?: {
    kind: string;
    epoch?: string;
    unit?: string;
  };
};

export interface FluxPlotManifestGen {
  spec: "fluxplot/manifest";
  schemaVersion: string;
  generator?: {
    name?: string;
    version?: string;
    matplotlib?: string;
  };
  plotType: string;
  svg: string;
  artifact?: {
    svgSha256?: string;
  };
  size: {
    width: number;
    height: number;
    unit: string;
  };
  axes: {
    id?: string;
    svgId?: string;
    panelId?: string;
    projection?: string;
    x: Axis;
    y: Axis;
    pixelBox?: {
      x0: number;
      y0: number;
      x1: number;
      y1: number;
    };
  }[];
  series: Series[];
  guides?: Guide[];
  overlays?: Overlay[];
  parts: PartNode;
  build: {
    order: string[];
    /**
     * Per-role build-animation hints, keyed by role (a consumer may override everything).
     */
    presets?: {
      [k: string]: {
        animation:
          "draw-on" | "fade-in" | "stagger-in" | "grow-from-baseline" | "fade-rise" | "write-on" | "pop-in";
        durationMs?: number;
        delayMs?: number;
        staggerMs?: number;
        staggerBy?: "x" | "y" | "index" | "value" | "count" | "category";
      };
    };
  };
  panels?: {
    id: string;
    svgId: string;
    label?: string;
    index?: number;
  }[];
  /**
   * Portable colour scales, one per colour-control key; see definitions/colorScale.
   */
  colorScales?: ColorScale[];
  /**
   * The theme in force at save: its name (null once the rcParams were changed by hand) and the scaffold colours by token (ink, label, tick, axis, grid, plot, paper), which data-ink-fill / data-ink-stroke on scaffold elements refer to.
   */
  style?: {
    theme: string | null;
    tokens: {
      ink: string;
      label: string;
      tick: string;
      axis: string;
      grid: string;
      plot: string;
      paper: string;
    };
  };
  /**
   * Lint findings recorded at save (fp.save(lint=...)): quality.color lists colorcheck findings.
   */
  quality?: {
    color?: {
      kind:
        | "cvd-confusable"
        | "greyscale-confusable"
        | "low-contrast-mark"
        | "low-contrast-text"
        | "non-uniform"
        | "non-monotone";
      a: string;
      b?: string | null;
      value: number;
      threshold: number;
      message: string;
    }[];
  };
}
/**
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: string;
  name?: string;
  kind?: string | null;
  roles?: string[];
  svg: {
    [k: string]: string | string[];
  };
  data?: {
    x?: (number | null)[];
    y?: (number | null)[];
  };
  label?: string;
  panelId?: string;
  rasterized?: boolean;
  capture?: {
    identity?: string;
    data?: string;
  };
  capabilities?: {
    dataMorph: boolean;
  };
  components?: {
    role: string;
    svgId: string;
    members?: string[];
    memberRole?: string;
  }[];
  points?: {
    index: number;
    svgId: string;
    x?: number | null;
    y?: number | null;
  }[];
  /**
   * The series' colour: hex = its primary paint (or 'varies' for a colour-mapped collection), alpha, token = the exact palette token naming it, palette = its position in the active cycle, scale = the colorScales[] id colouring it.
   */
  color?: {
    scale?: string;
    hex?: string;
    alpha?: number;
    token?: string;
    palette?: {
      name: string;
      index: number;
    };
  };
  bar?: {
    orientation?: string;
    baseline?: (number | null)[];
    length?: (number | null)[];
  };
  /**
   * An area's inputs: fp.band records {x, lo, hi, what}, fp.area {x, y1, y2}; a promoted fill_between only its polygon paths.
   */
  band?: {
    paths?: unknown[];
    x?: (number | null)[];
    lo?: (number | null)[];
    hi?: (number | null)[];
    what?: string;
    y1?: (number | null)[];
    y2?: (number | null)[];
  };
  uncertainty?: {
    xerr?: unknown[] | null;
    yerr?: unknown[] | null;
  };
  distribution?: Distribution;
  field?: Field;
  glowbar?: SignatureStats;
  fluxbox?: SignatureStats;
  hexmatrix?: Hexmatrix;
  surface?: Surface;
  /**
   * An fp.image: its channels (each a colorScales[] entry, <series>.<channel>), LUTs, display ranges, pixel size and extent.
   */
  image?: {
    shape: number[];
    channels: {
      name: string;
      lut?: string | {};
      displayRange: number[];
      scale: string;
      controlKey?: string;
    }[];
    composite?: "add" | "max";
    origin?: "upper" | "lower";
    extent?: number[];
    units?: string;
    pixelSize?: number[] | null;
  };
}
/**
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "distribution".
 */
export interface Distribution {
  binEdges?: (number | null)[];
  counts?: (number | null)[];
  normalization?: string;
  weighted?: boolean;
  cumulative?: boolean | number;
  orientation?: string;
  values?: (number | null)[];
}
/**
 * A colour-mapped mark's source-data colour contract (the portable law is colorScales[field.colorScale]).
 *
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "field".
 */
export interface Field {
  kind: "heatmap" | "contour" | "contourf" | "hexbin" | "scatter";
  shape?: number[];
  controlKey: string;
  colorScale?: string;
  includeValues?: boolean;
  normalization: Normalization;
  cmap: string;
  /**
   * How the recipe names the map: a resolvable name, or the portable {lut, under, over, bad} table.
   */
  cmapSpec?: string | {};
  extend?: "neither" | "min" | "max" | "both";
  label?: string | null;
  /**
   * @minItems 4
   * @maxItems 4
   */
  missingColor?: [number, number, number, number];
  /**
   * @minItems 4
   * @maxItems 4
   */
  underColor?: [number, number, number, number];
  /**
   * @minItems 4
   * @maxItems 4
   */
  overColor?: [number, number, number, number];
  maskedIndices?: number[];
  values?: (number | null)[][];
  levels?: (number | null)[];
  /**
   * @minItems 4
   * @maxItems 4
   */
  extent?: [number, number, number, number];
  origin?: string;
  grid?: {
    x?: unknown[];
    y?: unknown[];
  };
}
/**
 * A matplotlib norm by class name (alias of colorScales[].norm, whose kind is portable).
 *
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "normalization".
 */
export interface Normalization {
  kind: string;
  vmin: number | null;
  vmax: number | null;
  clip: boolean;
  vcenter?: number;
  halfrange?: number | null;
  gamma?: number;
  linthresh?: number;
  linscale?: number;
  base?: number;
  boundaries?: (number | null)[];
}
/**
 * fp.glowbar / fp.fluxbox payload: part=summary carries the statistics drawn for a category; part=unit a unit's identity.
 *
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "signatureStats".
 */
export interface SignatureStats {
  part: string;
  category?: unknown;
  units?: string | null;
  unit?: unknown;
  categories?: unknown[];
  colors?: string[];
  groupColor?: string;
  n?: number;
  mean?: number | null;
  median?: number | null;
  sd?: number | null;
  sem?: number | null;
  q1?: number | null;
  q3?: number | null;
  interval?: string;
  low?: number | null;
  high?: number | null;
  center?: string;
  centerValue?: number | null;
  x?: number | null;
  iqr?: number | null;
  whis?: unknown;
  whiskerLow?: number | null;
  whiskerHigh?: number | null;
  outliers?: (number | null)[];
  palette?: string | string[] | null;
}
/**
 * fp.hexmatrix payload: the lattice, the statistic and every hexagon drawn.
 *
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "hexmatrix".
 */
export interface Hexmatrix {
  orientation: "pointy" | "flat";
  hexRadius: number;
  aspect?: string | number;
  scale?: {
    x?: string;
    y?: string;
  };
  gridsize?: number | null;
  binwidth?: number | null;
  valueLabel?: string | null;
  nBins: number;
  mode?: "points" | "matrix";
  shape?: number[];
  origin?: string;
  n?: number;
  dropped?: number;
  stat?: string | null;
  reduce?: string | null;
  weighted?: boolean;
  mincnt?: number;
  sparse?: number | null;
  /**
   * @minItems 4
   * @maxItems 4
   */
  extent?: [number, number, number, number];
  hexArea?: number;
  boxAspect?: number;
  bins: {
    row: number;
    col: number;
    x: number;
    y: number;
    count?: number | null;
    value: number | null;
    svgId?: string;
  }[];
}
/**
 * fp.surface payload: the complete value→colour contract of a surface (brain) map and every part.
 *
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "surface".
 */
export interface Surface {
  kind: "label" | "continuous";
  cmap?: string;
  vmin?: number | null;
  vmax?: number | null;
  percentile?: unknown[] | null;
  palette?: {};
  views?: string[];
  hemispheres?: string[];
  panes?: string[];
  missingColor?: unknown;
  rendering?: {
    projection?: string;
    occlusion?: string;
    crossPartDepth?: string;
    missingLayer?: string;
  };
  missingRule?: {
    below?: number | null;
    values?: (number | null)[];
    zeroIsData?: boolean;
  };
  nVertices?: number;
  nMissing?: number;
  parts: SurfacePart[];
}
/**
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "surfacePart".
 */
export interface SurfacePart {
  part?: string;
  ref?: string;
  kind?: string;
  color?: unknown;
  vmin?: number | null;
  vmax?: number | null;
  cmap?: string;
  label?: string | null;
  editable?: string[];
  views?: string[];
  hemispheres?: string[];
  missingColor?: unknown;
  missingRule?: {};
  rendering?: {};
  percentile?: unknown[] | null;
}
/**
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "guide".
 */
export interface Guide {
  id: string;
  svgId?: string;
  role: string;
  axis?: string;
  entries?: LegendEntry[];
  orientation?: "vertical" | "horizontal";
  label?: string;
  ticks?: (number | null)[];
  normalization?: Normalization;
  cmap?: string;
  parts?: GuidePart[];
  mappable?: string;
  anchors?: {
    value: number;
    svg: number;
  }[];
  axisLength?: number | null;
  tickLocator?: "auto" | "log" | "fixed";
  tickFormatter?: "plain" | "sci" | "log" | "percent" | "custom";
  extend?: "neither" | "min" | "max" | "both";
  extendParts?: {
    min?: string;
    max?: string;
  };
  colorScale?: string;
}
/**
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "legendEntry".
 */
export interface LegendEntry {
  series?: string;
  part?: string;
  text?: string;
  swatch?: string;
  label?: string;
}
/**
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "guidePart".
 */
export interface GuidePart {
  svgId: string;
  role: string;
  kind?: string;
}
/**
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "overlay".
 */
export interface Overlay {
  id: string;
  svgId: string;
  role: string;
  kind?: string;
  name?: string;
  label?: string;
  between?: string[];
  p?: number;
  text?: string;
  rasterized?: boolean;
  /**
   * The test behind a significance bracket (fp.brackets): the fp.stats row it was drawn from.
   */
  stats?: {
    test?: string;
    statistic?: number;
    p?: number;
    pCorrected?: number;
    correction?: string;
    effectSizeMethod?: string;
    effectSize?: number;
    ciLow?: number;
    ciHigh?: number;
    n?: (number | null)[] | number;
    dof?: number;
    alternative?: string;
  };
  /**
   * A scale bar's length in data units.
   */
  length?: number;
  units?: string;
}
/**
 * A parts-tree node: a leaf (ref + role), a group (id, members, groupRole / memberRole) or a container (id, children).
 *
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "partNode".
 */
export interface PartNode {
  id?: string;
  ref?: string;
  role?: string;
  kind?: string;
  axis?: string;
  groupRole?: string;
  memberRole?: string;
  label?: string;
  members?: string[];
  children?: PartNode[];
}
/**
 * A portable colour scale (colorscale.py): the exact lookup table and norm of every colour-mapped mark, the svg groups it colours and the colour keys drawing it. The id equals the recipe's colour-control key.
 *
 * This interface was referenced by `FluxPlotManifestGen`'s JSON-Schema
 * via the `definition` "colorScale".
 */
export interface ColorScale {
  id: string;
  kind: "continuous" | "binned" | "categorical";
  colormap: {
    name: string;
    source: string;
    N: number;
    /**
     * @minItems 1
     */
    lut: [string, ...string[]];
    under: string;
    over: string;
    bad: string;
    discrete: boolean;
    approximate?: boolean;
  };
  norm: {
    kind: "linear" | "log" | "symlog" | "power" | "twoslope" | "centered" | "boundary" | "none" | "custom";
    vmin: number | null;
    vmax: number | null;
    clip: boolean;
    extend: "neither" | "min" | "max" | "both";
    vcenter?: number;
    halfrange?: number | null;
    gamma?: number;
    linthresh?: number;
    linscale?: number;
    base?: number;
    boundaries?: (number | null)[];
    ncolors?: number;
    className?: string;
  };
  mappables: string[];
  colorbars: string[];
  label?: string | null;
  recolor: "live" | "raster" | "regenerate";
  valueRaster?: string;
  editable: {
    cmap: boolean;
    limits: boolean;
    normKinds: string[];
    center: boolean;
  };
}

export interface FluxPlotRecipeGen {
  spec: "fluxplot/recipe";
  schemaVersion: string;
  plot: string;
  outputs: {
    svg?: string;
    glb?: string;
    manifest?: string;
  };
  generatedAt?: string | null;
  script?: {
    path?: string;
  } | null;
  params?: {};
  command?: string;
  args?: string[];
  cwd?: string;
  output?: string;
  /**
   * How the producing script was determined, plus the interpreter, platform, package versions, script hash and Git state.
   */
  provenance?: {
    scriptDiscovery: "automatic" | "explicit" | "notebook" | "unavailable" | "suppressed";
    scriptSha256?: string;
    python?: string;
    platform?: string;
    packages?: {
      [k: string]: string;
    };
    git?: {
      commit: string;
      dirty?: boolean;
    };
  };
  inputs: {
    role?: string;
    path: string | null;
    sha256?: string | null;
    bytes?: number;
  }[];
  env?: {} | null;
  /**
   * The notebook (and cell) that produced the plot when no script did: recorded for provenance, not rerunnable.
   */
  notebook?: {
    path: string;
    cell?: string | null;
    sha256?: string | null;
  };
}
